version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: room-booking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "54322:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d room-booking"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      # "./migrations/init.sql" - путь к миграциям БД
      - ./migrations/0001_init.up.sql:/docker-entrypoint-initdb.d/init.sql

#  app:
#    build: ../../Downloads/room-booking-service
#    depends_on:
#      postgres:
#        condition: service_healthy
#    env_file:
#      - ../../Downloads/room-booking-service/local.env
#    environment:
#      DATABASE_URL: postgres://booking:booking@postgres:5432/booking?sslmode=disable
#    ports:
#      - "8080:8080"
