// Code generated by http://github.com/gojuno/minimock (v3.4.5). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/avito-internships/test-backend-1-M1steryO/internal/repository.BookingRepository -o booking_repository_minimock.go -n BookingRepositoryMock -p mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	"time"
	mm_time "time"

	"github.com/avito-internships/test-backend-1-M1steryO/internal/domain"
	"github.com/gojuno/minimock/v3"
)

// BookingRepositoryMock implements mm_repository.BookingRepository
type BookingRepositoryMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCancelByOwner          func(ctx context.Context, bookingID string, userID string) (b1 domain.Booking, err error)
	funcCancelByOwnerOrigin    string
	inspectFuncCancelByOwner   func(ctx context.Context, bookingID string, userID string)
	afterCancelByOwnerCounter  uint64
	beforeCancelByOwnerCounter uint64
	CancelByOwnerMock          mBookingRepositoryMockCancelByOwner

	funcCreate          func(ctx context.Context, booking domain.Booking) (b1 domain.Booking, err error)
	funcCreateOrigin    string
	inspectFuncCreate   func(ctx context.Context, booking domain.Booking)
	afterCreateCounter  uint64
	beforeCreateCounter uint64
	CreateMock          mBookingRepositoryMockCreate

	funcGetByID          func(ctx context.Context, bookingID string) (b1 domain.Booking, err error)
	funcGetByIDOrigin    string
	inspectFuncGetByID   func(ctx context.Context, bookingID string)
	afterGetByIDCounter  uint64
	beforeGetByIDCounter uint64
	GetByIDMock          mBookingRepositoryMockGetByID

	funcListAll          func(ctx context.Context, page int, pageSize int) (ba1 []domain.Booking, i1 int, err error)
	funcListAllOrigin    string
	inspectFuncListAll   func(ctx context.Context, page int, pageSize int)
	afterListAllCounter  uint64
	beforeListAllCounter uint64
	ListAllMock          mBookingRepositoryMockListAll

	funcListByUser          func(ctx context.Context, userID string, now time.Time) (ba1 []domain.Booking, err error)
	funcListByUserOrigin    string
	inspectFuncListByUser   func(ctx context.Context, userID string, now time.Time)
	afterListByUserCounter  uint64
	beforeListByUserCounter uint64
	ListByUserMock          mBookingRepositoryMockListByUser
}

// NewBookingRepositoryMock returns a mock for mm_repository.BookingRepository
func NewBookingRepositoryMock(t minimock.Tester) *BookingRepositoryMock {
	m := &BookingRepositoryMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CancelByOwnerMock = mBookingRepositoryMockCancelByOwner{mock: m}
	m.CancelByOwnerMock.callArgs = []*BookingRepositoryMockCancelByOwnerParams{}

	m.CreateMock = mBookingRepositoryMockCreate{mock: m}
	m.CreateMock.callArgs = []*BookingRepositoryMockCreateParams{}

	m.GetByIDMock = mBookingRepositoryMockGetByID{mock: m}
	m.GetByIDMock.callArgs = []*BookingRepositoryMockGetByIDParams{}

	m.ListAllMock = mBookingRepositoryMockListAll{mock: m}
	m.ListAllMock.callArgs = []*BookingRepositoryMockListAllParams{}

	m.ListByUserMock = mBookingRepositoryMockListByUser{mock: m}
	m.ListByUserMock.callArgs = []*BookingRepositoryMockListByUserParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mBookingRepositoryMockCancelByOwner struct {
	optional           bool
	mock               *BookingRepositoryMock
	defaultExpectation *BookingRepositoryMockCancelByOwnerExpectation
	expectations       []*BookingRepositoryMockCancelByOwnerExpectation

	callArgs []*BookingRepositoryMockCancelByOwnerParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// BookingRepositoryMockCancelByOwnerExpectation specifies expectation struct of the BookingRepository.CancelByOwner
type BookingRepositoryMockCancelByOwnerExpectation struct {
	mock               *BookingRepositoryMock
	params             *BookingRepositoryMockCancelByOwnerParams
	paramPtrs          *BookingRepositoryMockCancelByOwnerParamPtrs
	expectationOrigins BookingRepositoryMockCancelByOwnerExpectationOrigins
	results            *BookingRepositoryMockCancelByOwnerResults
	returnOrigin       string
	Counter            uint64
}

// BookingRepositoryMockCancelByOwnerParams contains parameters of the BookingRepository.CancelByOwner
type BookingRepositoryMockCancelByOwnerParams struct {
	ctx       context.Context
	bookingID string
	userID    string
}

// BookingRepositoryMockCancelByOwnerParamPtrs contains pointers to parameters of the BookingRepository.CancelByOwner
type BookingRepositoryMockCancelByOwnerParamPtrs struct {
	ctx       *context.Context
	bookingID *string
	userID    *string
}

// BookingRepositoryMockCancelByOwnerResults contains results of the BookingRepository.CancelByOwner
type BookingRepositoryMockCancelByOwnerResults struct {
	b1  domain.Booking
	err error
}

// BookingRepositoryMockCancelByOwnerOrigins contains origins of expectations of the BookingRepository.CancelByOwner
type BookingRepositoryMockCancelByOwnerExpectationOrigins struct {
	origin          string
	originCtx       string
	originBookingID string
	originUserID    string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCancelByOwner *mBookingRepositoryMockCancelByOwner) Optional() *mBookingRepositoryMockCancelByOwner {
	mmCancelByOwner.optional = true
	return mmCancelByOwner
}

// Expect sets up expected params for BookingRepository.CancelByOwner
func (mmCancelByOwner *mBookingRepositoryMockCancelByOwner) Expect(ctx context.Context, bookingID string, userID string) *mBookingRepositoryMockCancelByOwner {
	if mmCancelByOwner.mock.funcCancelByOwner != nil {
		mmCancelByOwner.mock.t.Fatalf("BookingRepositoryMock.CancelByOwner mock is already set by Set")
	}

	if mmCancelByOwner.defaultExpectation == nil {
		mmCancelByOwner.defaultExpectation = &BookingRepositoryMockCancelByOwnerExpectation{}
	}

	if mmCancelByOwner.defaultExpectation.paramPtrs != nil {
		mmCancelByOwner.mock.t.Fatalf("BookingRepositoryMock.CancelByOwner mock is already set by ExpectParams functions")
	}

	mmCancelByOwner.defaultExpectation.params = &BookingRepositoryMockCancelByOwnerParams{ctx, bookingID, userID}
	mmCancelByOwner.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCancelByOwner.expectations {
		if minimock.Equal(e.params, mmCancelByOwner.defaultExpectation.params) {
			mmCancelByOwner.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCancelByOwner.defaultExpectation.params)
		}
	}

	return mmCancelByOwner
}

// ExpectCtxParam1 sets up expected param ctx for BookingRepository.CancelByOwner
func (mmCancelByOwner *mBookingRepositoryMockCancelByOwner) ExpectCtxParam1(ctx context.Context) *mBookingRepositoryMockCancelByOwner {
	if mmCancelByOwner.mock.funcCancelByOwner != nil {
		mmCancelByOwner.mock.t.Fatalf("BookingRepositoryMock.CancelByOwner mock is already set by Set")
	}

	if mmCancelByOwner.defaultExpectation == nil {
		mmCancelByOwner.defaultExpectation = &BookingRepositoryMockCancelByOwnerExpectation{}
	}

	if mmCancelByOwner.defaultExpectation.params != nil {
		mmCancelByOwner.mock.t.Fatalf("BookingRepositoryMock.CancelByOwner mock is already set by Expect")
	}

	if mmCancelByOwner.defaultExpectation.paramPtrs == nil {
		mmCancelByOwner.defaultExpectation.paramPtrs = &BookingRepositoryMockCancelByOwnerParamPtrs{}
	}
	mmCancelByOwner.defaultExpectation.paramPtrs.ctx = &ctx
	mmCancelByOwner.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCancelByOwner
}

// ExpectBookingIDParam2 sets up expected param bookingID for BookingRepository.CancelByOwner
func (mmCancelByOwner *mBookingRepositoryMockCancelByOwner) ExpectBookingIDParam2(bookingID string) *mBookingRepositoryMockCancelByOwner {
	if mmCancelByOwner.mock.funcCancelByOwner != nil {
		mmCancelByOwner.mock.t.Fatalf("BookingRepositoryMock.CancelByOwner mock is already set by Set")
	}

	if mmCancelByOwner.defaultExpectation == nil {
		mmCancelByOwner.defaultExpectation = &BookingRepositoryMockCancelByOwnerExpectation{}
	}

	if mmCancelByOwner.defaultExpectation.params != nil {
		mmCancelByOwner.mock.t.Fatalf("BookingRepositoryMock.CancelByOwner mock is already set by Expect")
	}

	if mmCancelByOwner.defaultExpectation.paramPtrs == nil {
		mmCancelByOwner.defaultExpectation.paramPtrs = &BookingRepositoryMockCancelByOwnerParamPtrs{}
	}
	mmCancelByOwner.defaultExpectation.paramPtrs.bookingID = &bookingID
	mmCancelByOwner.defaultExpectation.expectationOrigins.originBookingID = minimock.CallerInfo(1)

	return mmCancelByOwner
}

// ExpectUserIDParam3 sets up expected param userID for BookingRepository.CancelByOwner
func (mmCancelByOwner *mBookingRepositoryMockCancelByOwner) ExpectUserIDParam3(userID string) *mBookingRepositoryMockCancelByOwner {
	if mmCancelByOwner.mock.funcCancelByOwner != nil {
		mmCancelByOwner.mock.t.Fatalf("BookingRepositoryMock.CancelByOwner mock is already set by Set")
	}

	if mmCancelByOwner.defaultExpectation == nil {
		mmCancelByOwner.defaultExpectation = &BookingRepositoryMockCancelByOwnerExpectation{}
	}

	if mmCancelByOwner.defaultExpectation.params != nil {
		mmCancelByOwner.mock.t.Fatalf("BookingRepositoryMock.CancelByOwner mock is already set by Expect")
	}

	if mmCancelByOwner.defaultExpectation.paramPtrs == nil {
		mmCancelByOwner.defaultExpectation.paramPtrs = &BookingRepositoryMockCancelByOwnerParamPtrs{}
	}
	mmCancelByOwner.defaultExpectation.paramPtrs.userID = &userID
	mmCancelByOwner.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmCancelByOwner
}

// Inspect accepts an inspector function that has same arguments as the BookingRepository.CancelByOwner
func (mmCancelByOwner *mBookingRepositoryMockCancelByOwner) Inspect(f func(ctx context.Context, bookingID string, userID string)) *mBookingRepositoryMockCancelByOwner {
	if mmCancelByOwner.mock.inspectFuncCancelByOwner != nil {
		mmCancelByOwner.mock.t.Fatalf("Inspect function is already set for BookingRepositoryMock.CancelByOwner")
	}

	mmCancelByOwner.mock.inspectFuncCancelByOwner = f

	return mmCancelByOwner
}

// Return sets up results that will be returned by BookingRepository.CancelByOwner
func (mmCancelByOwner *mBookingRepositoryMockCancelByOwner) Return(b1 domain.Booking, err error) *BookingRepositoryMock {
	if mmCancelByOwner.mock.funcCancelByOwner != nil {
		mmCancelByOwner.mock.t.Fatalf("BookingRepositoryMock.CancelByOwner mock is already set by Set")
	}

	if mmCancelByOwner.defaultExpectation == nil {
		mmCancelByOwner.defaultExpectation = &BookingRepositoryMockCancelByOwnerExpectation{mock: mmCancelByOwner.mock}
	}
	mmCancelByOwner.defaultExpectation.results = &BookingRepositoryMockCancelByOwnerResults{b1, err}
	mmCancelByOwner.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCancelByOwner.mock
}

// Set uses given function f to mock the BookingRepository.CancelByOwner method
func (mmCancelByOwner *mBookingRepositoryMockCancelByOwner) Set(f func(ctx context.Context, bookingID string, userID string) (b1 domain.Booking, err error)) *BookingRepositoryMock {
	if mmCancelByOwner.defaultExpectation != nil {
		mmCancelByOwner.mock.t.Fatalf("Default expectation is already set for the BookingRepository.CancelByOwner method")
	}

	if len(mmCancelByOwner.expectations) > 0 {
		mmCancelByOwner.mock.t.Fatalf("Some expectations are already set for the BookingRepository.CancelByOwner method")
	}

	mmCancelByOwner.mock.funcCancelByOwner = f
	mmCancelByOwner.mock.funcCancelByOwnerOrigin = minimock.CallerInfo(1)
	return mmCancelByOwner.mock
}

// When sets expectation for the BookingRepository.CancelByOwner which will trigger the result defined by the following
// Then helper
func (mmCancelByOwner *mBookingRepositoryMockCancelByOwner) When(ctx context.Context, bookingID string, userID string) *BookingRepositoryMockCancelByOwnerExpectation {
	if mmCancelByOwner.mock.funcCancelByOwner != nil {
		mmCancelByOwner.mock.t.Fatalf("BookingRepositoryMock.CancelByOwner mock is already set by Set")
	}

	expectation := &BookingRepositoryMockCancelByOwnerExpectation{
		mock:               mmCancelByOwner.mock,
		params:             &BookingRepositoryMockCancelByOwnerParams{ctx, bookingID, userID},
		expectationOrigins: BookingRepositoryMockCancelByOwnerExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCancelByOwner.expectations = append(mmCancelByOwner.expectations, expectation)
	return expectation
}

// Then sets up BookingRepository.CancelByOwner return parameters for the expectation previously defined by the When method
func (e *BookingRepositoryMockCancelByOwnerExpectation) Then(b1 domain.Booking, err error) *BookingRepositoryMock {
	e.results = &BookingRepositoryMockCancelByOwnerResults{b1, err}
	return e.mock
}

// Times sets number of times BookingRepository.CancelByOwner should be invoked
func (mmCancelByOwner *mBookingRepositoryMockCancelByOwner) Times(n uint64) *mBookingRepositoryMockCancelByOwner {
	if n == 0 {
		mmCancelByOwner.mock.t.Fatalf("Times of BookingRepositoryMock.CancelByOwner mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCancelByOwner.expectedInvocations, n)
	mmCancelByOwner.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCancelByOwner
}

func (mmCancelByOwner *mBookingRepositoryMockCancelByOwner) invocationsDone() bool {
	if len(mmCancelByOwner.expectations) == 0 && mmCancelByOwner.defaultExpectation == nil && mmCancelByOwner.mock.funcCancelByOwner == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCancelByOwner.mock.afterCancelByOwnerCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCancelByOwner.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// CancelByOwner implements mm_repository.BookingRepository
func (mmCancelByOwner *BookingRepositoryMock) CancelByOwner(ctx context.Context, bookingID string, userID string) (b1 domain.Booking, err error) {
	mm_atomic.AddUint64(&mmCancelByOwner.beforeCancelByOwnerCounter, 1)
	defer mm_atomic.AddUint64(&mmCancelByOwner.afterCancelByOwnerCounter, 1)

	mmCancelByOwner.t.Helper()

	if mmCancelByOwner.inspectFuncCancelByOwner != nil {
		mmCancelByOwner.inspectFuncCancelByOwner(ctx, bookingID, userID)
	}

	mm_params := BookingRepositoryMockCancelByOwnerParams{ctx, bookingID, userID}

	// Record call args
	mmCancelByOwner.CancelByOwnerMock.mutex.Lock()
	mmCancelByOwner.CancelByOwnerMock.callArgs = append(mmCancelByOwner.CancelByOwnerMock.callArgs, &mm_params)
	mmCancelByOwner.CancelByOwnerMock.mutex.Unlock()

	for _, e := range mmCancelByOwner.CancelByOwnerMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.b1, e.results.err
		}
	}

	if mmCancelByOwner.CancelByOwnerMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCancelByOwner.CancelByOwnerMock.defaultExpectation.Counter, 1)
		mm_want := mmCancelByOwner.CancelByOwnerMock.defaultExpectation.params
		mm_want_ptrs := mmCancelByOwner.CancelByOwnerMock.defaultExpectation.paramPtrs

		mm_got := BookingRepositoryMockCancelByOwnerParams{ctx, bookingID, userID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCancelByOwner.t.Errorf("BookingRepositoryMock.CancelByOwner got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCancelByOwner.CancelByOwnerMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.bookingID != nil && !minimock.Equal(*mm_want_ptrs.bookingID, mm_got.bookingID) {
				mmCancelByOwner.t.Errorf("BookingRepositoryMock.CancelByOwner got unexpected parameter bookingID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCancelByOwner.CancelByOwnerMock.defaultExpectation.expectationOrigins.originBookingID, *mm_want_ptrs.bookingID, mm_got.bookingID, minimock.Diff(*mm_want_ptrs.bookingID, mm_got.bookingID))
			}

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmCancelByOwner.t.Errorf("BookingRepositoryMock.CancelByOwner got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCancelByOwner.CancelByOwnerMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCancelByOwner.t.Errorf("BookingRepositoryMock.CancelByOwner got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCancelByOwner.CancelByOwnerMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCancelByOwner.CancelByOwnerMock.defaultExpectation.results
		if mm_results == nil {
			mmCancelByOwner.t.Fatal("No results are set for the BookingRepositoryMock.CancelByOwner")
		}
		return (*mm_results).b1, (*mm_results).err
	}
	if mmCancelByOwner.funcCancelByOwner != nil {
		return mmCancelByOwner.funcCancelByOwner(ctx, bookingID, userID)
	}
	mmCancelByOwner.t.Fatalf("Unexpected call to BookingRepositoryMock.CancelByOwner. %v %v %v", ctx, bookingID, userID)
	return
}

// CancelByOwnerAfterCounter returns a count of finished BookingRepositoryMock.CancelByOwner invocations
func (mmCancelByOwner *BookingRepositoryMock) CancelByOwnerAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCancelByOwner.afterCancelByOwnerCounter)
}

// CancelByOwnerBeforeCounter returns a count of BookingRepositoryMock.CancelByOwner invocations
func (mmCancelByOwner *BookingRepositoryMock) CancelByOwnerBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCancelByOwner.beforeCancelByOwnerCounter)
}

// Calls returns a list of arguments used in each call to BookingRepositoryMock.CancelByOwner.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCancelByOwner *mBookingRepositoryMockCancelByOwner) Calls() []*BookingRepositoryMockCancelByOwnerParams {
	mmCancelByOwner.mutex.RLock()

	argCopy := make([]*BookingRepositoryMockCancelByOwnerParams, len(mmCancelByOwner.callArgs))
	copy(argCopy, mmCancelByOwner.callArgs)

	mmCancelByOwner.mutex.RUnlock()

	return argCopy
}

// MinimockCancelByOwnerDone returns true if the count of the CancelByOwner invocations corresponds
// the number of defined expectations
func (m *BookingRepositoryMock) MinimockCancelByOwnerDone() bool {
	if m.CancelByOwnerMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CancelByOwnerMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CancelByOwnerMock.invocationsDone()
}

// MinimockCancelByOwnerInspect logs each unmet expectation
func (m *BookingRepositoryMock) MinimockCancelByOwnerInspect() {
	for _, e := range m.CancelByOwnerMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to BookingRepositoryMock.CancelByOwner at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCancelByOwnerCounter := mm_atomic.LoadUint64(&m.afterCancelByOwnerCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CancelByOwnerMock.defaultExpectation != nil && afterCancelByOwnerCounter < 1 {
		if m.CancelByOwnerMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to BookingRepositoryMock.CancelByOwner at\n%s", m.CancelByOwnerMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to BookingRepositoryMock.CancelByOwner at\n%s with params: %#v", m.CancelByOwnerMock.defaultExpectation.expectationOrigins.origin, *m.CancelByOwnerMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCancelByOwner != nil && afterCancelByOwnerCounter < 1 {
		m.t.Errorf("Expected call to BookingRepositoryMock.CancelByOwner at\n%s", m.funcCancelByOwnerOrigin)
	}

	if !m.CancelByOwnerMock.invocationsDone() && afterCancelByOwnerCounter > 0 {
		m.t.Errorf("Expected %d calls to BookingRepositoryMock.CancelByOwner at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CancelByOwnerMock.expectedInvocations), m.CancelByOwnerMock.expectedInvocationsOrigin, afterCancelByOwnerCounter)
	}
}

type mBookingRepositoryMockCreate struct {
	optional           bool
	mock               *BookingRepositoryMock
	defaultExpectation *BookingRepositoryMockCreateExpectation
	expectations       []*BookingRepositoryMockCreateExpectation

	callArgs []*BookingRepositoryMockCreateParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// BookingRepositoryMockCreateExpectation specifies expectation struct of the BookingRepository.Create
type BookingRepositoryMockCreateExpectation struct {
	mock               *BookingRepositoryMock
	params             *BookingRepositoryMockCreateParams
	paramPtrs          *BookingRepositoryMockCreateParamPtrs
	expectationOrigins BookingRepositoryMockCreateExpectationOrigins
	results            *BookingRepositoryMockCreateResults
	returnOrigin       string
	Counter            uint64
}

// BookingRepositoryMockCreateParams contains parameters of the BookingRepository.Create
type BookingRepositoryMockCreateParams struct {
	ctx     context.Context
	booking domain.Booking
}

// BookingRepositoryMockCreateParamPtrs contains pointers to parameters of the BookingRepository.Create
type BookingRepositoryMockCreateParamPtrs struct {
	ctx     *context.Context
	booking *domain.Booking
}

// BookingRepositoryMockCreateResults contains results of the BookingRepository.Create
type BookingRepositoryMockCreateResults struct {
	b1  domain.Booking
	err error
}

// BookingRepositoryMockCreateOrigins contains origins of expectations of the BookingRepository.Create
type BookingRepositoryMockCreateExpectationOrigins struct {
	origin        string
	originCtx     string
	originBooking string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreate *mBookingRepositoryMockCreate) Optional() *mBookingRepositoryMockCreate {
	mmCreate.optional = true
	return mmCreate
}

// Expect sets up expected params for BookingRepository.Create
func (mmCreate *mBookingRepositoryMockCreate) Expect(ctx context.Context, booking domain.Booking) *mBookingRepositoryMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("BookingRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &BookingRepositoryMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.paramPtrs != nil {
		mmCreate.mock.t.Fatalf("BookingRepositoryMock.Create mock is already set by ExpectParams functions")
	}

	mmCreate.defaultExpectation.params = &BookingRepositoryMockCreateParams{ctx, booking}
	mmCreate.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreate.expectations {
		if minimock.Equal(e.params, mmCreate.defaultExpectation.params) {
			mmCreate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreate.defaultExpectation.params)
		}
	}

	return mmCreate
}

// ExpectCtxParam1 sets up expected param ctx for BookingRepository.Create
func (mmCreate *mBookingRepositoryMockCreate) ExpectCtxParam1(ctx context.Context) *mBookingRepositoryMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("BookingRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &BookingRepositoryMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("BookingRepositoryMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &BookingRepositoryMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreate.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreate
}

// ExpectBookingParam2 sets up expected param booking for BookingRepository.Create
func (mmCreate *mBookingRepositoryMockCreate) ExpectBookingParam2(booking domain.Booking) *mBookingRepositoryMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("BookingRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &BookingRepositoryMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("BookingRepositoryMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &BookingRepositoryMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.booking = &booking
	mmCreate.defaultExpectation.expectationOrigins.originBooking = minimock.CallerInfo(1)

	return mmCreate
}

// Inspect accepts an inspector function that has same arguments as the BookingRepository.Create
func (mmCreate *mBookingRepositoryMockCreate) Inspect(f func(ctx context.Context, booking domain.Booking)) *mBookingRepositoryMockCreate {
	if mmCreate.mock.inspectFuncCreate != nil {
		mmCreate.mock.t.Fatalf("Inspect function is already set for BookingRepositoryMock.Create")
	}

	mmCreate.mock.inspectFuncCreate = f

	return mmCreate
}

// Return sets up results that will be returned by BookingRepository.Create
func (mmCreate *mBookingRepositoryMockCreate) Return(b1 domain.Booking, err error) *BookingRepositoryMock {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("BookingRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &BookingRepositoryMockCreateExpectation{mock: mmCreate.mock}
	}
	mmCreate.defaultExpectation.results = &BookingRepositoryMockCreateResults{b1, err}
	mmCreate.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreate.mock
}

// Set uses given function f to mock the BookingRepository.Create method
func (mmCreate *mBookingRepositoryMockCreate) Set(f func(ctx context.Context, booking domain.Booking) (b1 domain.Booking, err error)) *BookingRepositoryMock {
	if mmCreate.defaultExpectation != nil {
		mmCreate.mock.t.Fatalf("Default expectation is already set for the BookingRepository.Create method")
	}

	if len(mmCreate.expectations) > 0 {
		mmCreate.mock.t.Fatalf("Some expectations are already set for the BookingRepository.Create method")
	}

	mmCreate.mock.funcCreate = f
	mmCreate.mock.funcCreateOrigin = minimock.CallerInfo(1)
	return mmCreate.mock
}

// When sets expectation for the BookingRepository.Create which will trigger the result defined by the following
// Then helper
func (mmCreate *mBookingRepositoryMockCreate) When(ctx context.Context, booking domain.Booking) *BookingRepositoryMockCreateExpectation {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("BookingRepositoryMock.Create mock is already set by Set")
	}

	expectation := &BookingRepositoryMockCreateExpectation{
		mock:               mmCreate.mock,
		params:             &BookingRepositoryMockCreateParams{ctx, booking},
		expectationOrigins: BookingRepositoryMockCreateExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreate.expectations = append(mmCreate.expectations, expectation)
	return expectation
}

// Then sets up BookingRepository.Create return parameters for the expectation previously defined by the When method
func (e *BookingRepositoryMockCreateExpectation) Then(b1 domain.Booking, err error) *BookingRepositoryMock {
	e.results = &BookingRepositoryMockCreateResults{b1, err}
	return e.mock
}

// Times sets number of times BookingRepository.Create should be invoked
func (mmCreate *mBookingRepositoryMockCreate) Times(n uint64) *mBookingRepositoryMockCreate {
	if n == 0 {
		mmCreate.mock.t.Fatalf("Times of BookingRepositoryMock.Create mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreate.expectedInvocations, n)
	mmCreate.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreate
}

func (mmCreate *mBookingRepositoryMockCreate) invocationsDone() bool {
	if len(mmCreate.expectations) == 0 && mmCreate.defaultExpectation == nil && mmCreate.mock.funcCreate == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreate.mock.afterCreateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreate.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Create implements mm_repository.BookingRepository
func (mmCreate *BookingRepositoryMock) Create(ctx context.Context, booking domain.Booking) (b1 domain.Booking, err error) {
	mm_atomic.AddUint64(&mmCreate.beforeCreateCounter, 1)
	defer mm_atomic.AddUint64(&mmCreate.afterCreateCounter, 1)

	mmCreate.t.Helper()

	if mmCreate.inspectFuncCreate != nil {
		mmCreate.inspectFuncCreate(ctx, booking)
	}

	mm_params := BookingRepositoryMockCreateParams{ctx, booking}

	// Record call args
	mmCreate.CreateMock.mutex.Lock()
	mmCreate.CreateMock.callArgs = append(mmCreate.CreateMock.callArgs, &mm_params)
	mmCreate.CreateMock.mutex.Unlock()

	for _, e := range mmCreate.CreateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.b1, e.results.err
		}
	}

	if mmCreate.CreateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreate.CreateMock.defaultExpectation.Counter, 1)
		mm_want := mmCreate.CreateMock.defaultExpectation.params
		mm_want_ptrs := mmCreate.CreateMock.defaultExpectation.paramPtrs

		mm_got := BookingRepositoryMockCreateParams{ctx, booking}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreate.t.Errorf("BookingRepositoryMock.Create got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.booking != nil && !minimock.Equal(*mm_want_ptrs.booking, mm_got.booking) {
				mmCreate.t.Errorf("BookingRepositoryMock.Create got unexpected parameter booking, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originBooking, *mm_want_ptrs.booking, mm_got.booking, minimock.Diff(*mm_want_ptrs.booking, mm_got.booking))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreate.t.Errorf("BookingRepositoryMock.Create got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreate.CreateMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreate.CreateMock.defaultExpectation.results
		if mm_results == nil {
			mmCreate.t.Fatal("No results are set for the BookingRepositoryMock.Create")
		}
		return (*mm_results).b1, (*mm_results).err
	}
	if mmCreate.funcCreate != nil {
		return mmCreate.funcCreate(ctx, booking)
	}
	mmCreate.t.Fatalf("Unexpected call to BookingRepositoryMock.Create. %v %v", ctx, booking)
	return
}

// CreateAfterCounter returns a count of finished BookingRepositoryMock.Create invocations
func (mmCreate *BookingRepositoryMock) CreateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.afterCreateCounter)
}

// CreateBeforeCounter returns a count of BookingRepositoryMock.Create invocations
func (mmCreate *BookingRepositoryMock) CreateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.beforeCreateCounter)
}

// Calls returns a list of arguments used in each call to BookingRepositoryMock.Create.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreate *mBookingRepositoryMockCreate) Calls() []*BookingRepositoryMockCreateParams {
	mmCreate.mutex.RLock()

	argCopy := make([]*BookingRepositoryMockCreateParams, len(mmCreate.callArgs))
	copy(argCopy, mmCreate.callArgs)

	mmCreate.mutex.RUnlock()

	return argCopy
}

// MinimockCreateDone returns true if the count of the Create invocations corresponds
// the number of defined expectations
func (m *BookingRepositoryMock) MinimockCreateDone() bool {
	if m.CreateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateMock.invocationsDone()
}

// MinimockCreateInspect logs each unmet expectation
func (m *BookingRepositoryMock) MinimockCreateInspect() {
	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to BookingRepositoryMock.Create at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateCounter := mm_atomic.LoadUint64(&m.afterCreateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateMock.defaultExpectation != nil && afterCreateCounter < 1 {
		if m.CreateMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to BookingRepositoryMock.Create at\n%s", m.CreateMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to BookingRepositoryMock.Create at\n%s with params: %#v", m.CreateMock.defaultExpectation.expectationOrigins.origin, *m.CreateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreate != nil && afterCreateCounter < 1 {
		m.t.Errorf("Expected call to BookingRepositoryMock.Create at\n%s", m.funcCreateOrigin)
	}

	if !m.CreateMock.invocationsDone() && afterCreateCounter > 0 {
		m.t.Errorf("Expected %d calls to BookingRepositoryMock.Create at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateMock.expectedInvocations), m.CreateMock.expectedInvocationsOrigin, afterCreateCounter)
	}
}

type mBookingRepositoryMockGetByID struct {
	optional           bool
	mock               *BookingRepositoryMock
	defaultExpectation *BookingRepositoryMockGetByIDExpectation
	expectations       []*BookingRepositoryMockGetByIDExpectation

	callArgs []*BookingRepositoryMockGetByIDParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// BookingRepositoryMockGetByIDExpectation specifies expectation struct of the BookingRepository.GetByID
type BookingRepositoryMockGetByIDExpectation struct {
	mock               *BookingRepositoryMock
	params             *BookingRepositoryMockGetByIDParams
	paramPtrs          *BookingRepositoryMockGetByIDParamPtrs
	expectationOrigins BookingRepositoryMockGetByIDExpectationOrigins
	results            *BookingRepositoryMockGetByIDResults
	returnOrigin       string
	Counter            uint64
}

// BookingRepositoryMockGetByIDParams contains parameters of the BookingRepository.GetByID
type BookingRepositoryMockGetByIDParams struct {
	ctx       context.Context
	bookingID string
}

// BookingRepositoryMockGetByIDParamPtrs contains pointers to parameters of the BookingRepository.GetByID
type BookingRepositoryMockGetByIDParamPtrs struct {
	ctx       *context.Context
	bookingID *string
}

// BookingRepositoryMockGetByIDResults contains results of the BookingRepository.GetByID
type BookingRepositoryMockGetByIDResults struct {
	b1  domain.Booking
	err error
}

// BookingRepositoryMockGetByIDOrigins contains origins of expectations of the BookingRepository.GetByID
type BookingRepositoryMockGetByIDExpectationOrigins struct {
	origin          string
	originCtx       string
	originBookingID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetByID *mBookingRepositoryMockGetByID) Optional() *mBookingRepositoryMockGetByID {
	mmGetByID.optional = true
	return mmGetByID
}

// Expect sets up expected params for BookingRepository.GetByID
func (mmGetByID *mBookingRepositoryMockGetByID) Expect(ctx context.Context, bookingID string) *mBookingRepositoryMockGetByID {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("BookingRepositoryMock.GetByID mock is already set by Set")
	}

	if mmGetByID.defaultExpectation == nil {
		mmGetByID.defaultExpectation = &BookingRepositoryMockGetByIDExpectation{}
	}

	if mmGetByID.defaultExpectation.paramPtrs != nil {
		mmGetByID.mock.t.Fatalf("BookingRepositoryMock.GetByID mock is already set by ExpectParams functions")
	}

	mmGetByID.defaultExpectation.params = &BookingRepositoryMockGetByIDParams{ctx, bookingID}
	mmGetByID.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetByID.expectations {
		if minimock.Equal(e.params, mmGetByID.defaultExpectation.params) {
			mmGetByID.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetByID.defaultExpectation.params)
		}
	}

	return mmGetByID
}

// ExpectCtxParam1 sets up expected param ctx for BookingRepository.GetByID
func (mmGetByID *mBookingRepositoryMockGetByID) ExpectCtxParam1(ctx context.Context) *mBookingRepositoryMockGetByID {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("BookingRepositoryMock.GetByID mock is already set by Set")
	}

	if mmGetByID.defaultExpectation == nil {
		mmGetByID.defaultExpectation = &BookingRepositoryMockGetByIDExpectation{}
	}

	if mmGetByID.defaultExpectation.params != nil {
		mmGetByID.mock.t.Fatalf("BookingRepositoryMock.GetByID mock is already set by Expect")
	}

	if mmGetByID.defaultExpectation.paramPtrs == nil {
		mmGetByID.defaultExpectation.paramPtrs = &BookingRepositoryMockGetByIDParamPtrs{}
	}
	mmGetByID.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetByID.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetByID
}

// ExpectBookingIDParam2 sets up expected param bookingID for BookingRepository.GetByID
func (mmGetByID *mBookingRepositoryMockGetByID) ExpectBookingIDParam2(bookingID string) *mBookingRepositoryMockGetByID {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("BookingRepositoryMock.GetByID mock is already set by Set")
	}

	if mmGetByID.defaultExpectation == nil {
		mmGetByID.defaultExpectation = &BookingRepositoryMockGetByIDExpectation{}
	}

	if mmGetByID.defaultExpectation.params != nil {
		mmGetByID.mock.t.Fatalf("BookingRepositoryMock.GetByID mock is already set by Expect")
	}

	if mmGetByID.defaultExpectation.paramPtrs == nil {
		mmGetByID.defaultExpectation.paramPtrs = &BookingRepositoryMockGetByIDParamPtrs{}
	}
	mmGetByID.defaultExpectation.paramPtrs.bookingID = &bookingID
	mmGetByID.defaultExpectation.expectationOrigins.originBookingID = minimock.CallerInfo(1)

	return mmGetByID
}

// Inspect accepts an inspector function that has same arguments as the BookingRepository.GetByID
func (mmGetByID *mBookingRepositoryMockGetByID) Inspect(f func(ctx context.Context, bookingID string)) *mBookingRepositoryMockGetByID {
	if mmGetByID.mock.inspectFuncGetByID != nil {
		mmGetByID.mock.t.Fatalf("Inspect function is already set for BookingRepositoryMock.GetByID")
	}

	mmGetByID.mock.inspectFuncGetByID = f

	return mmGetByID
}

// Return sets up results that will be returned by BookingRepository.GetByID
func (mmGetByID *mBookingRepositoryMockGetByID) Return(b1 domain.Booking, err error) *BookingRepositoryMock {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("BookingRepositoryMock.GetByID mock is already set by Set")
	}

	if mmGetByID.defaultExpectation == nil {
		mmGetByID.defaultExpectation = &BookingRepositoryMockGetByIDExpectation{mock: mmGetByID.mock}
	}
	mmGetByID.defaultExpectation.results = &BookingRepositoryMockGetByIDResults{b1, err}
	mmGetByID.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetByID.mock
}

// Set uses given function f to mock the BookingRepository.GetByID method
func (mmGetByID *mBookingRepositoryMockGetByID) Set(f func(ctx context.Context, bookingID string) (b1 domain.Booking, err error)) *BookingRepositoryMock {
	if mmGetByID.defaultExpectation != nil {
		mmGetByID.mock.t.Fatalf("Default expectation is already set for the BookingRepository.GetByID method")
	}

	if len(mmGetByID.expectations) > 0 {
		mmGetByID.mock.t.Fatalf("Some expectations are already set for the BookingRepository.GetByID method")
	}

	mmGetByID.mock.funcGetByID = f
	mmGetByID.mock.funcGetByIDOrigin = minimock.CallerInfo(1)
	return mmGetByID.mock
}

// When sets expectation for the BookingRepository.GetByID which will trigger the result defined by the following
// Then helper
func (mmGetByID *mBookingRepositoryMockGetByID) When(ctx context.Context, bookingID string) *BookingRepositoryMockGetByIDExpectation {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("BookingRepositoryMock.GetByID mock is already set by Set")
	}

	expectation := &BookingRepositoryMockGetByIDExpectation{
		mock:               mmGetByID.mock,
		params:             &BookingRepositoryMockGetByIDParams{ctx, bookingID},
		expectationOrigins: BookingRepositoryMockGetByIDExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetByID.expectations = append(mmGetByID.expectations, expectation)
	return expectation
}

// Then sets up BookingRepository.GetByID return parameters for the expectation previously defined by the When method
func (e *BookingRepositoryMockGetByIDExpectation) Then(b1 domain.Booking, err error) *BookingRepositoryMock {
	e.results = &BookingRepositoryMockGetByIDResults{b1, err}
	return e.mock
}

// Times sets number of times BookingRepository.GetByID should be invoked
func (mmGetByID *mBookingRepositoryMockGetByID) Times(n uint64) *mBookingRepositoryMockGetByID {
	if n == 0 {
		mmGetByID.mock.t.Fatalf("Times of BookingRepositoryMock.GetByID mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetByID.expectedInvocations, n)
	mmGetByID.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetByID
}

func (mmGetByID *mBookingRepositoryMockGetByID) invocationsDone() bool {
	if len(mmGetByID.expectations) == 0 && mmGetByID.defaultExpectation == nil && mmGetByID.mock.funcGetByID == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetByID.mock.afterGetByIDCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetByID.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetByID implements mm_repository.BookingRepository
func (mmGetByID *BookingRepositoryMock) GetByID(ctx context.Context, bookingID string) (b1 domain.Booking, err error) {
	mm_atomic.AddUint64(&mmGetByID.beforeGetByIDCounter, 1)
	defer mm_atomic.AddUint64(&mmGetByID.afterGetByIDCounter, 1)

	mmGetByID.t.Helper()

	if mmGetByID.inspectFuncGetByID != nil {
		mmGetByID.inspectFuncGetByID(ctx, bookingID)
	}

	mm_params := BookingRepositoryMockGetByIDParams{ctx, bookingID}

	// Record call args
	mmGetByID.GetByIDMock.mutex.Lock()
	mmGetByID.GetByIDMock.callArgs = append(mmGetByID.GetByIDMock.callArgs, &mm_params)
	mmGetByID.GetByIDMock.mutex.Unlock()

	for _, e := range mmGetByID.GetByIDMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.b1, e.results.err
		}
	}

	if mmGetByID.GetByIDMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetByID.GetByIDMock.defaultExpectation.Counter, 1)
		mm_want := mmGetByID.GetByIDMock.defaultExpectation.params
		mm_want_ptrs := mmGetByID.GetByIDMock.defaultExpectation.paramPtrs

		mm_got := BookingRepositoryMockGetByIDParams{ctx, bookingID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetByID.t.Errorf("BookingRepositoryMock.GetByID got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByID.GetByIDMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.bookingID != nil && !minimock.Equal(*mm_want_ptrs.bookingID, mm_got.bookingID) {
				mmGetByID.t.Errorf("BookingRepositoryMock.GetByID got unexpected parameter bookingID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByID.GetByIDMock.defaultExpectation.expectationOrigins.originBookingID, *mm_want_ptrs.bookingID, mm_got.bookingID, minimock.Diff(*mm_want_ptrs.bookingID, mm_got.bookingID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetByID.t.Errorf("BookingRepositoryMock.GetByID got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetByID.GetByIDMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetByID.GetByIDMock.defaultExpectation.results
		if mm_results == nil {
			mmGetByID.t.Fatal("No results are set for the BookingRepositoryMock.GetByID")
		}
		return (*mm_results).b1, (*mm_results).err
	}
	if mmGetByID.funcGetByID != nil {
		return mmGetByID.funcGetByID(ctx, bookingID)
	}
	mmGetByID.t.Fatalf("Unexpected call to BookingRepositoryMock.GetByID. %v %v", ctx, bookingID)
	return
}

// GetByIDAfterCounter returns a count of finished BookingRepositoryMock.GetByID invocations
func (mmGetByID *BookingRepositoryMock) GetByIDAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByID.afterGetByIDCounter)
}

// GetByIDBeforeCounter returns a count of BookingRepositoryMock.GetByID invocations
func (mmGetByID *BookingRepositoryMock) GetByIDBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByID.beforeGetByIDCounter)
}

// Calls returns a list of arguments used in each call to BookingRepositoryMock.GetByID.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetByID *mBookingRepositoryMockGetByID) Calls() []*BookingRepositoryMockGetByIDParams {
	mmGetByID.mutex.RLock()

	argCopy := make([]*BookingRepositoryMockGetByIDParams, len(mmGetByID.callArgs))
	copy(argCopy, mmGetByID.callArgs)

	mmGetByID.mutex.RUnlock()

	return argCopy
}

// MinimockGetByIDDone returns true if the count of the GetByID invocations corresponds
// the number of defined expectations
func (m *BookingRepositoryMock) MinimockGetByIDDone() bool {
	if m.GetByIDMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetByIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetByIDMock.invocationsDone()
}

// MinimockGetByIDInspect logs each unmet expectation
func (m *BookingRepositoryMock) MinimockGetByIDInspect() {
	for _, e := range m.GetByIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to BookingRepositoryMock.GetByID at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetByIDCounter := mm_atomic.LoadUint64(&m.afterGetByIDCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetByIDMock.defaultExpectation != nil && afterGetByIDCounter < 1 {
		if m.GetByIDMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to BookingRepositoryMock.GetByID at\n%s", m.GetByIDMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to BookingRepositoryMock.GetByID at\n%s with params: %#v", m.GetByIDMock.defaultExpectation.expectationOrigins.origin, *m.GetByIDMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetByID != nil && afterGetByIDCounter < 1 {
		m.t.Errorf("Expected call to BookingRepositoryMock.GetByID at\n%s", m.funcGetByIDOrigin)
	}

	if !m.GetByIDMock.invocationsDone() && afterGetByIDCounter > 0 {
		m.t.Errorf("Expected %d calls to BookingRepositoryMock.GetByID at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetByIDMock.expectedInvocations), m.GetByIDMock.expectedInvocationsOrigin, afterGetByIDCounter)
	}
}

type mBookingRepositoryMockListAll struct {
	optional           bool
	mock               *BookingRepositoryMock
	defaultExpectation *BookingRepositoryMockListAllExpectation
	expectations       []*BookingRepositoryMockListAllExpectation

	callArgs []*BookingRepositoryMockListAllParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// BookingRepositoryMockListAllExpectation specifies expectation struct of the BookingRepository.ListAll
type BookingRepositoryMockListAllExpectation struct {
	mock               *BookingRepositoryMock
	params             *BookingRepositoryMockListAllParams
	paramPtrs          *BookingRepositoryMockListAllParamPtrs
	expectationOrigins BookingRepositoryMockListAllExpectationOrigins
	results            *BookingRepositoryMockListAllResults
	returnOrigin       string
	Counter            uint64
}

// BookingRepositoryMockListAllParams contains parameters of the BookingRepository.ListAll
type BookingRepositoryMockListAllParams struct {
	ctx      context.Context
	page     int
	pageSize int
}

// BookingRepositoryMockListAllParamPtrs contains pointers to parameters of the BookingRepository.ListAll
type BookingRepositoryMockListAllParamPtrs struct {
	ctx      *context.Context
	page     *int
	pageSize *int
}

// BookingRepositoryMockListAllResults contains results of the BookingRepository.ListAll
type BookingRepositoryMockListAllResults struct {
	ba1 []domain.Booking
	i1  int
	err error
}

// BookingRepositoryMockListAllOrigins contains origins of expectations of the BookingRepository.ListAll
type BookingRepositoryMockListAllExpectationOrigins struct {
	origin         string
	originCtx      string
	originPage     string
	originPageSize string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmListAll *mBookingRepositoryMockListAll) Optional() *mBookingRepositoryMockListAll {
	mmListAll.optional = true
	return mmListAll
}

// Expect sets up expected params for BookingRepository.ListAll
func (mmListAll *mBookingRepositoryMockListAll) Expect(ctx context.Context, page int, pageSize int) *mBookingRepositoryMockListAll {
	if mmListAll.mock.funcListAll != nil {
		mmListAll.mock.t.Fatalf("BookingRepositoryMock.ListAll mock is already set by Set")
	}

	if mmListAll.defaultExpectation == nil {
		mmListAll.defaultExpectation = &BookingRepositoryMockListAllExpectation{}
	}

	if mmListAll.defaultExpectation.paramPtrs != nil {
		mmListAll.mock.t.Fatalf("BookingRepositoryMock.ListAll mock is already set by ExpectParams functions")
	}

	mmListAll.defaultExpectation.params = &BookingRepositoryMockListAllParams{ctx, page, pageSize}
	mmListAll.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmListAll.expectations {
		if minimock.Equal(e.params, mmListAll.defaultExpectation.params) {
			mmListAll.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmListAll.defaultExpectation.params)
		}
	}

	return mmListAll
}

// ExpectCtxParam1 sets up expected param ctx for BookingRepository.ListAll
func (mmListAll *mBookingRepositoryMockListAll) ExpectCtxParam1(ctx context.Context) *mBookingRepositoryMockListAll {
	if mmListAll.mock.funcListAll != nil {
		mmListAll.mock.t.Fatalf("BookingRepositoryMock.ListAll mock is already set by Set")
	}

	if mmListAll.defaultExpectation == nil {
		mmListAll.defaultExpectation = &BookingRepositoryMockListAllExpectation{}
	}

	if mmListAll.defaultExpectation.params != nil {
		mmListAll.mock.t.Fatalf("BookingRepositoryMock.ListAll mock is already set by Expect")
	}

	if mmListAll.defaultExpectation.paramPtrs == nil {
		mmListAll.defaultExpectation.paramPtrs = &BookingRepositoryMockListAllParamPtrs{}
	}
	mmListAll.defaultExpectation.paramPtrs.ctx = &ctx
	mmListAll.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmListAll
}

// ExpectPageParam2 sets up expected param page for BookingRepository.ListAll
func (mmListAll *mBookingRepositoryMockListAll) ExpectPageParam2(page int) *mBookingRepositoryMockListAll {
	if mmListAll.mock.funcListAll != nil {
		mmListAll.mock.t.Fatalf("BookingRepositoryMock.ListAll mock is already set by Set")
	}

	if mmListAll.defaultExpectation == nil {
		mmListAll.defaultExpectation = &BookingRepositoryMockListAllExpectation{}
	}

	if mmListAll.defaultExpectation.params != nil {
		mmListAll.mock.t.Fatalf("BookingRepositoryMock.ListAll mock is already set by Expect")
	}

	if mmListAll.defaultExpectation.paramPtrs == nil {
		mmListAll.defaultExpectation.paramPtrs = &BookingRepositoryMockListAllParamPtrs{}
	}
	mmListAll.defaultExpectation.paramPtrs.page = &page
	mmListAll.defaultExpectation.expectationOrigins.originPage = minimock.CallerInfo(1)

	return mmListAll
}

// ExpectPageSizeParam3 sets up expected param pageSize for BookingRepository.ListAll
func (mmListAll *mBookingRepositoryMockListAll) ExpectPageSizeParam3(pageSize int) *mBookingRepositoryMockListAll {
	if mmListAll.mock.funcListAll != nil {
		mmListAll.mock.t.Fatalf("BookingRepositoryMock.ListAll mock is already set by Set")
	}

	if mmListAll.defaultExpectation == nil {
		mmListAll.defaultExpectation = &BookingRepositoryMockListAllExpectation{}
	}

	if mmListAll.defaultExpectation.params != nil {
		mmListAll.mock.t.Fatalf("BookingRepositoryMock.ListAll mock is already set by Expect")
	}

	if mmListAll.defaultExpectation.paramPtrs == nil {
		mmListAll.defaultExpectation.paramPtrs = &BookingRepositoryMockListAllParamPtrs{}
	}
	mmListAll.defaultExpectation.paramPtrs.pageSize = &pageSize
	mmListAll.defaultExpectation.expectationOrigins.originPageSize = minimock.CallerInfo(1)

	return mmListAll
}

// Inspect accepts an inspector function that has same arguments as the BookingRepository.ListAll
func (mmListAll *mBookingRepositoryMockListAll) Inspect(f func(ctx context.Context, page int, pageSize int)) *mBookingRepositoryMockListAll {
	if mmListAll.mock.inspectFuncListAll != nil {
		mmListAll.mock.t.Fatalf("Inspect function is already set for BookingRepositoryMock.ListAll")
	}

	mmListAll.mock.inspectFuncListAll = f

	return mmListAll
}

// Return sets up results that will be returned by BookingRepository.ListAll
func (mmListAll *mBookingRepositoryMockListAll) Return(ba1 []domain.Booking, i1 int, err error) *BookingRepositoryMock {
	if mmListAll.mock.funcListAll != nil {
		mmListAll.mock.t.Fatalf("BookingRepositoryMock.ListAll mock is already set by Set")
	}

	if mmListAll.defaultExpectation == nil {
		mmListAll.defaultExpectation = &BookingRepositoryMockListAllExpectation{mock: mmListAll.mock}
	}
	mmListAll.defaultExpectation.results = &BookingRepositoryMockListAllResults{ba1, i1, err}
	mmListAll.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmListAll.mock
}

// Set uses given function f to mock the BookingRepository.ListAll method
func (mmListAll *mBookingRepositoryMockListAll) Set(f func(ctx context.Context, page int, pageSize int) (ba1 []domain.Booking, i1 int, err error)) *BookingRepositoryMock {
	if mmListAll.defaultExpectation != nil {
		mmListAll.mock.t.Fatalf("Default expectation is already set for the BookingRepository.ListAll method")
	}

	if len(mmListAll.expectations) > 0 {
		mmListAll.mock.t.Fatalf("Some expectations are already set for the BookingRepository.ListAll method")
	}

	mmListAll.mock.funcListAll = f
	mmListAll.mock.funcListAllOrigin = minimock.CallerInfo(1)
	return mmListAll.mock
}

// When sets expectation for the BookingRepository.ListAll which will trigger the result defined by the following
// Then helper
func (mmListAll *mBookingRepositoryMockListAll) When(ctx context.Context, page int, pageSize int) *BookingRepositoryMockListAllExpectation {
	if mmListAll.mock.funcListAll != nil {
		mmListAll.mock.t.Fatalf("BookingRepositoryMock.ListAll mock is already set by Set")
	}

	expectation := &BookingRepositoryMockListAllExpectation{
		mock:               mmListAll.mock,
		params:             &BookingRepositoryMockListAllParams{ctx, page, pageSize},
		expectationOrigins: BookingRepositoryMockListAllExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmListAll.expectations = append(mmListAll.expectations, expectation)
	return expectation
}

// Then sets up BookingRepository.ListAll return parameters for the expectation previously defined by the When method
func (e *BookingRepositoryMockListAllExpectation) Then(ba1 []domain.Booking, i1 int, err error) *BookingRepositoryMock {
	e.results = &BookingRepositoryMockListAllResults{ba1, i1, err}
	return e.mock
}

// Times sets number of times BookingRepository.ListAll should be invoked
func (mmListAll *mBookingRepositoryMockListAll) Times(n uint64) *mBookingRepositoryMockListAll {
	if n == 0 {
		mmListAll.mock.t.Fatalf("Times of BookingRepositoryMock.ListAll mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmListAll.expectedInvocations, n)
	mmListAll.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmListAll
}

func (mmListAll *mBookingRepositoryMockListAll) invocationsDone() bool {
	if len(mmListAll.expectations) == 0 && mmListAll.defaultExpectation == nil && mmListAll.mock.funcListAll == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmListAll.mock.afterListAllCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmListAll.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// ListAll implements mm_repository.BookingRepository
func (mmListAll *BookingRepositoryMock) ListAll(ctx context.Context, page int, pageSize int) (ba1 []domain.Booking, i1 int, err error) {
	mm_atomic.AddUint64(&mmListAll.beforeListAllCounter, 1)
	defer mm_atomic.AddUint64(&mmListAll.afterListAllCounter, 1)

	mmListAll.t.Helper()

	if mmListAll.inspectFuncListAll != nil {
		mmListAll.inspectFuncListAll(ctx, page, pageSize)
	}

	mm_params := BookingRepositoryMockListAllParams{ctx, page, pageSize}

	// Record call args
	mmListAll.ListAllMock.mutex.Lock()
	mmListAll.ListAllMock.callArgs = append(mmListAll.ListAllMock.callArgs, &mm_params)
	mmListAll.ListAllMock.mutex.Unlock()

	for _, e := range mmListAll.ListAllMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ba1, e.results.i1, e.results.err
		}
	}

	if mmListAll.ListAllMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmListAll.ListAllMock.defaultExpectation.Counter, 1)
		mm_want := mmListAll.ListAllMock.defaultExpectation.params
		mm_want_ptrs := mmListAll.ListAllMock.defaultExpectation.paramPtrs

		mm_got := BookingRepositoryMockListAllParams{ctx, page, pageSize}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmListAll.t.Errorf("BookingRepositoryMock.ListAll got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmListAll.ListAllMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.page != nil && !minimock.Equal(*mm_want_ptrs.page, mm_got.page) {
				mmListAll.t.Errorf("BookingRepositoryMock.ListAll got unexpected parameter page, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmListAll.ListAllMock.defaultExpectation.expectationOrigins.originPage, *mm_want_ptrs.page, mm_got.page, minimock.Diff(*mm_want_ptrs.page, mm_got.page))
			}

			if mm_want_ptrs.pageSize != nil && !minimock.Equal(*mm_want_ptrs.pageSize, mm_got.pageSize) {
				mmListAll.t.Errorf("BookingRepositoryMock.ListAll got unexpected parameter pageSize, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmListAll.ListAllMock.defaultExpectation.expectationOrigins.originPageSize, *mm_want_ptrs.pageSize, mm_got.pageSize, minimock.Diff(*mm_want_ptrs.pageSize, mm_got.pageSize))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmListAll.t.Errorf("BookingRepositoryMock.ListAll got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmListAll.ListAllMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmListAll.ListAllMock.defaultExpectation.results
		if mm_results == nil {
			mmListAll.t.Fatal("No results are set for the BookingRepositoryMock.ListAll")
		}
		return (*mm_results).ba1, (*mm_results).i1, (*mm_results).err
	}
	if mmListAll.funcListAll != nil {
		return mmListAll.funcListAll(ctx, page, pageSize)
	}
	mmListAll.t.Fatalf("Unexpected call to BookingRepositoryMock.ListAll. %v %v %v", ctx, page, pageSize)
	return
}

// ListAllAfterCounter returns a count of finished BookingRepositoryMock.ListAll invocations
func (mmListAll *BookingRepositoryMock) ListAllAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmListAll.afterListAllCounter)
}

// ListAllBeforeCounter returns a count of BookingRepositoryMock.ListAll invocations
func (mmListAll *BookingRepositoryMock) ListAllBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmListAll.beforeListAllCounter)
}

// Calls returns a list of arguments used in each call to BookingRepositoryMock.ListAll.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmListAll *mBookingRepositoryMockListAll) Calls() []*BookingRepositoryMockListAllParams {
	mmListAll.mutex.RLock()

	argCopy := make([]*BookingRepositoryMockListAllParams, len(mmListAll.callArgs))
	copy(argCopy, mmListAll.callArgs)

	mmListAll.mutex.RUnlock()

	return argCopy
}

// MinimockListAllDone returns true if the count of the ListAll invocations corresponds
// the number of defined expectations
func (m *BookingRepositoryMock) MinimockListAllDone() bool {
	if m.ListAllMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ListAllMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ListAllMock.invocationsDone()
}

// MinimockListAllInspect logs each unmet expectation
func (m *BookingRepositoryMock) MinimockListAllInspect() {
	for _, e := range m.ListAllMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to BookingRepositoryMock.ListAll at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterListAllCounter := mm_atomic.LoadUint64(&m.afterListAllCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ListAllMock.defaultExpectation != nil && afterListAllCounter < 1 {
		if m.ListAllMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to BookingRepositoryMock.ListAll at\n%s", m.ListAllMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to BookingRepositoryMock.ListAll at\n%s with params: %#v", m.ListAllMock.defaultExpectation.expectationOrigins.origin, *m.ListAllMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcListAll != nil && afterListAllCounter < 1 {
		m.t.Errorf("Expected call to BookingRepositoryMock.ListAll at\n%s", m.funcListAllOrigin)
	}

	if !m.ListAllMock.invocationsDone() && afterListAllCounter > 0 {
		m.t.Errorf("Expected %d calls to BookingRepositoryMock.ListAll at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ListAllMock.expectedInvocations), m.ListAllMock.expectedInvocationsOrigin, afterListAllCounter)
	}
}

type mBookingRepositoryMockListByUser struct {
	optional           bool
	mock               *BookingRepositoryMock
	defaultExpectation *BookingRepositoryMockListByUserExpectation
	expectations       []*BookingRepositoryMockListByUserExpectation

	callArgs []*BookingRepositoryMockListByUserParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// BookingRepositoryMockListByUserExpectation specifies expectation struct of the BookingRepository.ListByUser
type BookingRepositoryMockListByUserExpectation struct {
	mock               *BookingRepositoryMock
	params             *BookingRepositoryMockListByUserParams
	paramPtrs          *BookingRepositoryMockListByUserParamPtrs
	expectationOrigins BookingRepositoryMockListByUserExpectationOrigins
	results            *BookingRepositoryMockListByUserResults
	returnOrigin       string
	Counter            uint64
}

// BookingRepositoryMockListByUserParams contains parameters of the BookingRepository.ListByUser
type BookingRepositoryMockListByUserParams struct {
	ctx    context.Context
	userID string
	now    time.Time
}

// BookingRepositoryMockListByUserParamPtrs contains pointers to parameters of the BookingRepository.ListByUser
type BookingRepositoryMockListByUserParamPtrs struct {
	ctx    *context.Context
	userID *string
	now    *time.Time
}

// BookingRepositoryMockListByUserResults contains results of the BookingRepository.ListByUser
type BookingRepositoryMockListByUserResults struct {
	ba1 []domain.Booking
	err error
}

// BookingRepositoryMockListByUserOrigins contains origins of expectations of the BookingRepository.ListByUser
type BookingRepositoryMockListByUserExpectationOrigins struct {
	origin       string
	originCtx    string
	originUserID string
	originNow    string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmListByUser *mBookingRepositoryMockListByUser) Optional() *mBookingRepositoryMockListByUser {
	mmListByUser.optional = true
	return mmListByUser
}

// Expect sets up expected params for BookingRepository.ListByUser
func (mmListByUser *mBookingRepositoryMockListByUser) Expect(ctx context.Context, userID string, now time.Time) *mBookingRepositoryMockListByUser {
	if mmListByUser.mock.funcListByUser != nil {
		mmListByUser.mock.t.Fatalf("BookingRepositoryMock.ListByUser mock is already set by Set")
	}

	if mmListByUser.defaultExpectation == nil {
		mmListByUser.defaultExpectation = &BookingRepositoryMockListByUserExpectation{}
	}

	if mmListByUser.defaultExpectation.paramPtrs != nil {
		mmListByUser.mock.t.Fatalf("BookingRepositoryMock.ListByUser mock is already set by ExpectParams functions")
	}

	mmListByUser.defaultExpectation.params = &BookingRepositoryMockListByUserParams{ctx, userID, now}
	mmListByUser.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmListByUser.expectations {
		if minimock.Equal(e.params, mmListByUser.defaultExpectation.params) {
			mmListByUser.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmListByUser.defaultExpectation.params)
		}
	}

	return mmListByUser
}

// ExpectCtxParam1 sets up expected param ctx for BookingRepository.ListByUser
func (mmListByUser *mBookingRepositoryMockListByUser) ExpectCtxParam1(ctx context.Context) *mBookingRepositoryMockListByUser {
	if mmListByUser.mock.funcListByUser != nil {
		mmListByUser.mock.t.Fatalf("BookingRepositoryMock.ListByUser mock is already set by Set")
	}

	if mmListByUser.defaultExpectation == nil {
		mmListByUser.defaultExpectation = &BookingRepositoryMockListByUserExpectation{}
	}

	if mmListByUser.defaultExpectation.params != nil {
		mmListByUser.mock.t.Fatalf("BookingRepositoryMock.ListByUser mock is already set by Expect")
	}

	if mmListByUser.defaultExpectation.paramPtrs == nil {
		mmListByUser.defaultExpectation.paramPtrs = &BookingRepositoryMockListByUserParamPtrs{}
	}
	mmListByUser.defaultExpectation.paramPtrs.ctx = &ctx
	mmListByUser.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmListByUser
}

// ExpectUserIDParam2 sets up expected param userID for BookingRepository.ListByUser
func (mmListByUser *mBookingRepositoryMockListByUser) ExpectUserIDParam2(userID string) *mBookingRepositoryMockListByUser {
	if mmListByUser.mock.funcListByUser != nil {
		mmListByUser.mock.t.Fatalf("BookingRepositoryMock.ListByUser mock is already set by Set")
	}

	if mmListByUser.defaultExpectation == nil {
		mmListByUser.defaultExpectation = &BookingRepositoryMockListByUserExpectation{}
	}

	if mmListByUser.defaultExpectation.params != nil {
		mmListByUser.mock.t.Fatalf("BookingRepositoryMock.ListByUser mock is already set by Expect")
	}

	if mmListByUser.defaultExpectation.paramPtrs == nil {
		mmListByUser.defaultExpectation.paramPtrs = &BookingRepositoryMockListByUserParamPtrs{}
	}
	mmListByUser.defaultExpectation.paramPtrs.userID = &userID
	mmListByUser.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmListByUser
}

// ExpectNowParam3 sets up expected param now for BookingRepository.ListByUser
func (mmListByUser *mBookingRepositoryMockListByUser) ExpectNowParam3(now time.Time) *mBookingRepositoryMockListByUser {
	if mmListByUser.mock.funcListByUser != nil {
		mmListByUser.mock.t.Fatalf("BookingRepositoryMock.ListByUser mock is already set by Set")
	}

	if mmListByUser.defaultExpectation == nil {
		mmListByUser.defaultExpectation = &BookingRepositoryMockListByUserExpectation{}
	}

	if mmListByUser.defaultExpectation.params != nil {
		mmListByUser.mock.t.Fatalf("BookingRepositoryMock.ListByUser mock is already set by Expect")
	}

	if mmListByUser.defaultExpectation.paramPtrs == nil {
		mmListByUser.defaultExpectation.paramPtrs = &BookingRepositoryMockListByUserParamPtrs{}
	}
	mmListByUser.defaultExpectation.paramPtrs.now = &now
	mmListByUser.defaultExpectation.expectationOrigins.originNow = minimock.CallerInfo(1)

	return mmListByUser
}

// Inspect accepts an inspector function that has same arguments as the BookingRepository.ListByUser
func (mmListByUser *mBookingRepositoryMockListByUser) Inspect(f func(ctx context.Context, userID string, now time.Time)) *mBookingRepositoryMockListByUser {
	if mmListByUser.mock.inspectFuncListByUser != nil {
		mmListByUser.mock.t.Fatalf("Inspect function is already set for BookingRepositoryMock.ListByUser")
	}

	mmListByUser.mock.inspectFuncListByUser = f

	return mmListByUser
}

// Return sets up results that will be returned by BookingRepository.ListByUser
func (mmListByUser *mBookingRepositoryMockListByUser) Return(ba1 []domain.Booking, err error) *BookingRepositoryMock {
	if mmListByUser.mock.funcListByUser != nil {
		mmListByUser.mock.t.Fatalf("BookingRepositoryMock.ListByUser mock is already set by Set")
	}

	if mmListByUser.defaultExpectation == nil {
		mmListByUser.defaultExpectation = &BookingRepositoryMockListByUserExpectation{mock: mmListByUser.mock}
	}
	mmListByUser.defaultExpectation.results = &BookingRepositoryMockListByUserResults{ba1, err}
	mmListByUser.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmListByUser.mock
}

// Set uses given function f to mock the BookingRepository.ListByUser method
func (mmListByUser *mBookingRepositoryMockListByUser) Set(f func(ctx context.Context, userID string, now time.Time) (ba1 []domain.Booking, err error)) *BookingRepositoryMock {
	if mmListByUser.defaultExpectation != nil {
		mmListByUser.mock.t.Fatalf("Default expectation is already set for the BookingRepository.ListByUser method")
	}

	if len(mmListByUser.expectations) > 0 {
		mmListByUser.mock.t.Fatalf("Some expectations are already set for the BookingRepository.ListByUser method")
	}

	mmListByUser.mock.funcListByUser = f
	mmListByUser.mock.funcListByUserOrigin = minimock.CallerInfo(1)
	return mmListByUser.mock
}

// When sets expectation for the BookingRepository.ListByUser which will trigger the result defined by the following
// Then helper
func (mmListByUser *mBookingRepositoryMockListByUser) When(ctx context.Context, userID string, now time.Time) *BookingRepositoryMockListByUserExpectation {
	if mmListByUser.mock.funcListByUser != nil {
		mmListByUser.mock.t.Fatalf("BookingRepositoryMock.ListByUser mock is already set by Set")
	}

	expectation := &BookingRepositoryMockListByUserExpectation{
		mock:               mmListByUser.mock,
		params:             &BookingRepositoryMockListByUserParams{ctx, userID, now},
		expectationOrigins: BookingRepositoryMockListByUserExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmListByUser.expectations = append(mmListByUser.expectations, expectation)
	return expectation
}

// Then sets up BookingRepository.ListByUser return parameters for the expectation previously defined by the When method
func (e *BookingRepositoryMockListByUserExpectation) Then(ba1 []domain.Booking, err error) *BookingRepositoryMock {
	e.results = &BookingRepositoryMockListByUserResults{ba1, err}
	return e.mock
}

// Times sets number of times BookingRepository.ListByUser should be invoked
func (mmListByUser *mBookingRepositoryMockListByUser) Times(n uint64) *mBookingRepositoryMockListByUser {
	if n == 0 {
		mmListByUser.mock.t.Fatalf("Times of BookingRepositoryMock.ListByUser mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmListByUser.expectedInvocations, n)
	mmListByUser.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmListByUser
}

func (mmListByUser *mBookingRepositoryMockListByUser) invocationsDone() bool {
	if len(mmListByUser.expectations) == 0 && mmListByUser.defaultExpectation == nil && mmListByUser.mock.funcListByUser == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmListByUser.mock.afterListByUserCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmListByUser.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// ListByUser implements mm_repository.BookingRepository
func (mmListByUser *BookingRepositoryMock) ListByUser(ctx context.Context, userID string, now time.Time) (ba1 []domain.Booking, err error) {
	mm_atomic.AddUint64(&mmListByUser.beforeListByUserCounter, 1)
	defer mm_atomic.AddUint64(&mmListByUser.afterListByUserCounter, 1)

	mmListByUser.t.Helper()

	if mmListByUser.inspectFuncListByUser != nil {
		mmListByUser.inspectFuncListByUser(ctx, userID, now)
	}

	mm_params := BookingRepositoryMockListByUserParams{ctx, userID, now}

	// Record call args
	mmListByUser.ListByUserMock.mutex.Lock()
	mmListByUser.ListByUserMock.callArgs = append(mmListByUser.ListByUserMock.callArgs, &mm_params)
	mmListByUser.ListByUserMock.mutex.Unlock()

	for _, e := range mmListByUser.ListByUserMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ba1, e.results.err
		}
	}

	if mmListByUser.ListByUserMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmListByUser.ListByUserMock.defaultExpectation.Counter, 1)
		mm_want := mmListByUser.ListByUserMock.defaultExpectation.params
		mm_want_ptrs := mmListByUser.ListByUserMock.defaultExpectation.paramPtrs

		mm_got := BookingRepositoryMockListByUserParams{ctx, userID, now}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmListByUser.t.Errorf("BookingRepositoryMock.ListByUser got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmListByUser.ListByUserMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmListByUser.t.Errorf("BookingRepositoryMock.ListByUser got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmListByUser.ListByUserMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

			if mm_want_ptrs.now != nil && !minimock.Equal(*mm_want_ptrs.now, mm_got.now) {
				mmListByUser.t.Errorf("BookingRepositoryMock.ListByUser got unexpected parameter now, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmListByUser.ListByUserMock.defaultExpectation.expectationOrigins.originNow, *mm_want_ptrs.now, mm_got.now, minimock.Diff(*mm_want_ptrs.now, mm_got.now))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmListByUser.t.Errorf("BookingRepositoryMock.ListByUser got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmListByUser.ListByUserMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmListByUser.ListByUserMock.defaultExpectation.results
		if mm_results == nil {
			mmListByUser.t.Fatal("No results are set for the BookingRepositoryMock.ListByUser")
		}
		return (*mm_results).ba1, (*mm_results).err
	}
	if mmListByUser.funcListByUser != nil {
		return mmListByUser.funcListByUser(ctx, userID, now)
	}
	mmListByUser.t.Fatalf("Unexpected call to BookingRepositoryMock.ListByUser. %v %v %v", ctx, userID, now)
	return
}

// ListByUserAfterCounter returns a count of finished BookingRepositoryMock.ListByUser invocations
func (mmListByUser *BookingRepositoryMock) ListByUserAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmListByUser.afterListByUserCounter)
}

// ListByUserBeforeCounter returns a count of BookingRepositoryMock.ListByUser invocations
func (mmListByUser *BookingRepositoryMock) ListByUserBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmListByUser.beforeListByUserCounter)
}

// Calls returns a list of arguments used in each call to BookingRepositoryMock.ListByUser.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmListByUser *mBookingRepositoryMockListByUser) Calls() []*BookingRepositoryMockListByUserParams {
	mmListByUser.mutex.RLock()

	argCopy := make([]*BookingRepositoryMockListByUserParams, len(mmListByUser.callArgs))
	copy(argCopy, mmListByUser.callArgs)

	mmListByUser.mutex.RUnlock()

	return argCopy
}

// MinimockListByUserDone returns true if the count of the ListByUser invocations corresponds
// the number of defined expectations
func (m *BookingRepositoryMock) MinimockListByUserDone() bool {
	if m.ListByUserMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ListByUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ListByUserMock.invocationsDone()
}

// MinimockListByUserInspect logs each unmet expectation
func (m *BookingRepositoryMock) MinimockListByUserInspect() {
	for _, e := range m.ListByUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to BookingRepositoryMock.ListByUser at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterListByUserCounter := mm_atomic.LoadUint64(&m.afterListByUserCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ListByUserMock.defaultExpectation != nil && afterListByUserCounter < 1 {
		if m.ListByUserMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to BookingRepositoryMock.ListByUser at\n%s", m.ListByUserMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to BookingRepositoryMock.ListByUser at\n%s with params: %#v", m.ListByUserMock.defaultExpectation.expectationOrigins.origin, *m.ListByUserMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcListByUser != nil && afterListByUserCounter < 1 {
		m.t.Errorf("Expected call to BookingRepositoryMock.ListByUser at\n%s", m.funcListByUserOrigin)
	}

	if !m.ListByUserMock.invocationsDone() && afterListByUserCounter > 0 {
		m.t.Errorf("Expected %d calls to BookingRepositoryMock.ListByUser at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ListByUserMock.expectedInvocations), m.ListByUserMock.expectedInvocationsOrigin, afterListByUserCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *BookingRepositoryMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCancelByOwnerInspect()

			m.MinimockCreateInspect()

			m.MinimockGetByIDInspect()

			m.MinimockListAllInspect()

			m.MinimockListByUserInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *BookingRepositoryMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *BookingRepositoryMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCancelByOwnerDone() &&
		m.MinimockCreateDone() &&
		m.MinimockGetByIDDone() &&
		m.MinimockListAllDone() &&
		m.MinimockListByUserDone()
}
