// Code generated by http://github.com/gojuno/minimock (v3.4.5). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/avito-internships/test-backend-1-M1steryO/internal/repository.RoomRepository -o room_repository_minimock.go -n RoomRepositoryMock -p mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/avito-internships/test-backend-1-M1steryO/internal/domain"
	"github.com/gojuno/minimock/v3"
)

// RoomRepositoryMock implements mm_repository.RoomRepository
type RoomRepositoryMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreate          func(ctx context.Context, room domain.Room) (r1 domain.Room, err error)
	funcCreateOrigin    string
	inspectFuncCreate   func(ctx context.Context, room domain.Room)
	afterCreateCounter  uint64
	beforeCreateCounter uint64
	CreateMock          mRoomRepositoryMockCreate

	funcGetByID          func(ctx context.Context, roomID string) (r1 domain.Room, err error)
	funcGetByIDOrigin    string
	inspectFuncGetByID   func(ctx context.Context, roomID string)
	afterGetByIDCounter  uint64
	beforeGetByIDCounter uint64
	GetByIDMock          mRoomRepositoryMockGetByID

	funcList          func(ctx context.Context) (ra1 []domain.Room, err error)
	funcListOrigin    string
	inspectFuncList   func(ctx context.Context)
	afterListCounter  uint64
	beforeListCounter uint64
	ListMock          mRoomRepositoryMockList
}

// NewRoomRepositoryMock returns a mock for mm_repository.RoomRepository
func NewRoomRepositoryMock(t minimock.Tester) *RoomRepositoryMock {
	m := &RoomRepositoryMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateMock = mRoomRepositoryMockCreate{mock: m}
	m.CreateMock.callArgs = []*RoomRepositoryMockCreateParams{}

	m.GetByIDMock = mRoomRepositoryMockGetByID{mock: m}
	m.GetByIDMock.callArgs = []*RoomRepositoryMockGetByIDParams{}

	m.ListMock = mRoomRepositoryMockList{mock: m}
	m.ListMock.callArgs = []*RoomRepositoryMockListParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mRoomRepositoryMockCreate struct {
	optional           bool
	mock               *RoomRepositoryMock
	defaultExpectation *RoomRepositoryMockCreateExpectation
	expectations       []*RoomRepositoryMockCreateExpectation

	callArgs []*RoomRepositoryMockCreateParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// RoomRepositoryMockCreateExpectation specifies expectation struct of the RoomRepository.Create
type RoomRepositoryMockCreateExpectation struct {
	mock               *RoomRepositoryMock
	params             *RoomRepositoryMockCreateParams
	paramPtrs          *RoomRepositoryMockCreateParamPtrs
	expectationOrigins RoomRepositoryMockCreateExpectationOrigins
	results            *RoomRepositoryMockCreateResults
	returnOrigin       string
	Counter            uint64
}

// RoomRepositoryMockCreateParams contains parameters of the RoomRepository.Create
type RoomRepositoryMockCreateParams struct {
	ctx  context.Context
	room domain.Room
}

// RoomRepositoryMockCreateParamPtrs contains pointers to parameters of the RoomRepository.Create
type RoomRepositoryMockCreateParamPtrs struct {
	ctx  *context.Context
	room *domain.Room
}

// RoomRepositoryMockCreateResults contains results of the RoomRepository.Create
type RoomRepositoryMockCreateResults struct {
	r1  domain.Room
	err error
}

// RoomRepositoryMockCreateOrigins contains origins of expectations of the RoomRepository.Create
type RoomRepositoryMockCreateExpectationOrigins struct {
	origin     string
	originCtx  string
	originRoom string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreate *mRoomRepositoryMockCreate) Optional() *mRoomRepositoryMockCreate {
	mmCreate.optional = true
	return mmCreate
}

// Expect sets up expected params for RoomRepository.Create
func (mmCreate *mRoomRepositoryMockCreate) Expect(ctx context.Context, room domain.Room) *mRoomRepositoryMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("RoomRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &RoomRepositoryMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.paramPtrs != nil {
		mmCreate.mock.t.Fatalf("RoomRepositoryMock.Create mock is already set by ExpectParams functions")
	}

	mmCreate.defaultExpectation.params = &RoomRepositoryMockCreateParams{ctx, room}
	mmCreate.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreate.expectations {
		if minimock.Equal(e.params, mmCreate.defaultExpectation.params) {
			mmCreate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreate.defaultExpectation.params)
		}
	}

	return mmCreate
}

// ExpectCtxParam1 sets up expected param ctx for RoomRepository.Create
func (mmCreate *mRoomRepositoryMockCreate) ExpectCtxParam1(ctx context.Context) *mRoomRepositoryMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("RoomRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &RoomRepositoryMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("RoomRepositoryMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &RoomRepositoryMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreate.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreate
}

// ExpectRoomParam2 sets up expected param room for RoomRepository.Create
func (mmCreate *mRoomRepositoryMockCreate) ExpectRoomParam2(room domain.Room) *mRoomRepositoryMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("RoomRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &RoomRepositoryMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("RoomRepositoryMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &RoomRepositoryMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.room = &room
	mmCreate.defaultExpectation.expectationOrigins.originRoom = minimock.CallerInfo(1)

	return mmCreate
}

// Inspect accepts an inspector function that has same arguments as the RoomRepository.Create
func (mmCreate *mRoomRepositoryMockCreate) Inspect(f func(ctx context.Context, room domain.Room)) *mRoomRepositoryMockCreate {
	if mmCreate.mock.inspectFuncCreate != nil {
		mmCreate.mock.t.Fatalf("Inspect function is already set for RoomRepositoryMock.Create")
	}

	mmCreate.mock.inspectFuncCreate = f

	return mmCreate
}

// Return sets up results that will be returned by RoomRepository.Create
func (mmCreate *mRoomRepositoryMockCreate) Return(r1 domain.Room, err error) *RoomRepositoryMock {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("RoomRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &RoomRepositoryMockCreateExpectation{mock: mmCreate.mock}
	}
	mmCreate.defaultExpectation.results = &RoomRepositoryMockCreateResults{r1, err}
	mmCreate.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreate.mock
}

// Set uses given function f to mock the RoomRepository.Create method
func (mmCreate *mRoomRepositoryMockCreate) Set(f func(ctx context.Context, room domain.Room) (r1 domain.Room, err error)) *RoomRepositoryMock {
	if mmCreate.defaultExpectation != nil {
		mmCreate.mock.t.Fatalf("Default expectation is already set for the RoomRepository.Create method")
	}

	if len(mmCreate.expectations) > 0 {
		mmCreate.mock.t.Fatalf("Some expectations are already set for the RoomRepository.Create method")
	}

	mmCreate.mock.funcCreate = f
	mmCreate.mock.funcCreateOrigin = minimock.CallerInfo(1)
	return mmCreate.mock
}

// When sets expectation for the RoomRepository.Create which will trigger the result defined by the following
// Then helper
func (mmCreate *mRoomRepositoryMockCreate) When(ctx context.Context, room domain.Room) *RoomRepositoryMockCreateExpectation {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("RoomRepositoryMock.Create mock is already set by Set")
	}

	expectation := &RoomRepositoryMockCreateExpectation{
		mock:               mmCreate.mock,
		params:             &RoomRepositoryMockCreateParams{ctx, room},
		expectationOrigins: RoomRepositoryMockCreateExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreate.expectations = append(mmCreate.expectations, expectation)
	return expectation
}

// Then sets up RoomRepository.Create return parameters for the expectation previously defined by the When method
func (e *RoomRepositoryMockCreateExpectation) Then(r1 domain.Room, err error) *RoomRepositoryMock {
	e.results = &RoomRepositoryMockCreateResults{r1, err}
	return e.mock
}

// Times sets number of times RoomRepository.Create should be invoked
func (mmCreate *mRoomRepositoryMockCreate) Times(n uint64) *mRoomRepositoryMockCreate {
	if n == 0 {
		mmCreate.mock.t.Fatalf("Times of RoomRepositoryMock.Create mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreate.expectedInvocations, n)
	mmCreate.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreate
}

func (mmCreate *mRoomRepositoryMockCreate) invocationsDone() bool {
	if len(mmCreate.expectations) == 0 && mmCreate.defaultExpectation == nil && mmCreate.mock.funcCreate == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreate.mock.afterCreateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreate.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Create implements mm_repository.RoomRepository
func (mmCreate *RoomRepositoryMock) Create(ctx context.Context, room domain.Room) (r1 domain.Room, err error) {
	mm_atomic.AddUint64(&mmCreate.beforeCreateCounter, 1)
	defer mm_atomic.AddUint64(&mmCreate.afterCreateCounter, 1)

	mmCreate.t.Helper()

	if mmCreate.inspectFuncCreate != nil {
		mmCreate.inspectFuncCreate(ctx, room)
	}

	mm_params := RoomRepositoryMockCreateParams{ctx, room}

	// Record call args
	mmCreate.CreateMock.mutex.Lock()
	mmCreate.CreateMock.callArgs = append(mmCreate.CreateMock.callArgs, &mm_params)
	mmCreate.CreateMock.mutex.Unlock()

	for _, e := range mmCreate.CreateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.r1, e.results.err
		}
	}

	if mmCreate.CreateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreate.CreateMock.defaultExpectation.Counter, 1)
		mm_want := mmCreate.CreateMock.defaultExpectation.params
		mm_want_ptrs := mmCreate.CreateMock.defaultExpectation.paramPtrs

		mm_got := RoomRepositoryMockCreateParams{ctx, room}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreate.t.Errorf("RoomRepositoryMock.Create got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.room != nil && !minimock.Equal(*mm_want_ptrs.room, mm_got.room) {
				mmCreate.t.Errorf("RoomRepositoryMock.Create got unexpected parameter room, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originRoom, *mm_want_ptrs.room, mm_got.room, minimock.Diff(*mm_want_ptrs.room, mm_got.room))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreate.t.Errorf("RoomRepositoryMock.Create got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreate.CreateMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreate.CreateMock.defaultExpectation.results
		if mm_results == nil {
			mmCreate.t.Fatal("No results are set for the RoomRepositoryMock.Create")
		}
		return (*mm_results).r1, (*mm_results).err
	}
	if mmCreate.funcCreate != nil {
		return mmCreate.funcCreate(ctx, room)
	}
	mmCreate.t.Fatalf("Unexpected call to RoomRepositoryMock.Create. %v %v", ctx, room)
	return
}

// CreateAfterCounter returns a count of finished RoomRepositoryMock.Create invocations
func (mmCreate *RoomRepositoryMock) CreateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.afterCreateCounter)
}

// CreateBeforeCounter returns a count of RoomRepositoryMock.Create invocations
func (mmCreate *RoomRepositoryMock) CreateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.beforeCreateCounter)
}

// Calls returns a list of arguments used in each call to RoomRepositoryMock.Create.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreate *mRoomRepositoryMockCreate) Calls() []*RoomRepositoryMockCreateParams {
	mmCreate.mutex.RLock()

	argCopy := make([]*RoomRepositoryMockCreateParams, len(mmCreate.callArgs))
	copy(argCopy, mmCreate.callArgs)

	mmCreate.mutex.RUnlock()

	return argCopy
}

// MinimockCreateDone returns true if the count of the Create invocations corresponds
// the number of defined expectations
func (m *RoomRepositoryMock) MinimockCreateDone() bool {
	if m.CreateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateMock.invocationsDone()
}

// MinimockCreateInspect logs each unmet expectation
func (m *RoomRepositoryMock) MinimockCreateInspect() {
	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RoomRepositoryMock.Create at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateCounter := mm_atomic.LoadUint64(&m.afterCreateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateMock.defaultExpectation != nil && afterCreateCounter < 1 {
		if m.CreateMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to RoomRepositoryMock.Create at\n%s", m.CreateMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to RoomRepositoryMock.Create at\n%s with params: %#v", m.CreateMock.defaultExpectation.expectationOrigins.origin, *m.CreateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreate != nil && afterCreateCounter < 1 {
		m.t.Errorf("Expected call to RoomRepositoryMock.Create at\n%s", m.funcCreateOrigin)
	}

	if !m.CreateMock.invocationsDone() && afterCreateCounter > 0 {
		m.t.Errorf("Expected %d calls to RoomRepositoryMock.Create at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateMock.expectedInvocations), m.CreateMock.expectedInvocationsOrigin, afterCreateCounter)
	}
}

type mRoomRepositoryMockGetByID struct {
	optional           bool
	mock               *RoomRepositoryMock
	defaultExpectation *RoomRepositoryMockGetByIDExpectation
	expectations       []*RoomRepositoryMockGetByIDExpectation

	callArgs []*RoomRepositoryMockGetByIDParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// RoomRepositoryMockGetByIDExpectation specifies expectation struct of the RoomRepository.GetByID
type RoomRepositoryMockGetByIDExpectation struct {
	mock               *RoomRepositoryMock
	params             *RoomRepositoryMockGetByIDParams
	paramPtrs          *RoomRepositoryMockGetByIDParamPtrs
	expectationOrigins RoomRepositoryMockGetByIDExpectationOrigins
	results            *RoomRepositoryMockGetByIDResults
	returnOrigin       string
	Counter            uint64
}

// RoomRepositoryMockGetByIDParams contains parameters of the RoomRepository.GetByID
type RoomRepositoryMockGetByIDParams struct {
	ctx    context.Context
	roomID string
}

// RoomRepositoryMockGetByIDParamPtrs contains pointers to parameters of the RoomRepository.GetByID
type RoomRepositoryMockGetByIDParamPtrs struct {
	ctx    *context.Context
	roomID *string
}

// RoomRepositoryMockGetByIDResults contains results of the RoomRepository.GetByID
type RoomRepositoryMockGetByIDResults struct {
	r1  domain.Room
	err error
}

// RoomRepositoryMockGetByIDOrigins contains origins of expectations of the RoomRepository.GetByID
type RoomRepositoryMockGetByIDExpectationOrigins struct {
	origin       string
	originCtx    string
	originRoomID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetByID *mRoomRepositoryMockGetByID) Optional() *mRoomRepositoryMockGetByID {
	mmGetByID.optional = true
	return mmGetByID
}

// Expect sets up expected params for RoomRepository.GetByID
func (mmGetByID *mRoomRepositoryMockGetByID) Expect(ctx context.Context, roomID string) *mRoomRepositoryMockGetByID {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("RoomRepositoryMock.GetByID mock is already set by Set")
	}

	if mmGetByID.defaultExpectation == nil {
		mmGetByID.defaultExpectation = &RoomRepositoryMockGetByIDExpectation{}
	}

	if mmGetByID.defaultExpectation.paramPtrs != nil {
		mmGetByID.mock.t.Fatalf("RoomRepositoryMock.GetByID mock is already set by ExpectParams functions")
	}

	mmGetByID.defaultExpectation.params = &RoomRepositoryMockGetByIDParams{ctx, roomID}
	mmGetByID.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetByID.expectations {
		if minimock.Equal(e.params, mmGetByID.defaultExpectation.params) {
			mmGetByID.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetByID.defaultExpectation.params)
		}
	}

	return mmGetByID
}

// ExpectCtxParam1 sets up expected param ctx for RoomRepository.GetByID
func (mmGetByID *mRoomRepositoryMockGetByID) ExpectCtxParam1(ctx context.Context) *mRoomRepositoryMockGetByID {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("RoomRepositoryMock.GetByID mock is already set by Set")
	}

	if mmGetByID.defaultExpectation == nil {
		mmGetByID.defaultExpectation = &RoomRepositoryMockGetByIDExpectation{}
	}

	if mmGetByID.defaultExpectation.params != nil {
		mmGetByID.mock.t.Fatalf("RoomRepositoryMock.GetByID mock is already set by Expect")
	}

	if mmGetByID.defaultExpectation.paramPtrs == nil {
		mmGetByID.defaultExpectation.paramPtrs = &RoomRepositoryMockGetByIDParamPtrs{}
	}
	mmGetByID.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetByID.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetByID
}

// ExpectRoomIDParam2 sets up expected param roomID for RoomRepository.GetByID
func (mmGetByID *mRoomRepositoryMockGetByID) ExpectRoomIDParam2(roomID string) *mRoomRepositoryMockGetByID {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("RoomRepositoryMock.GetByID mock is already set by Set")
	}

	if mmGetByID.defaultExpectation == nil {
		mmGetByID.defaultExpectation = &RoomRepositoryMockGetByIDExpectation{}
	}

	if mmGetByID.defaultExpectation.params != nil {
		mmGetByID.mock.t.Fatalf("RoomRepositoryMock.GetByID mock is already set by Expect")
	}

	if mmGetByID.defaultExpectation.paramPtrs == nil {
		mmGetByID.defaultExpectation.paramPtrs = &RoomRepositoryMockGetByIDParamPtrs{}
	}
	mmGetByID.defaultExpectation.paramPtrs.roomID = &roomID
	mmGetByID.defaultExpectation.expectationOrigins.originRoomID = minimock.CallerInfo(1)

	return mmGetByID
}

// Inspect accepts an inspector function that has same arguments as the RoomRepository.GetByID
func (mmGetByID *mRoomRepositoryMockGetByID) Inspect(f func(ctx context.Context, roomID string)) *mRoomRepositoryMockGetByID {
	if mmGetByID.mock.inspectFuncGetByID != nil {
		mmGetByID.mock.t.Fatalf("Inspect function is already set for RoomRepositoryMock.GetByID")
	}

	mmGetByID.mock.inspectFuncGetByID = f

	return mmGetByID
}

// Return sets up results that will be returned by RoomRepository.GetByID
func (mmGetByID *mRoomRepositoryMockGetByID) Return(r1 domain.Room, err error) *RoomRepositoryMock {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("RoomRepositoryMock.GetByID mock is already set by Set")
	}

	if mmGetByID.defaultExpectation == nil {
		mmGetByID.defaultExpectation = &RoomRepositoryMockGetByIDExpectation{mock: mmGetByID.mock}
	}
	mmGetByID.defaultExpectation.results = &RoomRepositoryMockGetByIDResults{r1, err}
	mmGetByID.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetByID.mock
}

// Set uses given function f to mock the RoomRepository.GetByID method
func (mmGetByID *mRoomRepositoryMockGetByID) Set(f func(ctx context.Context, roomID string) (r1 domain.Room, err error)) *RoomRepositoryMock {
	if mmGetByID.defaultExpectation != nil {
		mmGetByID.mock.t.Fatalf("Default expectation is already set for the RoomRepository.GetByID method")
	}

	if len(mmGetByID.expectations) > 0 {
		mmGetByID.mock.t.Fatalf("Some expectations are already set for the RoomRepository.GetByID method")
	}

	mmGetByID.mock.funcGetByID = f
	mmGetByID.mock.funcGetByIDOrigin = minimock.CallerInfo(1)
	return mmGetByID.mock
}

// When sets expectation for the RoomRepository.GetByID which will trigger the result defined by the following
// Then helper
func (mmGetByID *mRoomRepositoryMockGetByID) When(ctx context.Context, roomID string) *RoomRepositoryMockGetByIDExpectation {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("RoomRepositoryMock.GetByID mock is already set by Set")
	}

	expectation := &RoomRepositoryMockGetByIDExpectation{
		mock:               mmGetByID.mock,
		params:             &RoomRepositoryMockGetByIDParams{ctx, roomID},
		expectationOrigins: RoomRepositoryMockGetByIDExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetByID.expectations = append(mmGetByID.expectations, expectation)
	return expectation
}

// Then sets up RoomRepository.GetByID return parameters for the expectation previously defined by the When method
func (e *RoomRepositoryMockGetByIDExpectation) Then(r1 domain.Room, err error) *RoomRepositoryMock {
	e.results = &RoomRepositoryMockGetByIDResults{r1, err}
	return e.mock
}

// Times sets number of times RoomRepository.GetByID should be invoked
func (mmGetByID *mRoomRepositoryMockGetByID) Times(n uint64) *mRoomRepositoryMockGetByID {
	if n == 0 {
		mmGetByID.mock.t.Fatalf("Times of RoomRepositoryMock.GetByID mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetByID.expectedInvocations, n)
	mmGetByID.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetByID
}

func (mmGetByID *mRoomRepositoryMockGetByID) invocationsDone() bool {
	if len(mmGetByID.expectations) == 0 && mmGetByID.defaultExpectation == nil && mmGetByID.mock.funcGetByID == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetByID.mock.afterGetByIDCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetByID.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetByID implements mm_repository.RoomRepository
func (mmGetByID *RoomRepositoryMock) GetByID(ctx context.Context, roomID string) (r1 domain.Room, err error) {
	mm_atomic.AddUint64(&mmGetByID.beforeGetByIDCounter, 1)
	defer mm_atomic.AddUint64(&mmGetByID.afterGetByIDCounter, 1)

	mmGetByID.t.Helper()

	if mmGetByID.inspectFuncGetByID != nil {
		mmGetByID.inspectFuncGetByID(ctx, roomID)
	}

	mm_params := RoomRepositoryMockGetByIDParams{ctx, roomID}

	// Record call args
	mmGetByID.GetByIDMock.mutex.Lock()
	mmGetByID.GetByIDMock.callArgs = append(mmGetByID.GetByIDMock.callArgs, &mm_params)
	mmGetByID.GetByIDMock.mutex.Unlock()

	for _, e := range mmGetByID.GetByIDMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.r1, e.results.err
		}
	}

	if mmGetByID.GetByIDMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetByID.GetByIDMock.defaultExpectation.Counter, 1)
		mm_want := mmGetByID.GetByIDMock.defaultExpectation.params
		mm_want_ptrs := mmGetByID.GetByIDMock.defaultExpectation.paramPtrs

		mm_got := RoomRepositoryMockGetByIDParams{ctx, roomID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetByID.t.Errorf("RoomRepositoryMock.GetByID got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByID.GetByIDMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.roomID != nil && !minimock.Equal(*mm_want_ptrs.roomID, mm_got.roomID) {
				mmGetByID.t.Errorf("RoomRepositoryMock.GetByID got unexpected parameter roomID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByID.GetByIDMock.defaultExpectation.expectationOrigins.originRoomID, *mm_want_ptrs.roomID, mm_got.roomID, minimock.Diff(*mm_want_ptrs.roomID, mm_got.roomID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetByID.t.Errorf("RoomRepositoryMock.GetByID got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetByID.GetByIDMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetByID.GetByIDMock.defaultExpectation.results
		if mm_results == nil {
			mmGetByID.t.Fatal("No results are set for the RoomRepositoryMock.GetByID")
		}
		return (*mm_results).r1, (*mm_results).err
	}
	if mmGetByID.funcGetByID != nil {
		return mmGetByID.funcGetByID(ctx, roomID)
	}
	mmGetByID.t.Fatalf("Unexpected call to RoomRepositoryMock.GetByID. %v %v", ctx, roomID)
	return
}

// GetByIDAfterCounter returns a count of finished RoomRepositoryMock.GetByID invocations
func (mmGetByID *RoomRepositoryMock) GetByIDAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByID.afterGetByIDCounter)
}

// GetByIDBeforeCounter returns a count of RoomRepositoryMock.GetByID invocations
func (mmGetByID *RoomRepositoryMock) GetByIDBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByID.beforeGetByIDCounter)
}

// Calls returns a list of arguments used in each call to RoomRepositoryMock.GetByID.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetByID *mRoomRepositoryMockGetByID) Calls() []*RoomRepositoryMockGetByIDParams {
	mmGetByID.mutex.RLock()

	argCopy := make([]*RoomRepositoryMockGetByIDParams, len(mmGetByID.callArgs))
	copy(argCopy, mmGetByID.callArgs)

	mmGetByID.mutex.RUnlock()

	return argCopy
}

// MinimockGetByIDDone returns true if the count of the GetByID invocations corresponds
// the number of defined expectations
func (m *RoomRepositoryMock) MinimockGetByIDDone() bool {
	if m.GetByIDMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetByIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetByIDMock.invocationsDone()
}

// MinimockGetByIDInspect logs each unmet expectation
func (m *RoomRepositoryMock) MinimockGetByIDInspect() {
	for _, e := range m.GetByIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RoomRepositoryMock.GetByID at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetByIDCounter := mm_atomic.LoadUint64(&m.afterGetByIDCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetByIDMock.defaultExpectation != nil && afterGetByIDCounter < 1 {
		if m.GetByIDMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to RoomRepositoryMock.GetByID at\n%s", m.GetByIDMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to RoomRepositoryMock.GetByID at\n%s with params: %#v", m.GetByIDMock.defaultExpectation.expectationOrigins.origin, *m.GetByIDMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetByID != nil && afterGetByIDCounter < 1 {
		m.t.Errorf("Expected call to RoomRepositoryMock.GetByID at\n%s", m.funcGetByIDOrigin)
	}

	if !m.GetByIDMock.invocationsDone() && afterGetByIDCounter > 0 {
		m.t.Errorf("Expected %d calls to RoomRepositoryMock.GetByID at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetByIDMock.expectedInvocations), m.GetByIDMock.expectedInvocationsOrigin, afterGetByIDCounter)
	}
}

type mRoomRepositoryMockList struct {
	optional           bool
	mock               *RoomRepositoryMock
	defaultExpectation *RoomRepositoryMockListExpectation
	expectations       []*RoomRepositoryMockListExpectation

	callArgs []*RoomRepositoryMockListParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// RoomRepositoryMockListExpectation specifies expectation struct of the RoomRepository.List
type RoomRepositoryMockListExpectation struct {
	mock               *RoomRepositoryMock
	params             *RoomRepositoryMockListParams
	paramPtrs          *RoomRepositoryMockListParamPtrs
	expectationOrigins RoomRepositoryMockListExpectationOrigins
	results            *RoomRepositoryMockListResults
	returnOrigin       string
	Counter            uint64
}

// RoomRepositoryMockListParams contains parameters of the RoomRepository.List
type RoomRepositoryMockListParams struct {
	ctx context.Context
}

// RoomRepositoryMockListParamPtrs contains pointers to parameters of the RoomRepository.List
type RoomRepositoryMockListParamPtrs struct {
	ctx *context.Context
}

// RoomRepositoryMockListResults contains results of the RoomRepository.List
type RoomRepositoryMockListResults struct {
	ra1 []domain.Room
	err error
}

// RoomRepositoryMockListOrigins contains origins of expectations of the RoomRepository.List
type RoomRepositoryMockListExpectationOrigins struct {
	origin    string
	originCtx string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmList *mRoomRepositoryMockList) Optional() *mRoomRepositoryMockList {
	mmList.optional = true
	return mmList
}

// Expect sets up expected params for RoomRepository.List
func (mmList *mRoomRepositoryMockList) Expect(ctx context.Context) *mRoomRepositoryMockList {
	if mmList.mock.funcList != nil {
		mmList.mock.t.Fatalf("RoomRepositoryMock.List mock is already set by Set")
	}

	if mmList.defaultExpectation == nil {
		mmList.defaultExpectation = &RoomRepositoryMockListExpectation{}
	}

	if mmList.defaultExpectation.paramPtrs != nil {
		mmList.mock.t.Fatalf("RoomRepositoryMock.List mock is already set by ExpectParams functions")
	}

	mmList.defaultExpectation.params = &RoomRepositoryMockListParams{ctx}
	mmList.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmList.expectations {
		if minimock.Equal(e.params, mmList.defaultExpectation.params) {
			mmList.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmList.defaultExpectation.params)
		}
	}

	return mmList
}

// ExpectCtxParam1 sets up expected param ctx for RoomRepository.List
func (mmList *mRoomRepositoryMockList) ExpectCtxParam1(ctx context.Context) *mRoomRepositoryMockList {
	if mmList.mock.funcList != nil {
		mmList.mock.t.Fatalf("RoomRepositoryMock.List mock is already set by Set")
	}

	if mmList.defaultExpectation == nil {
		mmList.defaultExpectation = &RoomRepositoryMockListExpectation{}
	}

	if mmList.defaultExpectation.params != nil {
		mmList.mock.t.Fatalf("RoomRepositoryMock.List mock is already set by Expect")
	}

	if mmList.defaultExpectation.paramPtrs == nil {
		mmList.defaultExpectation.paramPtrs = &RoomRepositoryMockListParamPtrs{}
	}
	mmList.defaultExpectation.paramPtrs.ctx = &ctx
	mmList.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmList
}

// Inspect accepts an inspector function that has same arguments as the RoomRepository.List
func (mmList *mRoomRepositoryMockList) Inspect(f func(ctx context.Context)) *mRoomRepositoryMockList {
	if mmList.mock.inspectFuncList != nil {
		mmList.mock.t.Fatalf("Inspect function is already set for RoomRepositoryMock.List")
	}

	mmList.mock.inspectFuncList = f

	return mmList
}

// Return sets up results that will be returned by RoomRepository.List
func (mmList *mRoomRepositoryMockList) Return(ra1 []domain.Room, err error) *RoomRepositoryMock {
	if mmList.mock.funcList != nil {
		mmList.mock.t.Fatalf("RoomRepositoryMock.List mock is already set by Set")
	}

	if mmList.defaultExpectation == nil {
		mmList.defaultExpectation = &RoomRepositoryMockListExpectation{mock: mmList.mock}
	}
	mmList.defaultExpectation.results = &RoomRepositoryMockListResults{ra1, err}
	mmList.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmList.mock
}

// Set uses given function f to mock the RoomRepository.List method
func (mmList *mRoomRepositoryMockList) Set(f func(ctx context.Context) (ra1 []domain.Room, err error)) *RoomRepositoryMock {
	if mmList.defaultExpectation != nil {
		mmList.mock.t.Fatalf("Default expectation is already set for the RoomRepository.List method")
	}

	if len(mmList.expectations) > 0 {
		mmList.mock.t.Fatalf("Some expectations are already set for the RoomRepository.List method")
	}

	mmList.mock.funcList = f
	mmList.mock.funcListOrigin = minimock.CallerInfo(1)
	return mmList.mock
}

// When sets expectation for the RoomRepository.List which will trigger the result defined by the following
// Then helper
func (mmList *mRoomRepositoryMockList) When(ctx context.Context) *RoomRepositoryMockListExpectation {
	if mmList.mock.funcList != nil {
		mmList.mock.t.Fatalf("RoomRepositoryMock.List mock is already set by Set")
	}

	expectation := &RoomRepositoryMockListExpectation{
		mock:               mmList.mock,
		params:             &RoomRepositoryMockListParams{ctx},
		expectationOrigins: RoomRepositoryMockListExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmList.expectations = append(mmList.expectations, expectation)
	return expectation
}

// Then sets up RoomRepository.List return parameters for the expectation previously defined by the When method
func (e *RoomRepositoryMockListExpectation) Then(ra1 []domain.Room, err error) *RoomRepositoryMock {
	e.results = &RoomRepositoryMockListResults{ra1, err}
	return e.mock
}

// Times sets number of times RoomRepository.List should be invoked
func (mmList *mRoomRepositoryMockList) Times(n uint64) *mRoomRepositoryMockList {
	if n == 0 {
		mmList.mock.t.Fatalf("Times of RoomRepositoryMock.List mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmList.expectedInvocations, n)
	mmList.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmList
}

func (mmList *mRoomRepositoryMockList) invocationsDone() bool {
	if len(mmList.expectations) == 0 && mmList.defaultExpectation == nil && mmList.mock.funcList == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmList.mock.afterListCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmList.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// List implements mm_repository.RoomRepository
func (mmList *RoomRepositoryMock) List(ctx context.Context) (ra1 []domain.Room, err error) {
	mm_atomic.AddUint64(&mmList.beforeListCounter, 1)
	defer mm_atomic.AddUint64(&mmList.afterListCounter, 1)

	mmList.t.Helper()

	if mmList.inspectFuncList != nil {
		mmList.inspectFuncList(ctx)
	}

	mm_params := RoomRepositoryMockListParams{ctx}

	// Record call args
	mmList.ListMock.mutex.Lock()
	mmList.ListMock.callArgs = append(mmList.ListMock.callArgs, &mm_params)
	mmList.ListMock.mutex.Unlock()

	for _, e := range mmList.ListMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ra1, e.results.err
		}
	}

	if mmList.ListMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmList.ListMock.defaultExpectation.Counter, 1)
		mm_want := mmList.ListMock.defaultExpectation.params
		mm_want_ptrs := mmList.ListMock.defaultExpectation.paramPtrs

		mm_got := RoomRepositoryMockListParams{ctx}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmList.t.Errorf("RoomRepositoryMock.List got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmList.ListMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmList.t.Errorf("RoomRepositoryMock.List got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmList.ListMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmList.ListMock.defaultExpectation.results
		if mm_results == nil {
			mmList.t.Fatal("No results are set for the RoomRepositoryMock.List")
		}
		return (*mm_results).ra1, (*mm_results).err
	}
	if mmList.funcList != nil {
		return mmList.funcList(ctx)
	}
	mmList.t.Fatalf("Unexpected call to RoomRepositoryMock.List. %v", ctx)
	return
}

// ListAfterCounter returns a count of finished RoomRepositoryMock.List invocations
func (mmList *RoomRepositoryMock) ListAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmList.afterListCounter)
}

// ListBeforeCounter returns a count of RoomRepositoryMock.List invocations
func (mmList *RoomRepositoryMock) ListBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmList.beforeListCounter)
}

// Calls returns a list of arguments used in each call to RoomRepositoryMock.List.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmList *mRoomRepositoryMockList) Calls() []*RoomRepositoryMockListParams {
	mmList.mutex.RLock()

	argCopy := make([]*RoomRepositoryMockListParams, len(mmList.callArgs))
	copy(argCopy, mmList.callArgs)

	mmList.mutex.RUnlock()

	return argCopy
}

// MinimockListDone returns true if the count of the List invocations corresponds
// the number of defined expectations
func (m *RoomRepositoryMock) MinimockListDone() bool {
	if m.ListMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ListMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ListMock.invocationsDone()
}

// MinimockListInspect logs each unmet expectation
func (m *RoomRepositoryMock) MinimockListInspect() {
	for _, e := range m.ListMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RoomRepositoryMock.List at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterListCounter := mm_atomic.LoadUint64(&m.afterListCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ListMock.defaultExpectation != nil && afterListCounter < 1 {
		if m.ListMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to RoomRepositoryMock.List at\n%s", m.ListMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to RoomRepositoryMock.List at\n%s with params: %#v", m.ListMock.defaultExpectation.expectationOrigins.origin, *m.ListMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcList != nil && afterListCounter < 1 {
		m.t.Errorf("Expected call to RoomRepositoryMock.List at\n%s", m.funcListOrigin)
	}

	if !m.ListMock.invocationsDone() && afterListCounter > 0 {
		m.t.Errorf("Expected %d calls to RoomRepositoryMock.List at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ListMock.expectedInvocations), m.ListMock.expectedInvocationsOrigin, afterListCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *RoomRepositoryMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateInspect()

			m.MinimockGetByIDInspect()

			m.MinimockListInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *RoomRepositoryMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *RoomRepositoryMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateDone() &&
		m.MinimockGetByIDDone() &&
		m.MinimockListDone()
}
