// Code generated by http://github.com/gojuno/minimock (v3.4.5). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/M1steryO/Room-Booking-Service/internal/repository.ScheduleRepository -o schedule_repository_minimock.go -n ScheduleRepositoryMock -p mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/M1steryO/Room-Booking-Service/internal/domain"
	"github.com/gojuno/minimock/v3"
)

// ScheduleRepositoryMock implements mm_repository.ScheduleRepository
type ScheduleRepositoryMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreateWithSlots          func(ctx context.Context, schedule domain.Schedule, slots []domain.Slot) (s1 domain.Schedule, err error)
	funcCreateWithSlotsOrigin    string
	inspectFuncCreateWithSlots   func(ctx context.Context, schedule domain.Schedule, slots []domain.Slot)
	afterCreateWithSlotsCounter  uint64
	beforeCreateWithSlotsCounter uint64
	CreateWithSlotsMock          mScheduleRepositoryMockCreateWithSlots

	funcGetByRoomID          func(ctx context.Context, roomID string) (s1 domain.Schedule, err error)
	funcGetByRoomIDOrigin    string
	inspectFuncGetByRoomID   func(ctx context.Context, roomID string)
	afterGetByRoomIDCounter  uint64
	beforeGetByRoomIDCounter uint64
	GetByRoomIDMock          mScheduleRepositoryMockGetByRoomID
}

// NewScheduleRepositoryMock returns a mock for mm_repository.ScheduleRepository
func NewScheduleRepositoryMock(t minimock.Tester) *ScheduleRepositoryMock {
	m := &ScheduleRepositoryMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateWithSlotsMock = mScheduleRepositoryMockCreateWithSlots{mock: m}
	m.CreateWithSlotsMock.callArgs = []*ScheduleRepositoryMockCreateWithSlotsParams{}

	m.GetByRoomIDMock = mScheduleRepositoryMockGetByRoomID{mock: m}
	m.GetByRoomIDMock.callArgs = []*ScheduleRepositoryMockGetByRoomIDParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mScheduleRepositoryMockCreateWithSlots struct {
	optional           bool
	mock               *ScheduleRepositoryMock
	defaultExpectation *ScheduleRepositoryMockCreateWithSlotsExpectation
	expectations       []*ScheduleRepositoryMockCreateWithSlotsExpectation

	callArgs []*ScheduleRepositoryMockCreateWithSlotsParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ScheduleRepositoryMockCreateWithSlotsExpectation specifies expectation struct of the ScheduleRepository.CreateWithSlots
type ScheduleRepositoryMockCreateWithSlotsExpectation struct {
	mock               *ScheduleRepositoryMock
	params             *ScheduleRepositoryMockCreateWithSlotsParams
	paramPtrs          *ScheduleRepositoryMockCreateWithSlotsParamPtrs
	expectationOrigins ScheduleRepositoryMockCreateWithSlotsExpectationOrigins
	results            *ScheduleRepositoryMockCreateWithSlotsResults
	returnOrigin       string
	Counter            uint64
}

// ScheduleRepositoryMockCreateWithSlotsParams contains parameters of the ScheduleRepository.CreateWithSlots
type ScheduleRepositoryMockCreateWithSlotsParams struct {
	ctx      context.Context
	schedule domain.Schedule
	slots    []domain.Slot
}

// ScheduleRepositoryMockCreateWithSlotsParamPtrs contains pointers to parameters of the ScheduleRepository.CreateWithSlots
type ScheduleRepositoryMockCreateWithSlotsParamPtrs struct {
	ctx      *context.Context
	schedule *domain.Schedule
	slots    *[]domain.Slot
}

// ScheduleRepositoryMockCreateWithSlotsResults contains results of the ScheduleRepository.CreateWithSlots
type ScheduleRepositoryMockCreateWithSlotsResults struct {
	s1  domain.Schedule
	err error
}

// ScheduleRepositoryMockCreateWithSlotsOrigins contains origins of expectations of the ScheduleRepository.CreateWithSlots
type ScheduleRepositoryMockCreateWithSlotsExpectationOrigins struct {
	origin         string
	originCtx      string
	originSchedule string
	originSlots    string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreateWithSlots *mScheduleRepositoryMockCreateWithSlots) Optional() *mScheduleRepositoryMockCreateWithSlots {
	mmCreateWithSlots.optional = true
	return mmCreateWithSlots
}

// Expect sets up expected params for ScheduleRepository.CreateWithSlots
func (mmCreateWithSlots *mScheduleRepositoryMockCreateWithSlots) Expect(ctx context.Context, schedule domain.Schedule, slots []domain.Slot) *mScheduleRepositoryMockCreateWithSlots {
	if mmCreateWithSlots.mock.funcCreateWithSlots != nil {
		mmCreateWithSlots.mock.t.Fatalf("ScheduleRepositoryMock.CreateWithSlots mock is already set by Set")
	}

	if mmCreateWithSlots.defaultExpectation == nil {
		mmCreateWithSlots.defaultExpectation = &ScheduleRepositoryMockCreateWithSlotsExpectation{}
	}

	if mmCreateWithSlots.defaultExpectation.paramPtrs != nil {
		mmCreateWithSlots.mock.t.Fatalf("ScheduleRepositoryMock.CreateWithSlots mock is already set by ExpectParams functions")
	}

	mmCreateWithSlots.defaultExpectation.params = &ScheduleRepositoryMockCreateWithSlotsParams{ctx, schedule, slots}
	mmCreateWithSlots.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreateWithSlots.expectations {
		if minimock.Equal(e.params, mmCreateWithSlots.defaultExpectation.params) {
			mmCreateWithSlots.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreateWithSlots.defaultExpectation.params)
		}
	}

	return mmCreateWithSlots
}

// ExpectCtxParam1 sets up expected param ctx for ScheduleRepository.CreateWithSlots
func (mmCreateWithSlots *mScheduleRepositoryMockCreateWithSlots) ExpectCtxParam1(ctx context.Context) *mScheduleRepositoryMockCreateWithSlots {
	if mmCreateWithSlots.mock.funcCreateWithSlots != nil {
		mmCreateWithSlots.mock.t.Fatalf("ScheduleRepositoryMock.CreateWithSlots mock is already set by Set")
	}

	if mmCreateWithSlots.defaultExpectation == nil {
		mmCreateWithSlots.defaultExpectation = &ScheduleRepositoryMockCreateWithSlotsExpectation{}
	}

	if mmCreateWithSlots.defaultExpectation.params != nil {
		mmCreateWithSlots.mock.t.Fatalf("ScheduleRepositoryMock.CreateWithSlots mock is already set by Expect")
	}

	if mmCreateWithSlots.defaultExpectation.paramPtrs == nil {
		mmCreateWithSlots.defaultExpectation.paramPtrs = &ScheduleRepositoryMockCreateWithSlotsParamPtrs{}
	}
	mmCreateWithSlots.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreateWithSlots.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreateWithSlots
}

// ExpectScheduleParam2 sets up expected param schedule for ScheduleRepository.CreateWithSlots
func (mmCreateWithSlots *mScheduleRepositoryMockCreateWithSlots) ExpectScheduleParam2(schedule domain.Schedule) *mScheduleRepositoryMockCreateWithSlots {
	if mmCreateWithSlots.mock.funcCreateWithSlots != nil {
		mmCreateWithSlots.mock.t.Fatalf("ScheduleRepositoryMock.CreateWithSlots mock is already set by Set")
	}

	if mmCreateWithSlots.defaultExpectation == nil {
		mmCreateWithSlots.defaultExpectation = &ScheduleRepositoryMockCreateWithSlotsExpectation{}
	}

	if mmCreateWithSlots.defaultExpectation.params != nil {
		mmCreateWithSlots.mock.t.Fatalf("ScheduleRepositoryMock.CreateWithSlots mock is already set by Expect")
	}

	if mmCreateWithSlots.defaultExpectation.paramPtrs == nil {
		mmCreateWithSlots.defaultExpectation.paramPtrs = &ScheduleRepositoryMockCreateWithSlotsParamPtrs{}
	}
	mmCreateWithSlots.defaultExpectation.paramPtrs.schedule = &schedule
	mmCreateWithSlots.defaultExpectation.expectationOrigins.originSchedule = minimock.CallerInfo(1)

	return mmCreateWithSlots
}

// ExpectSlotsParam3 sets up expected param slots for ScheduleRepository.CreateWithSlots
func (mmCreateWithSlots *mScheduleRepositoryMockCreateWithSlots) ExpectSlotsParam3(slots []domain.Slot) *mScheduleRepositoryMockCreateWithSlots {
	if mmCreateWithSlots.mock.funcCreateWithSlots != nil {
		mmCreateWithSlots.mock.t.Fatalf("ScheduleRepositoryMock.CreateWithSlots mock is already set by Set")
	}

	if mmCreateWithSlots.defaultExpectation == nil {
		mmCreateWithSlots.defaultExpectation = &ScheduleRepositoryMockCreateWithSlotsExpectation{}
	}

	if mmCreateWithSlots.defaultExpectation.params != nil {
		mmCreateWithSlots.mock.t.Fatalf("ScheduleRepositoryMock.CreateWithSlots mock is already set by Expect")
	}

	if mmCreateWithSlots.defaultExpectation.paramPtrs == nil {
		mmCreateWithSlots.defaultExpectation.paramPtrs = &ScheduleRepositoryMockCreateWithSlotsParamPtrs{}
	}
	mmCreateWithSlots.defaultExpectation.paramPtrs.slots = &slots
	mmCreateWithSlots.defaultExpectation.expectationOrigins.originSlots = minimock.CallerInfo(1)

	return mmCreateWithSlots
}

// Inspect accepts an inspector function that has same arguments as the ScheduleRepository.CreateWithSlots
func (mmCreateWithSlots *mScheduleRepositoryMockCreateWithSlots) Inspect(f func(ctx context.Context, schedule domain.Schedule, slots []domain.Slot)) *mScheduleRepositoryMockCreateWithSlots {
	if mmCreateWithSlots.mock.inspectFuncCreateWithSlots != nil {
		mmCreateWithSlots.mock.t.Fatalf("Inspect function is already set for ScheduleRepositoryMock.CreateWithSlots")
	}

	mmCreateWithSlots.mock.inspectFuncCreateWithSlots = f

	return mmCreateWithSlots
}

// Return sets up results that will be returned by ScheduleRepository.CreateWithSlots
func (mmCreateWithSlots *mScheduleRepositoryMockCreateWithSlots) Return(s1 domain.Schedule, err error) *ScheduleRepositoryMock {
	if mmCreateWithSlots.mock.funcCreateWithSlots != nil {
		mmCreateWithSlots.mock.t.Fatalf("ScheduleRepositoryMock.CreateWithSlots mock is already set by Set")
	}

	if mmCreateWithSlots.defaultExpectation == nil {
		mmCreateWithSlots.defaultExpectation = &ScheduleRepositoryMockCreateWithSlotsExpectation{mock: mmCreateWithSlots.mock}
	}
	mmCreateWithSlots.defaultExpectation.results = &ScheduleRepositoryMockCreateWithSlotsResults{s1, err}
	mmCreateWithSlots.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreateWithSlots.mock
}

// Set uses given function f to mock the ScheduleRepository.CreateWithSlots method
func (mmCreateWithSlots *mScheduleRepositoryMockCreateWithSlots) Set(f func(ctx context.Context, schedule domain.Schedule, slots []domain.Slot) (s1 domain.Schedule, err error)) *ScheduleRepositoryMock {
	if mmCreateWithSlots.defaultExpectation != nil {
		mmCreateWithSlots.mock.t.Fatalf("Default expectation is already set for the ScheduleRepository.CreateWithSlots method")
	}

	if len(mmCreateWithSlots.expectations) > 0 {
		mmCreateWithSlots.mock.t.Fatalf("Some expectations are already set for the ScheduleRepository.CreateWithSlots method")
	}

	mmCreateWithSlots.mock.funcCreateWithSlots = f
	mmCreateWithSlots.mock.funcCreateWithSlotsOrigin = minimock.CallerInfo(1)
	return mmCreateWithSlots.mock
}

// When sets expectation for the ScheduleRepository.CreateWithSlots which will trigger the result defined by the following
// Then helper
func (mmCreateWithSlots *mScheduleRepositoryMockCreateWithSlots) When(ctx context.Context, schedule domain.Schedule, slots []domain.Slot) *ScheduleRepositoryMockCreateWithSlotsExpectation {
	if mmCreateWithSlots.mock.funcCreateWithSlots != nil {
		mmCreateWithSlots.mock.t.Fatalf("ScheduleRepositoryMock.CreateWithSlots mock is already set by Set")
	}

	expectation := &ScheduleRepositoryMockCreateWithSlotsExpectation{
		mock:               mmCreateWithSlots.mock,
		params:             &ScheduleRepositoryMockCreateWithSlotsParams{ctx, schedule, slots},
		expectationOrigins: ScheduleRepositoryMockCreateWithSlotsExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreateWithSlots.expectations = append(mmCreateWithSlots.expectations, expectation)
	return expectation
}

// Then sets up ScheduleRepository.CreateWithSlots return parameters for the expectation previously defined by the When method
func (e *ScheduleRepositoryMockCreateWithSlotsExpectation) Then(s1 domain.Schedule, err error) *ScheduleRepositoryMock {
	e.results = &ScheduleRepositoryMockCreateWithSlotsResults{s1, err}
	return e.mock
}

// Times sets number of times ScheduleRepository.CreateWithSlots should be invoked
func (mmCreateWithSlots *mScheduleRepositoryMockCreateWithSlots) Times(n uint64) *mScheduleRepositoryMockCreateWithSlots {
	if n == 0 {
		mmCreateWithSlots.mock.t.Fatalf("Times of ScheduleRepositoryMock.CreateWithSlots mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreateWithSlots.expectedInvocations, n)
	mmCreateWithSlots.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreateWithSlots
}

func (mmCreateWithSlots *mScheduleRepositoryMockCreateWithSlots) invocationsDone() bool {
	if len(mmCreateWithSlots.expectations) == 0 && mmCreateWithSlots.defaultExpectation == nil && mmCreateWithSlots.mock.funcCreateWithSlots == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreateWithSlots.mock.afterCreateWithSlotsCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreateWithSlots.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// CreateWithSlots implements mm_repository.ScheduleRepository
func (mmCreateWithSlots *ScheduleRepositoryMock) CreateWithSlots(ctx context.Context, schedule domain.Schedule, slots []domain.Slot) (s1 domain.Schedule, err error) {
	mm_atomic.AddUint64(&mmCreateWithSlots.beforeCreateWithSlotsCounter, 1)
	defer mm_atomic.AddUint64(&mmCreateWithSlots.afterCreateWithSlotsCounter, 1)

	mmCreateWithSlots.t.Helper()

	if mmCreateWithSlots.inspectFuncCreateWithSlots != nil {
		mmCreateWithSlots.inspectFuncCreateWithSlots(ctx, schedule, slots)
	}

	mm_params := ScheduleRepositoryMockCreateWithSlotsParams{ctx, schedule, slots}

	// Record call args
	mmCreateWithSlots.CreateWithSlotsMock.mutex.Lock()
	mmCreateWithSlots.CreateWithSlotsMock.callArgs = append(mmCreateWithSlots.CreateWithSlotsMock.callArgs, &mm_params)
	mmCreateWithSlots.CreateWithSlotsMock.mutex.Unlock()

	for _, e := range mmCreateWithSlots.CreateWithSlotsMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1, e.results.err
		}
	}

	if mmCreateWithSlots.CreateWithSlotsMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreateWithSlots.CreateWithSlotsMock.defaultExpectation.Counter, 1)
		mm_want := mmCreateWithSlots.CreateWithSlotsMock.defaultExpectation.params
		mm_want_ptrs := mmCreateWithSlots.CreateWithSlotsMock.defaultExpectation.paramPtrs

		mm_got := ScheduleRepositoryMockCreateWithSlotsParams{ctx, schedule, slots}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreateWithSlots.t.Errorf("ScheduleRepositoryMock.CreateWithSlots got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateWithSlots.CreateWithSlotsMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.schedule != nil && !minimock.Equal(*mm_want_ptrs.schedule, mm_got.schedule) {
				mmCreateWithSlots.t.Errorf("ScheduleRepositoryMock.CreateWithSlots got unexpected parameter schedule, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateWithSlots.CreateWithSlotsMock.defaultExpectation.expectationOrigins.originSchedule, *mm_want_ptrs.schedule, mm_got.schedule, minimock.Diff(*mm_want_ptrs.schedule, mm_got.schedule))
			}

			if mm_want_ptrs.slots != nil && !minimock.Equal(*mm_want_ptrs.slots, mm_got.slots) {
				mmCreateWithSlots.t.Errorf("ScheduleRepositoryMock.CreateWithSlots got unexpected parameter slots, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateWithSlots.CreateWithSlotsMock.defaultExpectation.expectationOrigins.originSlots, *mm_want_ptrs.slots, mm_got.slots, minimock.Diff(*mm_want_ptrs.slots, mm_got.slots))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreateWithSlots.t.Errorf("ScheduleRepositoryMock.CreateWithSlots got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreateWithSlots.CreateWithSlotsMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreateWithSlots.CreateWithSlotsMock.defaultExpectation.results
		if mm_results == nil {
			mmCreateWithSlots.t.Fatal("No results are set for the ScheduleRepositoryMock.CreateWithSlots")
		}
		return (*mm_results).s1, (*mm_results).err
	}
	if mmCreateWithSlots.funcCreateWithSlots != nil {
		return mmCreateWithSlots.funcCreateWithSlots(ctx, schedule, slots)
	}
	mmCreateWithSlots.t.Fatalf("Unexpected call to ScheduleRepositoryMock.CreateWithSlots. %v %v %v", ctx, schedule, slots)
	return
}

// CreateWithSlotsAfterCounter returns a count of finished ScheduleRepositoryMock.CreateWithSlots invocations
func (mmCreateWithSlots *ScheduleRepositoryMock) CreateWithSlotsAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateWithSlots.afterCreateWithSlotsCounter)
}

// CreateWithSlotsBeforeCounter returns a count of ScheduleRepositoryMock.CreateWithSlots invocations
func (mmCreateWithSlots *ScheduleRepositoryMock) CreateWithSlotsBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateWithSlots.beforeCreateWithSlotsCounter)
}

// Calls returns a list of arguments used in each call to ScheduleRepositoryMock.CreateWithSlots.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreateWithSlots *mScheduleRepositoryMockCreateWithSlots) Calls() []*ScheduleRepositoryMockCreateWithSlotsParams {
	mmCreateWithSlots.mutex.RLock()

	argCopy := make([]*ScheduleRepositoryMockCreateWithSlotsParams, len(mmCreateWithSlots.callArgs))
	copy(argCopy, mmCreateWithSlots.callArgs)

	mmCreateWithSlots.mutex.RUnlock()

	return argCopy
}

// MinimockCreateWithSlotsDone returns true if the count of the CreateWithSlots invocations corresponds
// the number of defined expectations
func (m *ScheduleRepositoryMock) MinimockCreateWithSlotsDone() bool {
	if m.CreateWithSlotsMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateWithSlotsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateWithSlotsMock.invocationsDone()
}

// MinimockCreateWithSlotsInspect logs each unmet expectation
func (m *ScheduleRepositoryMock) MinimockCreateWithSlotsInspect() {
	for _, e := range m.CreateWithSlotsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ScheduleRepositoryMock.CreateWithSlots at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateWithSlotsCounter := mm_atomic.LoadUint64(&m.afterCreateWithSlotsCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateWithSlotsMock.defaultExpectation != nil && afterCreateWithSlotsCounter < 1 {
		if m.CreateWithSlotsMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ScheduleRepositoryMock.CreateWithSlots at\n%s", m.CreateWithSlotsMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ScheduleRepositoryMock.CreateWithSlots at\n%s with params: %#v", m.CreateWithSlotsMock.defaultExpectation.expectationOrigins.origin, *m.CreateWithSlotsMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreateWithSlots != nil && afterCreateWithSlotsCounter < 1 {
		m.t.Errorf("Expected call to ScheduleRepositoryMock.CreateWithSlots at\n%s", m.funcCreateWithSlotsOrigin)
	}

	if !m.CreateWithSlotsMock.invocationsDone() && afterCreateWithSlotsCounter > 0 {
		m.t.Errorf("Expected %d calls to ScheduleRepositoryMock.CreateWithSlots at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateWithSlotsMock.expectedInvocations), m.CreateWithSlotsMock.expectedInvocationsOrigin, afterCreateWithSlotsCounter)
	}
}

type mScheduleRepositoryMockGetByRoomID struct {
	optional           bool
	mock               *ScheduleRepositoryMock
	defaultExpectation *ScheduleRepositoryMockGetByRoomIDExpectation
	expectations       []*ScheduleRepositoryMockGetByRoomIDExpectation

	callArgs []*ScheduleRepositoryMockGetByRoomIDParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ScheduleRepositoryMockGetByRoomIDExpectation specifies expectation struct of the ScheduleRepository.GetByRoomID
type ScheduleRepositoryMockGetByRoomIDExpectation struct {
	mock               *ScheduleRepositoryMock
	params             *ScheduleRepositoryMockGetByRoomIDParams
	paramPtrs          *ScheduleRepositoryMockGetByRoomIDParamPtrs
	expectationOrigins ScheduleRepositoryMockGetByRoomIDExpectationOrigins
	results            *ScheduleRepositoryMockGetByRoomIDResults
	returnOrigin       string
	Counter            uint64
}

// ScheduleRepositoryMockGetByRoomIDParams contains parameters of the ScheduleRepository.GetByRoomID
type ScheduleRepositoryMockGetByRoomIDParams struct {
	ctx    context.Context
	roomID string
}

// ScheduleRepositoryMockGetByRoomIDParamPtrs contains pointers to parameters of the ScheduleRepository.GetByRoomID
type ScheduleRepositoryMockGetByRoomIDParamPtrs struct {
	ctx    *context.Context
	roomID *string
}

// ScheduleRepositoryMockGetByRoomIDResults contains results of the ScheduleRepository.GetByRoomID
type ScheduleRepositoryMockGetByRoomIDResults struct {
	s1  domain.Schedule
	err error
}

// ScheduleRepositoryMockGetByRoomIDOrigins contains origins of expectations of the ScheduleRepository.GetByRoomID
type ScheduleRepositoryMockGetByRoomIDExpectationOrigins struct {
	origin       string
	originCtx    string
	originRoomID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetByRoomID *mScheduleRepositoryMockGetByRoomID) Optional() *mScheduleRepositoryMockGetByRoomID {
	mmGetByRoomID.optional = true
	return mmGetByRoomID
}

// Expect sets up expected params for ScheduleRepository.GetByRoomID
func (mmGetByRoomID *mScheduleRepositoryMockGetByRoomID) Expect(ctx context.Context, roomID string) *mScheduleRepositoryMockGetByRoomID {
	if mmGetByRoomID.mock.funcGetByRoomID != nil {
		mmGetByRoomID.mock.t.Fatalf("ScheduleRepositoryMock.GetByRoomID mock is already set by Set")
	}

	if mmGetByRoomID.defaultExpectation == nil {
		mmGetByRoomID.defaultExpectation = &ScheduleRepositoryMockGetByRoomIDExpectation{}
	}

	if mmGetByRoomID.defaultExpectation.paramPtrs != nil {
		mmGetByRoomID.mock.t.Fatalf("ScheduleRepositoryMock.GetByRoomID mock is already set by ExpectParams functions")
	}

	mmGetByRoomID.defaultExpectation.params = &ScheduleRepositoryMockGetByRoomIDParams{ctx, roomID}
	mmGetByRoomID.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetByRoomID.expectations {
		if minimock.Equal(e.params, mmGetByRoomID.defaultExpectation.params) {
			mmGetByRoomID.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetByRoomID.defaultExpectation.params)
		}
	}

	return mmGetByRoomID
}

// ExpectCtxParam1 sets up expected param ctx for ScheduleRepository.GetByRoomID
func (mmGetByRoomID *mScheduleRepositoryMockGetByRoomID) ExpectCtxParam1(ctx context.Context) *mScheduleRepositoryMockGetByRoomID {
	if mmGetByRoomID.mock.funcGetByRoomID != nil {
		mmGetByRoomID.mock.t.Fatalf("ScheduleRepositoryMock.GetByRoomID mock is already set by Set")
	}

	if mmGetByRoomID.defaultExpectation == nil {
		mmGetByRoomID.defaultExpectation = &ScheduleRepositoryMockGetByRoomIDExpectation{}
	}

	if mmGetByRoomID.defaultExpectation.params != nil {
		mmGetByRoomID.mock.t.Fatalf("ScheduleRepositoryMock.GetByRoomID mock is already set by Expect")
	}

	if mmGetByRoomID.defaultExpectation.paramPtrs == nil {
		mmGetByRoomID.defaultExpectation.paramPtrs = &ScheduleRepositoryMockGetByRoomIDParamPtrs{}
	}
	mmGetByRoomID.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetByRoomID.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetByRoomID
}

// ExpectRoomIDParam2 sets up expected param roomID for ScheduleRepository.GetByRoomID
func (mmGetByRoomID *mScheduleRepositoryMockGetByRoomID) ExpectRoomIDParam2(roomID string) *mScheduleRepositoryMockGetByRoomID {
	if mmGetByRoomID.mock.funcGetByRoomID != nil {
		mmGetByRoomID.mock.t.Fatalf("ScheduleRepositoryMock.GetByRoomID mock is already set by Set")
	}

	if mmGetByRoomID.defaultExpectation == nil {
		mmGetByRoomID.defaultExpectation = &ScheduleRepositoryMockGetByRoomIDExpectation{}
	}

	if mmGetByRoomID.defaultExpectation.params != nil {
		mmGetByRoomID.mock.t.Fatalf("ScheduleRepositoryMock.GetByRoomID mock is already set by Expect")
	}

	if mmGetByRoomID.defaultExpectation.paramPtrs == nil {
		mmGetByRoomID.defaultExpectation.paramPtrs = &ScheduleRepositoryMockGetByRoomIDParamPtrs{}
	}
	mmGetByRoomID.defaultExpectation.paramPtrs.roomID = &roomID
	mmGetByRoomID.defaultExpectation.expectationOrigins.originRoomID = minimock.CallerInfo(1)

	return mmGetByRoomID
}

// Inspect accepts an inspector function that has same arguments as the ScheduleRepository.GetByRoomID
func (mmGetByRoomID *mScheduleRepositoryMockGetByRoomID) Inspect(f func(ctx context.Context, roomID string)) *mScheduleRepositoryMockGetByRoomID {
	if mmGetByRoomID.mock.inspectFuncGetByRoomID != nil {
		mmGetByRoomID.mock.t.Fatalf("Inspect function is already set for ScheduleRepositoryMock.GetByRoomID")
	}

	mmGetByRoomID.mock.inspectFuncGetByRoomID = f

	return mmGetByRoomID
}

// Return sets up results that will be returned by ScheduleRepository.GetByRoomID
func (mmGetByRoomID *mScheduleRepositoryMockGetByRoomID) Return(s1 domain.Schedule, err error) *ScheduleRepositoryMock {
	if mmGetByRoomID.mock.funcGetByRoomID != nil {
		mmGetByRoomID.mock.t.Fatalf("ScheduleRepositoryMock.GetByRoomID mock is already set by Set")
	}

	if mmGetByRoomID.defaultExpectation == nil {
		mmGetByRoomID.defaultExpectation = &ScheduleRepositoryMockGetByRoomIDExpectation{mock: mmGetByRoomID.mock}
	}
	mmGetByRoomID.defaultExpectation.results = &ScheduleRepositoryMockGetByRoomIDResults{s1, err}
	mmGetByRoomID.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetByRoomID.mock
}

// Set uses given function f to mock the ScheduleRepository.GetByRoomID method
func (mmGetByRoomID *mScheduleRepositoryMockGetByRoomID) Set(f func(ctx context.Context, roomID string) (s1 domain.Schedule, err error)) *ScheduleRepositoryMock {
	if mmGetByRoomID.defaultExpectation != nil {
		mmGetByRoomID.mock.t.Fatalf("Default expectation is already set for the ScheduleRepository.GetByRoomID method")
	}

	if len(mmGetByRoomID.expectations) > 0 {
		mmGetByRoomID.mock.t.Fatalf("Some expectations are already set for the ScheduleRepository.GetByRoomID method")
	}

	mmGetByRoomID.mock.funcGetByRoomID = f
	mmGetByRoomID.mock.funcGetByRoomIDOrigin = minimock.CallerInfo(1)
	return mmGetByRoomID.mock
}

// When sets expectation for the ScheduleRepository.GetByRoomID which will trigger the result defined by the following
// Then helper
func (mmGetByRoomID *mScheduleRepositoryMockGetByRoomID) When(ctx context.Context, roomID string) *ScheduleRepositoryMockGetByRoomIDExpectation {
	if mmGetByRoomID.mock.funcGetByRoomID != nil {
		mmGetByRoomID.mock.t.Fatalf("ScheduleRepositoryMock.GetByRoomID mock is already set by Set")
	}

	expectation := &ScheduleRepositoryMockGetByRoomIDExpectation{
		mock:               mmGetByRoomID.mock,
		params:             &ScheduleRepositoryMockGetByRoomIDParams{ctx, roomID},
		expectationOrigins: ScheduleRepositoryMockGetByRoomIDExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetByRoomID.expectations = append(mmGetByRoomID.expectations, expectation)
	return expectation
}

// Then sets up ScheduleRepository.GetByRoomID return parameters for the expectation previously defined by the When method
func (e *ScheduleRepositoryMockGetByRoomIDExpectation) Then(s1 domain.Schedule, err error) *ScheduleRepositoryMock {
	e.results = &ScheduleRepositoryMockGetByRoomIDResults{s1, err}
	return e.mock
}

// Times sets number of times ScheduleRepository.GetByRoomID should be invoked
func (mmGetByRoomID *mScheduleRepositoryMockGetByRoomID) Times(n uint64) *mScheduleRepositoryMockGetByRoomID {
	if n == 0 {
		mmGetByRoomID.mock.t.Fatalf("Times of ScheduleRepositoryMock.GetByRoomID mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetByRoomID.expectedInvocations, n)
	mmGetByRoomID.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetByRoomID
}

func (mmGetByRoomID *mScheduleRepositoryMockGetByRoomID) invocationsDone() bool {
	if len(mmGetByRoomID.expectations) == 0 && mmGetByRoomID.defaultExpectation == nil && mmGetByRoomID.mock.funcGetByRoomID == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetByRoomID.mock.afterGetByRoomIDCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetByRoomID.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetByRoomID implements mm_repository.ScheduleRepository
func (mmGetByRoomID *ScheduleRepositoryMock) GetByRoomID(ctx context.Context, roomID string) (s1 domain.Schedule, err error) {
	mm_atomic.AddUint64(&mmGetByRoomID.beforeGetByRoomIDCounter, 1)
	defer mm_atomic.AddUint64(&mmGetByRoomID.afterGetByRoomIDCounter, 1)

	mmGetByRoomID.t.Helper()

	if mmGetByRoomID.inspectFuncGetByRoomID != nil {
		mmGetByRoomID.inspectFuncGetByRoomID(ctx, roomID)
	}

	mm_params := ScheduleRepositoryMockGetByRoomIDParams{ctx, roomID}

	// Record call args
	mmGetByRoomID.GetByRoomIDMock.mutex.Lock()
	mmGetByRoomID.GetByRoomIDMock.callArgs = append(mmGetByRoomID.GetByRoomIDMock.callArgs, &mm_params)
	mmGetByRoomID.GetByRoomIDMock.mutex.Unlock()

	for _, e := range mmGetByRoomID.GetByRoomIDMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1, e.results.err
		}
	}

	if mmGetByRoomID.GetByRoomIDMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetByRoomID.GetByRoomIDMock.defaultExpectation.Counter, 1)
		mm_want := mmGetByRoomID.GetByRoomIDMock.defaultExpectation.params
		mm_want_ptrs := mmGetByRoomID.GetByRoomIDMock.defaultExpectation.paramPtrs

		mm_got := ScheduleRepositoryMockGetByRoomIDParams{ctx, roomID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetByRoomID.t.Errorf("ScheduleRepositoryMock.GetByRoomID got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByRoomID.GetByRoomIDMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.roomID != nil && !minimock.Equal(*mm_want_ptrs.roomID, mm_got.roomID) {
				mmGetByRoomID.t.Errorf("ScheduleRepositoryMock.GetByRoomID got unexpected parameter roomID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByRoomID.GetByRoomIDMock.defaultExpectation.expectationOrigins.originRoomID, *mm_want_ptrs.roomID, mm_got.roomID, minimock.Diff(*mm_want_ptrs.roomID, mm_got.roomID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetByRoomID.t.Errorf("ScheduleRepositoryMock.GetByRoomID got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetByRoomID.GetByRoomIDMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetByRoomID.GetByRoomIDMock.defaultExpectation.results
		if mm_results == nil {
			mmGetByRoomID.t.Fatal("No results are set for the ScheduleRepositoryMock.GetByRoomID")
		}
		return (*mm_results).s1, (*mm_results).err
	}
	if mmGetByRoomID.funcGetByRoomID != nil {
		return mmGetByRoomID.funcGetByRoomID(ctx, roomID)
	}
	mmGetByRoomID.t.Fatalf("Unexpected call to ScheduleRepositoryMock.GetByRoomID. %v %v", ctx, roomID)
	return
}

// GetByRoomIDAfterCounter returns a count of finished ScheduleRepositoryMock.GetByRoomID invocations
func (mmGetByRoomID *ScheduleRepositoryMock) GetByRoomIDAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByRoomID.afterGetByRoomIDCounter)
}

// GetByRoomIDBeforeCounter returns a count of ScheduleRepositoryMock.GetByRoomID invocations
func (mmGetByRoomID *ScheduleRepositoryMock) GetByRoomIDBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByRoomID.beforeGetByRoomIDCounter)
}

// Calls returns a list of arguments used in each call to ScheduleRepositoryMock.GetByRoomID.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetByRoomID *mScheduleRepositoryMockGetByRoomID) Calls() []*ScheduleRepositoryMockGetByRoomIDParams {
	mmGetByRoomID.mutex.RLock()

	argCopy := make([]*ScheduleRepositoryMockGetByRoomIDParams, len(mmGetByRoomID.callArgs))
	copy(argCopy, mmGetByRoomID.callArgs)

	mmGetByRoomID.mutex.RUnlock()

	return argCopy
}

// MinimockGetByRoomIDDone returns true if the count of the GetByRoomID invocations corresponds
// the number of defined expectations
func (m *ScheduleRepositoryMock) MinimockGetByRoomIDDone() bool {
	if m.GetByRoomIDMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetByRoomIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetByRoomIDMock.invocationsDone()
}

// MinimockGetByRoomIDInspect logs each unmet expectation
func (m *ScheduleRepositoryMock) MinimockGetByRoomIDInspect() {
	for _, e := range m.GetByRoomIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ScheduleRepositoryMock.GetByRoomID at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetByRoomIDCounter := mm_atomic.LoadUint64(&m.afterGetByRoomIDCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetByRoomIDMock.defaultExpectation != nil && afterGetByRoomIDCounter < 1 {
		if m.GetByRoomIDMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ScheduleRepositoryMock.GetByRoomID at\n%s", m.GetByRoomIDMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ScheduleRepositoryMock.GetByRoomID at\n%s with params: %#v", m.GetByRoomIDMock.defaultExpectation.expectationOrigins.origin, *m.GetByRoomIDMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetByRoomID != nil && afterGetByRoomIDCounter < 1 {
		m.t.Errorf("Expected call to ScheduleRepositoryMock.GetByRoomID at\n%s", m.funcGetByRoomIDOrigin)
	}

	if !m.GetByRoomIDMock.invocationsDone() && afterGetByRoomIDCounter > 0 {
		m.t.Errorf("Expected %d calls to ScheduleRepositoryMock.GetByRoomID at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetByRoomIDMock.expectedInvocations), m.GetByRoomIDMock.expectedInvocationsOrigin, afterGetByRoomIDCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ScheduleRepositoryMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateWithSlotsInspect()

			m.MinimockGetByRoomIDInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ScheduleRepositoryMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ScheduleRepositoryMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateWithSlotsDone() &&
		m.MinimockGetByRoomIDDone()
}
