// Code generated by http://github.com/gojuno/minimock (v3.4.5). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/avito-internships/test-backend-1-M1steryO/internal/repository.ScheduleRepository -o schedule_repository_minimock.go -n ScheduleRepositoryMock -p mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/avito-internships/test-backend-1-M1steryO/internal/domain"
	"github.com/gojuno/minimock/v3"
)

// ScheduleRepositoryMock implements mm_repository.ScheduleRepository
type ScheduleRepositoryMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreate          func(ctx context.Context, schedule domain.Schedule) (s1 domain.Schedule, err error)
	funcCreateOrigin    string
	inspectFuncCreate   func(ctx context.Context, schedule domain.Schedule)
	afterCreateCounter  uint64
	beforeCreateCounter uint64
	CreateMock          mScheduleRepositoryMockCreate

	funcGetByRoomID          func(ctx context.Context, roomID string) (s1 domain.Schedule, err error)
	funcGetByRoomIDOrigin    string
	inspectFuncGetByRoomID   func(ctx context.Context, roomID string)
	afterGetByRoomIDCounter  uint64
	beforeGetByRoomIDCounter uint64
	GetByRoomIDMock          mScheduleRepositoryMockGetByRoomID
}

// NewScheduleRepositoryMock returns a mock for mm_repository.ScheduleRepository
func NewScheduleRepositoryMock(t minimock.Tester) *ScheduleRepositoryMock {
	m := &ScheduleRepositoryMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateMock = mScheduleRepositoryMockCreate{mock: m}
	m.CreateMock.callArgs = []*ScheduleRepositoryMockCreateParams{}

	m.GetByRoomIDMock = mScheduleRepositoryMockGetByRoomID{mock: m}
	m.GetByRoomIDMock.callArgs = []*ScheduleRepositoryMockGetByRoomIDParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mScheduleRepositoryMockCreate struct {
	optional           bool
	mock               *ScheduleRepositoryMock
	defaultExpectation *ScheduleRepositoryMockCreateExpectation
	expectations       []*ScheduleRepositoryMockCreateExpectation

	callArgs []*ScheduleRepositoryMockCreateParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ScheduleRepositoryMockCreateExpectation specifies expectation struct of the ScheduleRepository.Create
type ScheduleRepositoryMockCreateExpectation struct {
	mock               *ScheduleRepositoryMock
	params             *ScheduleRepositoryMockCreateParams
	paramPtrs          *ScheduleRepositoryMockCreateParamPtrs
	expectationOrigins ScheduleRepositoryMockCreateExpectationOrigins
	results            *ScheduleRepositoryMockCreateResults
	returnOrigin       string
	Counter            uint64
}

// ScheduleRepositoryMockCreateParams contains parameters of the ScheduleRepository.Create
type ScheduleRepositoryMockCreateParams struct {
	ctx      context.Context
	schedule domain.Schedule
}

// ScheduleRepositoryMockCreateParamPtrs contains pointers to parameters of the ScheduleRepository.Create
type ScheduleRepositoryMockCreateParamPtrs struct {
	ctx      *context.Context
	schedule *domain.Schedule
}

// ScheduleRepositoryMockCreateResults contains results of the ScheduleRepository.Create
type ScheduleRepositoryMockCreateResults struct {
	s1  domain.Schedule
	err error
}

// ScheduleRepositoryMockCreateOrigins contains origins of expectations of the ScheduleRepository.Create
type ScheduleRepositoryMockCreateExpectationOrigins struct {
	origin         string
	originCtx      string
	originSchedule string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreate *mScheduleRepositoryMockCreate) Optional() *mScheduleRepositoryMockCreate {
	mmCreate.optional = true
	return mmCreate
}

// Expect sets up expected params for ScheduleRepository.Create
func (mmCreate *mScheduleRepositoryMockCreate) Expect(ctx context.Context, schedule domain.Schedule) *mScheduleRepositoryMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("ScheduleRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &ScheduleRepositoryMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.paramPtrs != nil {
		mmCreate.mock.t.Fatalf("ScheduleRepositoryMock.Create mock is already set by ExpectParams functions")
	}

	mmCreate.defaultExpectation.params = &ScheduleRepositoryMockCreateParams{ctx, schedule}
	mmCreate.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreate.expectations {
		if minimock.Equal(e.params, mmCreate.defaultExpectation.params) {
			mmCreate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreate.defaultExpectation.params)
		}
	}

	return mmCreate
}

// ExpectCtxParam1 sets up expected param ctx for ScheduleRepository.Create
func (mmCreate *mScheduleRepositoryMockCreate) ExpectCtxParam1(ctx context.Context) *mScheduleRepositoryMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("ScheduleRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &ScheduleRepositoryMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("ScheduleRepositoryMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &ScheduleRepositoryMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreate.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreate
}

// ExpectScheduleParam2 sets up expected param schedule for ScheduleRepository.Create
func (mmCreate *mScheduleRepositoryMockCreate) ExpectScheduleParam2(schedule domain.Schedule) *mScheduleRepositoryMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("ScheduleRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &ScheduleRepositoryMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("ScheduleRepositoryMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &ScheduleRepositoryMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.schedule = &schedule
	mmCreate.defaultExpectation.expectationOrigins.originSchedule = minimock.CallerInfo(1)

	return mmCreate
}

// Inspect accepts an inspector function that has same arguments as the ScheduleRepository.Create
func (mmCreate *mScheduleRepositoryMockCreate) Inspect(f func(ctx context.Context, schedule domain.Schedule)) *mScheduleRepositoryMockCreate {
	if mmCreate.mock.inspectFuncCreate != nil {
		mmCreate.mock.t.Fatalf("Inspect function is already set for ScheduleRepositoryMock.Create")
	}

	mmCreate.mock.inspectFuncCreate = f

	return mmCreate
}

// Return sets up results that will be returned by ScheduleRepository.Create
func (mmCreate *mScheduleRepositoryMockCreate) Return(s1 domain.Schedule, err error) *ScheduleRepositoryMock {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("ScheduleRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &ScheduleRepositoryMockCreateExpectation{mock: mmCreate.mock}
	}
	mmCreate.defaultExpectation.results = &ScheduleRepositoryMockCreateResults{s1, err}
	mmCreate.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreate.mock
}

// Set uses given function f to mock the ScheduleRepository.Create method
func (mmCreate *mScheduleRepositoryMockCreate) Set(f func(ctx context.Context, schedule domain.Schedule) (s1 domain.Schedule, err error)) *ScheduleRepositoryMock {
	if mmCreate.defaultExpectation != nil {
		mmCreate.mock.t.Fatalf("Default expectation is already set for the ScheduleRepository.Create method")
	}

	if len(mmCreate.expectations) > 0 {
		mmCreate.mock.t.Fatalf("Some expectations are already set for the ScheduleRepository.Create method")
	}

	mmCreate.mock.funcCreate = f
	mmCreate.mock.funcCreateOrigin = minimock.CallerInfo(1)
	return mmCreate.mock
}

// When sets expectation for the ScheduleRepository.Create which will trigger the result defined by the following
// Then helper
func (mmCreate *mScheduleRepositoryMockCreate) When(ctx context.Context, schedule domain.Schedule) *ScheduleRepositoryMockCreateExpectation {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("ScheduleRepositoryMock.Create mock is already set by Set")
	}

	expectation := &ScheduleRepositoryMockCreateExpectation{
		mock:               mmCreate.mock,
		params:             &ScheduleRepositoryMockCreateParams{ctx, schedule},
		expectationOrigins: ScheduleRepositoryMockCreateExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreate.expectations = append(mmCreate.expectations, expectation)
	return expectation
}

// Then sets up ScheduleRepository.Create return parameters for the expectation previously defined by the When method
func (e *ScheduleRepositoryMockCreateExpectation) Then(s1 domain.Schedule, err error) *ScheduleRepositoryMock {
	e.results = &ScheduleRepositoryMockCreateResults{s1, err}
	return e.mock
}

// Times sets number of times ScheduleRepository.Create should be invoked
func (mmCreate *mScheduleRepositoryMockCreate) Times(n uint64) *mScheduleRepositoryMockCreate {
	if n == 0 {
		mmCreate.mock.t.Fatalf("Times of ScheduleRepositoryMock.Create mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreate.expectedInvocations, n)
	mmCreate.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreate
}

func (mmCreate *mScheduleRepositoryMockCreate) invocationsDone() bool {
	if len(mmCreate.expectations) == 0 && mmCreate.defaultExpectation == nil && mmCreate.mock.funcCreate == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreate.mock.afterCreateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreate.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Create implements mm_repository.ScheduleRepository
func (mmCreate *ScheduleRepositoryMock) Create(ctx context.Context, schedule domain.Schedule) (s1 domain.Schedule, err error) {
	mm_atomic.AddUint64(&mmCreate.beforeCreateCounter, 1)
	defer mm_atomic.AddUint64(&mmCreate.afterCreateCounter, 1)

	mmCreate.t.Helper()

	if mmCreate.inspectFuncCreate != nil {
		mmCreate.inspectFuncCreate(ctx, schedule)
	}

	mm_params := ScheduleRepositoryMockCreateParams{ctx, schedule}

	// Record call args
	mmCreate.CreateMock.mutex.Lock()
	mmCreate.CreateMock.callArgs = append(mmCreate.CreateMock.callArgs, &mm_params)
	mmCreate.CreateMock.mutex.Unlock()

	for _, e := range mmCreate.CreateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1, e.results.err
		}
	}

	if mmCreate.CreateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreate.CreateMock.defaultExpectation.Counter, 1)
		mm_want := mmCreate.CreateMock.defaultExpectation.params
		mm_want_ptrs := mmCreate.CreateMock.defaultExpectation.paramPtrs

		mm_got := ScheduleRepositoryMockCreateParams{ctx, schedule}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreate.t.Errorf("ScheduleRepositoryMock.Create got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.schedule != nil && !minimock.Equal(*mm_want_ptrs.schedule, mm_got.schedule) {
				mmCreate.t.Errorf("ScheduleRepositoryMock.Create got unexpected parameter schedule, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originSchedule, *mm_want_ptrs.schedule, mm_got.schedule, minimock.Diff(*mm_want_ptrs.schedule, mm_got.schedule))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreate.t.Errorf("ScheduleRepositoryMock.Create got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreate.CreateMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreate.CreateMock.defaultExpectation.results
		if mm_results == nil {
			mmCreate.t.Fatal("No results are set for the ScheduleRepositoryMock.Create")
		}
		return (*mm_results).s1, (*mm_results).err
	}
	if mmCreate.funcCreate != nil {
		return mmCreate.funcCreate(ctx, schedule)
	}
	mmCreate.t.Fatalf("Unexpected call to ScheduleRepositoryMock.Create. %v %v", ctx, schedule)
	return
}

// CreateAfterCounter returns a count of finished ScheduleRepositoryMock.Create invocations
func (mmCreate *ScheduleRepositoryMock) CreateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.afterCreateCounter)
}

// CreateBeforeCounter returns a count of ScheduleRepositoryMock.Create invocations
func (mmCreate *ScheduleRepositoryMock) CreateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.beforeCreateCounter)
}

// Calls returns a list of arguments used in each call to ScheduleRepositoryMock.Create.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreate *mScheduleRepositoryMockCreate) Calls() []*ScheduleRepositoryMockCreateParams {
	mmCreate.mutex.RLock()

	argCopy := make([]*ScheduleRepositoryMockCreateParams, len(mmCreate.callArgs))
	copy(argCopy, mmCreate.callArgs)

	mmCreate.mutex.RUnlock()

	return argCopy
}

// MinimockCreateDone returns true if the count of the Create invocations corresponds
// the number of defined expectations
func (m *ScheduleRepositoryMock) MinimockCreateDone() bool {
	if m.CreateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateMock.invocationsDone()
}

// MinimockCreateInspect logs each unmet expectation
func (m *ScheduleRepositoryMock) MinimockCreateInspect() {
	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ScheduleRepositoryMock.Create at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateCounter := mm_atomic.LoadUint64(&m.afterCreateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateMock.defaultExpectation != nil && afterCreateCounter < 1 {
		if m.CreateMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ScheduleRepositoryMock.Create at\n%s", m.CreateMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ScheduleRepositoryMock.Create at\n%s with params: %#v", m.CreateMock.defaultExpectation.expectationOrigins.origin, *m.CreateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreate != nil && afterCreateCounter < 1 {
		m.t.Errorf("Expected call to ScheduleRepositoryMock.Create at\n%s", m.funcCreateOrigin)
	}

	if !m.CreateMock.invocationsDone() && afterCreateCounter > 0 {
		m.t.Errorf("Expected %d calls to ScheduleRepositoryMock.Create at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateMock.expectedInvocations), m.CreateMock.expectedInvocationsOrigin, afterCreateCounter)
	}
}

type mScheduleRepositoryMockGetByRoomID struct {
	optional           bool
	mock               *ScheduleRepositoryMock
	defaultExpectation *ScheduleRepositoryMockGetByRoomIDExpectation
	expectations       []*ScheduleRepositoryMockGetByRoomIDExpectation

	callArgs []*ScheduleRepositoryMockGetByRoomIDParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ScheduleRepositoryMockGetByRoomIDExpectation specifies expectation struct of the ScheduleRepository.GetByRoomID
type ScheduleRepositoryMockGetByRoomIDExpectation struct {
	mock               *ScheduleRepositoryMock
	params             *ScheduleRepositoryMockGetByRoomIDParams
	paramPtrs          *ScheduleRepositoryMockGetByRoomIDParamPtrs
	expectationOrigins ScheduleRepositoryMockGetByRoomIDExpectationOrigins
	results            *ScheduleRepositoryMockGetByRoomIDResults
	returnOrigin       string
	Counter            uint64
}

// ScheduleRepositoryMockGetByRoomIDParams contains parameters of the ScheduleRepository.GetByRoomID
type ScheduleRepositoryMockGetByRoomIDParams struct {
	ctx    context.Context
	roomID string
}

// ScheduleRepositoryMockGetByRoomIDParamPtrs contains pointers to parameters of the ScheduleRepository.GetByRoomID
type ScheduleRepositoryMockGetByRoomIDParamPtrs struct {
	ctx    *context.Context
	roomID *string
}

// ScheduleRepositoryMockGetByRoomIDResults contains results of the ScheduleRepository.GetByRoomID
type ScheduleRepositoryMockGetByRoomIDResults struct {
	s1  domain.Schedule
	err error
}

// ScheduleRepositoryMockGetByRoomIDOrigins contains origins of expectations of the ScheduleRepository.GetByRoomID
type ScheduleRepositoryMockGetByRoomIDExpectationOrigins struct {
	origin       string
	originCtx    string
	originRoomID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetByRoomID *mScheduleRepositoryMockGetByRoomID) Optional() *mScheduleRepositoryMockGetByRoomID {
	mmGetByRoomID.optional = true
	return mmGetByRoomID
}

// Expect sets up expected params for ScheduleRepository.GetByRoomID
func (mmGetByRoomID *mScheduleRepositoryMockGetByRoomID) Expect(ctx context.Context, roomID string) *mScheduleRepositoryMockGetByRoomID {
	if mmGetByRoomID.mock.funcGetByRoomID != nil {
		mmGetByRoomID.mock.t.Fatalf("ScheduleRepositoryMock.GetByRoomID mock is already set by Set")
	}

	if mmGetByRoomID.defaultExpectation == nil {
		mmGetByRoomID.defaultExpectation = &ScheduleRepositoryMockGetByRoomIDExpectation{}
	}

	if mmGetByRoomID.defaultExpectation.paramPtrs != nil {
		mmGetByRoomID.mock.t.Fatalf("ScheduleRepositoryMock.GetByRoomID mock is already set by ExpectParams functions")
	}

	mmGetByRoomID.defaultExpectation.params = &ScheduleRepositoryMockGetByRoomIDParams{ctx, roomID}
	mmGetByRoomID.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetByRoomID.expectations {
		if minimock.Equal(e.params, mmGetByRoomID.defaultExpectation.params) {
			mmGetByRoomID.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetByRoomID.defaultExpectation.params)
		}
	}

	return mmGetByRoomID
}

// ExpectCtxParam1 sets up expected param ctx for ScheduleRepository.GetByRoomID
func (mmGetByRoomID *mScheduleRepositoryMockGetByRoomID) ExpectCtxParam1(ctx context.Context) *mScheduleRepositoryMockGetByRoomID {
	if mmGetByRoomID.mock.funcGetByRoomID != nil {
		mmGetByRoomID.mock.t.Fatalf("ScheduleRepositoryMock.GetByRoomID mock is already set by Set")
	}

	if mmGetByRoomID.defaultExpectation == nil {
		mmGetByRoomID.defaultExpectation = &ScheduleRepositoryMockGetByRoomIDExpectation{}
	}

	if mmGetByRoomID.defaultExpectation.params != nil {
		mmGetByRoomID.mock.t.Fatalf("ScheduleRepositoryMock.GetByRoomID mock is already set by Expect")
	}

	if mmGetByRoomID.defaultExpectation.paramPtrs == nil {
		mmGetByRoomID.defaultExpectation.paramPtrs = &ScheduleRepositoryMockGetByRoomIDParamPtrs{}
	}
	mmGetByRoomID.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetByRoomID.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetByRoomID
}

// ExpectRoomIDParam2 sets up expected param roomID for ScheduleRepository.GetByRoomID
func (mmGetByRoomID *mScheduleRepositoryMockGetByRoomID) ExpectRoomIDParam2(roomID string) *mScheduleRepositoryMockGetByRoomID {
	if mmGetByRoomID.mock.funcGetByRoomID != nil {
		mmGetByRoomID.mock.t.Fatalf("ScheduleRepositoryMock.GetByRoomID mock is already set by Set")
	}

	if mmGetByRoomID.defaultExpectation == nil {
		mmGetByRoomID.defaultExpectation = &ScheduleRepositoryMockGetByRoomIDExpectation{}
	}

	if mmGetByRoomID.defaultExpectation.params != nil {
		mmGetByRoomID.mock.t.Fatalf("ScheduleRepositoryMock.GetByRoomID mock is already set by Expect")
	}

	if mmGetByRoomID.defaultExpectation.paramPtrs == nil {
		mmGetByRoomID.defaultExpectation.paramPtrs = &ScheduleRepositoryMockGetByRoomIDParamPtrs{}
	}
	mmGetByRoomID.defaultExpectation.paramPtrs.roomID = &roomID
	mmGetByRoomID.defaultExpectation.expectationOrigins.originRoomID = minimock.CallerInfo(1)

	return mmGetByRoomID
}

// Inspect accepts an inspector function that has same arguments as the ScheduleRepository.GetByRoomID
func (mmGetByRoomID *mScheduleRepositoryMockGetByRoomID) Inspect(f func(ctx context.Context, roomID string)) *mScheduleRepositoryMockGetByRoomID {
	if mmGetByRoomID.mock.inspectFuncGetByRoomID != nil {
		mmGetByRoomID.mock.t.Fatalf("Inspect function is already set for ScheduleRepositoryMock.GetByRoomID")
	}

	mmGetByRoomID.mock.inspectFuncGetByRoomID = f

	return mmGetByRoomID
}

// Return sets up results that will be returned by ScheduleRepository.GetByRoomID
func (mmGetByRoomID *mScheduleRepositoryMockGetByRoomID) Return(s1 domain.Schedule, err error) *ScheduleRepositoryMock {
	if mmGetByRoomID.mock.funcGetByRoomID != nil {
		mmGetByRoomID.mock.t.Fatalf("ScheduleRepositoryMock.GetByRoomID mock is already set by Set")
	}

	if mmGetByRoomID.defaultExpectation == nil {
		mmGetByRoomID.defaultExpectation = &ScheduleRepositoryMockGetByRoomIDExpectation{mock: mmGetByRoomID.mock}
	}
	mmGetByRoomID.defaultExpectation.results = &ScheduleRepositoryMockGetByRoomIDResults{s1, err}
	mmGetByRoomID.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetByRoomID.mock
}

// Set uses given function f to mock the ScheduleRepository.GetByRoomID method
func (mmGetByRoomID *mScheduleRepositoryMockGetByRoomID) Set(f func(ctx context.Context, roomID string) (s1 domain.Schedule, err error)) *ScheduleRepositoryMock {
	if mmGetByRoomID.defaultExpectation != nil {
		mmGetByRoomID.mock.t.Fatalf("Default expectation is already set for the ScheduleRepository.GetByRoomID method")
	}

	if len(mmGetByRoomID.expectations) > 0 {
		mmGetByRoomID.mock.t.Fatalf("Some expectations are already set for the ScheduleRepository.GetByRoomID method")
	}

	mmGetByRoomID.mock.funcGetByRoomID = f
	mmGetByRoomID.mock.funcGetByRoomIDOrigin = minimock.CallerInfo(1)
	return mmGetByRoomID.mock
}

// When sets expectation for the ScheduleRepository.GetByRoomID which will trigger the result defined by the following
// Then helper
func (mmGetByRoomID *mScheduleRepositoryMockGetByRoomID) When(ctx context.Context, roomID string) *ScheduleRepositoryMockGetByRoomIDExpectation {
	if mmGetByRoomID.mock.funcGetByRoomID != nil {
		mmGetByRoomID.mock.t.Fatalf("ScheduleRepositoryMock.GetByRoomID mock is already set by Set")
	}

	expectation := &ScheduleRepositoryMockGetByRoomIDExpectation{
		mock:               mmGetByRoomID.mock,
		params:             &ScheduleRepositoryMockGetByRoomIDParams{ctx, roomID},
		expectationOrigins: ScheduleRepositoryMockGetByRoomIDExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetByRoomID.expectations = append(mmGetByRoomID.expectations, expectation)
	return expectation
}

// Then sets up ScheduleRepository.GetByRoomID return parameters for the expectation previously defined by the When method
func (e *ScheduleRepositoryMockGetByRoomIDExpectation) Then(s1 domain.Schedule, err error) *ScheduleRepositoryMock {
	e.results = &ScheduleRepositoryMockGetByRoomIDResults{s1, err}
	return e.mock
}

// Times sets number of times ScheduleRepository.GetByRoomID should be invoked
func (mmGetByRoomID *mScheduleRepositoryMockGetByRoomID) Times(n uint64) *mScheduleRepositoryMockGetByRoomID {
	if n == 0 {
		mmGetByRoomID.mock.t.Fatalf("Times of ScheduleRepositoryMock.GetByRoomID mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetByRoomID.expectedInvocations, n)
	mmGetByRoomID.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetByRoomID
}

func (mmGetByRoomID *mScheduleRepositoryMockGetByRoomID) invocationsDone() bool {
	if len(mmGetByRoomID.expectations) == 0 && mmGetByRoomID.defaultExpectation == nil && mmGetByRoomID.mock.funcGetByRoomID == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetByRoomID.mock.afterGetByRoomIDCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetByRoomID.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetByRoomID implements mm_repository.ScheduleRepository
func (mmGetByRoomID *ScheduleRepositoryMock) GetByRoomID(ctx context.Context, roomID string) (s1 domain.Schedule, err error) {
	mm_atomic.AddUint64(&mmGetByRoomID.beforeGetByRoomIDCounter, 1)
	defer mm_atomic.AddUint64(&mmGetByRoomID.afterGetByRoomIDCounter, 1)

	mmGetByRoomID.t.Helper()

	if mmGetByRoomID.inspectFuncGetByRoomID != nil {
		mmGetByRoomID.inspectFuncGetByRoomID(ctx, roomID)
	}

	mm_params := ScheduleRepositoryMockGetByRoomIDParams{ctx, roomID}

	// Record call args
	mmGetByRoomID.GetByRoomIDMock.mutex.Lock()
	mmGetByRoomID.GetByRoomIDMock.callArgs = append(mmGetByRoomID.GetByRoomIDMock.callArgs, &mm_params)
	mmGetByRoomID.GetByRoomIDMock.mutex.Unlock()

	for _, e := range mmGetByRoomID.GetByRoomIDMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1, e.results.err
		}
	}

	if mmGetByRoomID.GetByRoomIDMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetByRoomID.GetByRoomIDMock.defaultExpectation.Counter, 1)
		mm_want := mmGetByRoomID.GetByRoomIDMock.defaultExpectation.params
		mm_want_ptrs := mmGetByRoomID.GetByRoomIDMock.defaultExpectation.paramPtrs

		mm_got := ScheduleRepositoryMockGetByRoomIDParams{ctx, roomID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetByRoomID.t.Errorf("ScheduleRepositoryMock.GetByRoomID got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByRoomID.GetByRoomIDMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.roomID != nil && !minimock.Equal(*mm_want_ptrs.roomID, mm_got.roomID) {
				mmGetByRoomID.t.Errorf("ScheduleRepositoryMock.GetByRoomID got unexpected parameter roomID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByRoomID.GetByRoomIDMock.defaultExpectation.expectationOrigins.originRoomID, *mm_want_ptrs.roomID, mm_got.roomID, minimock.Diff(*mm_want_ptrs.roomID, mm_got.roomID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetByRoomID.t.Errorf("ScheduleRepositoryMock.GetByRoomID got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetByRoomID.GetByRoomIDMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetByRoomID.GetByRoomIDMock.defaultExpectation.results
		if mm_results == nil {
			mmGetByRoomID.t.Fatal("No results are set for the ScheduleRepositoryMock.GetByRoomID")
		}
		return (*mm_results).s1, (*mm_results).err
	}
	if mmGetByRoomID.funcGetByRoomID != nil {
		return mmGetByRoomID.funcGetByRoomID(ctx, roomID)
	}
	mmGetByRoomID.t.Fatalf("Unexpected call to ScheduleRepositoryMock.GetByRoomID. %v %v", ctx, roomID)
	return
}

// GetByRoomIDAfterCounter returns a count of finished ScheduleRepositoryMock.GetByRoomID invocations
func (mmGetByRoomID *ScheduleRepositoryMock) GetByRoomIDAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByRoomID.afterGetByRoomIDCounter)
}

// GetByRoomIDBeforeCounter returns a count of ScheduleRepositoryMock.GetByRoomID invocations
func (mmGetByRoomID *ScheduleRepositoryMock) GetByRoomIDBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByRoomID.beforeGetByRoomIDCounter)
}

// Calls returns a list of arguments used in each call to ScheduleRepositoryMock.GetByRoomID.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetByRoomID *mScheduleRepositoryMockGetByRoomID) Calls() []*ScheduleRepositoryMockGetByRoomIDParams {
	mmGetByRoomID.mutex.RLock()

	argCopy := make([]*ScheduleRepositoryMockGetByRoomIDParams, len(mmGetByRoomID.callArgs))
	copy(argCopy, mmGetByRoomID.callArgs)

	mmGetByRoomID.mutex.RUnlock()

	return argCopy
}

// MinimockGetByRoomIDDone returns true if the count of the GetByRoomID invocations corresponds
// the number of defined expectations
func (m *ScheduleRepositoryMock) MinimockGetByRoomIDDone() bool {
	if m.GetByRoomIDMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetByRoomIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetByRoomIDMock.invocationsDone()
}

// MinimockGetByRoomIDInspect logs each unmet expectation
func (m *ScheduleRepositoryMock) MinimockGetByRoomIDInspect() {
	for _, e := range m.GetByRoomIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ScheduleRepositoryMock.GetByRoomID at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetByRoomIDCounter := mm_atomic.LoadUint64(&m.afterGetByRoomIDCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetByRoomIDMock.defaultExpectation != nil && afterGetByRoomIDCounter < 1 {
		if m.GetByRoomIDMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ScheduleRepositoryMock.GetByRoomID at\n%s", m.GetByRoomIDMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ScheduleRepositoryMock.GetByRoomID at\n%s with params: %#v", m.GetByRoomIDMock.defaultExpectation.expectationOrigins.origin, *m.GetByRoomIDMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetByRoomID != nil && afterGetByRoomIDCounter < 1 {
		m.t.Errorf("Expected call to ScheduleRepositoryMock.GetByRoomID at\n%s", m.funcGetByRoomIDOrigin)
	}

	if !m.GetByRoomIDMock.invocationsDone() && afterGetByRoomIDCounter > 0 {
		m.t.Errorf("Expected %d calls to ScheduleRepositoryMock.GetByRoomID at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetByRoomIDMock.expectedInvocations), m.GetByRoomIDMock.expectedInvocationsOrigin, afterGetByRoomIDCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ScheduleRepositoryMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateInspect()

			m.MinimockGetByRoomIDInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ScheduleRepositoryMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ScheduleRepositoryMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateDone() &&
		m.MinimockGetByRoomIDDone()
}
