// Code generated by http://github.com/gojuno/minimock (v3.4.5). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/M1steryO/Room-Booking-Service/internal/repository.SlotRepository -o slot_repository_minimock.go -n SlotRepositoryMock -p mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	"time"
	mm_time "time"

	"github.com/M1steryO/Room-Booking-Service/internal/domain"
	"github.com/gojuno/minimock/v3"
)

// SlotRepositoryMock implements mm_repository.SlotRepository
type SlotRepositoryMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcBulkUpsert          func(ctx context.Context, slots []domain.Slot) (err error)
	funcBulkUpsertOrigin    string
	inspectFuncBulkUpsert   func(ctx context.Context, slots []domain.Slot)
	afterBulkUpsertCounter  uint64
	beforeBulkUpsertCounter uint64
	BulkUpsertMock          mSlotRepositoryMockBulkUpsert

	funcDateHasSlots          func(ctx context.Context, roomID string, date time.Time) (b1 bool, err error)
	funcDateHasSlotsOrigin    string
	inspectFuncDateHasSlots   func(ctx context.Context, roomID string, date time.Time)
	afterDateHasSlotsCounter  uint64
	beforeDateHasSlotsCounter uint64
	DateHasSlotsMock          mSlotRepositoryMockDateHasSlots

	funcGetByID          func(ctx context.Context, slotID string) (s1 domain.Slot, err error)
	funcGetByIDOrigin    string
	inspectFuncGetByID   func(ctx context.Context, slotID string)
	afterGetByIDCounter  uint64
	beforeGetByIDCounter uint64
	GetByIDMock          mSlotRepositoryMockGetByID

	funcListAvailableByRoomAndDate          func(ctx context.Context, roomID string, date time.Time) (sa1 []domain.Slot, err error)
	funcListAvailableByRoomAndDateOrigin    string
	inspectFuncListAvailableByRoomAndDate   func(ctx context.Context, roomID string, date time.Time)
	afterListAvailableByRoomAndDateCounter  uint64
	beforeListAvailableByRoomAndDateCounter uint64
	ListAvailableByRoomAndDateMock          mSlotRepositoryMockListAvailableByRoomAndDate
}

// NewSlotRepositoryMock returns a mock for mm_repository.SlotRepository
func NewSlotRepositoryMock(t minimock.Tester) *SlotRepositoryMock {
	m := &SlotRepositoryMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.BulkUpsertMock = mSlotRepositoryMockBulkUpsert{mock: m}
	m.BulkUpsertMock.callArgs = []*SlotRepositoryMockBulkUpsertParams{}

	m.DateHasSlotsMock = mSlotRepositoryMockDateHasSlots{mock: m}
	m.DateHasSlotsMock.callArgs = []*SlotRepositoryMockDateHasSlotsParams{}

	m.GetByIDMock = mSlotRepositoryMockGetByID{mock: m}
	m.GetByIDMock.callArgs = []*SlotRepositoryMockGetByIDParams{}

	m.ListAvailableByRoomAndDateMock = mSlotRepositoryMockListAvailableByRoomAndDate{mock: m}
	m.ListAvailableByRoomAndDateMock.callArgs = []*SlotRepositoryMockListAvailableByRoomAndDateParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mSlotRepositoryMockBulkUpsert struct {
	optional           bool
	mock               *SlotRepositoryMock
	defaultExpectation *SlotRepositoryMockBulkUpsertExpectation
	expectations       []*SlotRepositoryMockBulkUpsertExpectation

	callArgs []*SlotRepositoryMockBulkUpsertParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// SlotRepositoryMockBulkUpsertExpectation specifies expectation struct of the SlotRepository.BulkUpsert
type SlotRepositoryMockBulkUpsertExpectation struct {
	mock               *SlotRepositoryMock
	params             *SlotRepositoryMockBulkUpsertParams
	paramPtrs          *SlotRepositoryMockBulkUpsertParamPtrs
	expectationOrigins SlotRepositoryMockBulkUpsertExpectationOrigins
	results            *SlotRepositoryMockBulkUpsertResults
	returnOrigin       string
	Counter            uint64
}

// SlotRepositoryMockBulkUpsertParams contains parameters of the SlotRepository.BulkUpsert
type SlotRepositoryMockBulkUpsertParams struct {
	ctx   context.Context
	slots []domain.Slot
}

// SlotRepositoryMockBulkUpsertParamPtrs contains pointers to parameters of the SlotRepository.BulkUpsert
type SlotRepositoryMockBulkUpsertParamPtrs struct {
	ctx   *context.Context
	slots *[]domain.Slot
}

// SlotRepositoryMockBulkUpsertResults contains results of the SlotRepository.BulkUpsert
type SlotRepositoryMockBulkUpsertResults struct {
	err error
}

// SlotRepositoryMockBulkUpsertOrigins contains origins of expectations of the SlotRepository.BulkUpsert
type SlotRepositoryMockBulkUpsertExpectationOrigins struct {
	origin      string
	originCtx   string
	originSlots string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmBulkUpsert *mSlotRepositoryMockBulkUpsert) Optional() *mSlotRepositoryMockBulkUpsert {
	mmBulkUpsert.optional = true
	return mmBulkUpsert
}

// Expect sets up expected params for SlotRepository.BulkUpsert
func (mmBulkUpsert *mSlotRepositoryMockBulkUpsert) Expect(ctx context.Context, slots []domain.Slot) *mSlotRepositoryMockBulkUpsert {
	if mmBulkUpsert.mock.funcBulkUpsert != nil {
		mmBulkUpsert.mock.t.Fatalf("SlotRepositoryMock.BulkUpsert mock is already set by Set")
	}

	if mmBulkUpsert.defaultExpectation == nil {
		mmBulkUpsert.defaultExpectation = &SlotRepositoryMockBulkUpsertExpectation{}
	}

	if mmBulkUpsert.defaultExpectation.paramPtrs != nil {
		mmBulkUpsert.mock.t.Fatalf("SlotRepositoryMock.BulkUpsert mock is already set by ExpectParams functions")
	}

	mmBulkUpsert.defaultExpectation.params = &SlotRepositoryMockBulkUpsertParams{ctx, slots}
	mmBulkUpsert.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmBulkUpsert.expectations {
		if minimock.Equal(e.params, mmBulkUpsert.defaultExpectation.params) {
			mmBulkUpsert.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmBulkUpsert.defaultExpectation.params)
		}
	}

	return mmBulkUpsert
}

// ExpectCtxParam1 sets up expected param ctx for SlotRepository.BulkUpsert
func (mmBulkUpsert *mSlotRepositoryMockBulkUpsert) ExpectCtxParam1(ctx context.Context) *mSlotRepositoryMockBulkUpsert {
	if mmBulkUpsert.mock.funcBulkUpsert != nil {
		mmBulkUpsert.mock.t.Fatalf("SlotRepositoryMock.BulkUpsert mock is already set by Set")
	}

	if mmBulkUpsert.defaultExpectation == nil {
		mmBulkUpsert.defaultExpectation = &SlotRepositoryMockBulkUpsertExpectation{}
	}

	if mmBulkUpsert.defaultExpectation.params != nil {
		mmBulkUpsert.mock.t.Fatalf("SlotRepositoryMock.BulkUpsert mock is already set by Expect")
	}

	if mmBulkUpsert.defaultExpectation.paramPtrs == nil {
		mmBulkUpsert.defaultExpectation.paramPtrs = &SlotRepositoryMockBulkUpsertParamPtrs{}
	}
	mmBulkUpsert.defaultExpectation.paramPtrs.ctx = &ctx
	mmBulkUpsert.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmBulkUpsert
}

// ExpectSlotsParam2 sets up expected param slots for SlotRepository.BulkUpsert
func (mmBulkUpsert *mSlotRepositoryMockBulkUpsert) ExpectSlotsParam2(slots []domain.Slot) *mSlotRepositoryMockBulkUpsert {
	if mmBulkUpsert.mock.funcBulkUpsert != nil {
		mmBulkUpsert.mock.t.Fatalf("SlotRepositoryMock.BulkUpsert mock is already set by Set")
	}

	if mmBulkUpsert.defaultExpectation == nil {
		mmBulkUpsert.defaultExpectation = &SlotRepositoryMockBulkUpsertExpectation{}
	}

	if mmBulkUpsert.defaultExpectation.params != nil {
		mmBulkUpsert.mock.t.Fatalf("SlotRepositoryMock.BulkUpsert mock is already set by Expect")
	}

	if mmBulkUpsert.defaultExpectation.paramPtrs == nil {
		mmBulkUpsert.defaultExpectation.paramPtrs = &SlotRepositoryMockBulkUpsertParamPtrs{}
	}
	mmBulkUpsert.defaultExpectation.paramPtrs.slots = &slots
	mmBulkUpsert.defaultExpectation.expectationOrigins.originSlots = minimock.CallerInfo(1)

	return mmBulkUpsert
}

// Inspect accepts an inspector function that has same arguments as the SlotRepository.BulkUpsert
func (mmBulkUpsert *mSlotRepositoryMockBulkUpsert) Inspect(f func(ctx context.Context, slots []domain.Slot)) *mSlotRepositoryMockBulkUpsert {
	if mmBulkUpsert.mock.inspectFuncBulkUpsert != nil {
		mmBulkUpsert.mock.t.Fatalf("Inspect function is already set for SlotRepositoryMock.BulkUpsert")
	}

	mmBulkUpsert.mock.inspectFuncBulkUpsert = f

	return mmBulkUpsert
}

// Return sets up results that will be returned by SlotRepository.BulkUpsert
func (mmBulkUpsert *mSlotRepositoryMockBulkUpsert) Return(err error) *SlotRepositoryMock {
	if mmBulkUpsert.mock.funcBulkUpsert != nil {
		mmBulkUpsert.mock.t.Fatalf("SlotRepositoryMock.BulkUpsert mock is already set by Set")
	}

	if mmBulkUpsert.defaultExpectation == nil {
		mmBulkUpsert.defaultExpectation = &SlotRepositoryMockBulkUpsertExpectation{mock: mmBulkUpsert.mock}
	}
	mmBulkUpsert.defaultExpectation.results = &SlotRepositoryMockBulkUpsertResults{err}
	mmBulkUpsert.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmBulkUpsert.mock
}

// Set uses given function f to mock the SlotRepository.BulkUpsert method
func (mmBulkUpsert *mSlotRepositoryMockBulkUpsert) Set(f func(ctx context.Context, slots []domain.Slot) (err error)) *SlotRepositoryMock {
	if mmBulkUpsert.defaultExpectation != nil {
		mmBulkUpsert.mock.t.Fatalf("Default expectation is already set for the SlotRepository.BulkUpsert method")
	}

	if len(mmBulkUpsert.expectations) > 0 {
		mmBulkUpsert.mock.t.Fatalf("Some expectations are already set for the SlotRepository.BulkUpsert method")
	}

	mmBulkUpsert.mock.funcBulkUpsert = f
	mmBulkUpsert.mock.funcBulkUpsertOrigin = minimock.CallerInfo(1)
	return mmBulkUpsert.mock
}

// When sets expectation for the SlotRepository.BulkUpsert which will trigger the result defined by the following
// Then helper
func (mmBulkUpsert *mSlotRepositoryMockBulkUpsert) When(ctx context.Context, slots []domain.Slot) *SlotRepositoryMockBulkUpsertExpectation {
	if mmBulkUpsert.mock.funcBulkUpsert != nil {
		mmBulkUpsert.mock.t.Fatalf("SlotRepositoryMock.BulkUpsert mock is already set by Set")
	}

	expectation := &SlotRepositoryMockBulkUpsertExpectation{
		mock:               mmBulkUpsert.mock,
		params:             &SlotRepositoryMockBulkUpsertParams{ctx, slots},
		expectationOrigins: SlotRepositoryMockBulkUpsertExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmBulkUpsert.expectations = append(mmBulkUpsert.expectations, expectation)
	return expectation
}

// Then sets up SlotRepository.BulkUpsert return parameters for the expectation previously defined by the When method
func (e *SlotRepositoryMockBulkUpsertExpectation) Then(err error) *SlotRepositoryMock {
	e.results = &SlotRepositoryMockBulkUpsertResults{err}
	return e.mock
}

// Times sets number of times SlotRepository.BulkUpsert should be invoked
func (mmBulkUpsert *mSlotRepositoryMockBulkUpsert) Times(n uint64) *mSlotRepositoryMockBulkUpsert {
	if n == 0 {
		mmBulkUpsert.mock.t.Fatalf("Times of SlotRepositoryMock.BulkUpsert mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmBulkUpsert.expectedInvocations, n)
	mmBulkUpsert.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmBulkUpsert
}

func (mmBulkUpsert *mSlotRepositoryMockBulkUpsert) invocationsDone() bool {
	if len(mmBulkUpsert.expectations) == 0 && mmBulkUpsert.defaultExpectation == nil && mmBulkUpsert.mock.funcBulkUpsert == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmBulkUpsert.mock.afterBulkUpsertCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmBulkUpsert.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// BulkUpsert implements mm_repository.SlotRepository
func (mmBulkUpsert *SlotRepositoryMock) BulkUpsert(ctx context.Context, slots []domain.Slot) (err error) {
	mm_atomic.AddUint64(&mmBulkUpsert.beforeBulkUpsertCounter, 1)
	defer mm_atomic.AddUint64(&mmBulkUpsert.afterBulkUpsertCounter, 1)

	mmBulkUpsert.t.Helper()

	if mmBulkUpsert.inspectFuncBulkUpsert != nil {
		mmBulkUpsert.inspectFuncBulkUpsert(ctx, slots)
	}

	mm_params := SlotRepositoryMockBulkUpsertParams{ctx, slots}

	// Record call args
	mmBulkUpsert.BulkUpsertMock.mutex.Lock()
	mmBulkUpsert.BulkUpsertMock.callArgs = append(mmBulkUpsert.BulkUpsertMock.callArgs, &mm_params)
	mmBulkUpsert.BulkUpsertMock.mutex.Unlock()

	for _, e := range mmBulkUpsert.BulkUpsertMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmBulkUpsert.BulkUpsertMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmBulkUpsert.BulkUpsertMock.defaultExpectation.Counter, 1)
		mm_want := mmBulkUpsert.BulkUpsertMock.defaultExpectation.params
		mm_want_ptrs := mmBulkUpsert.BulkUpsertMock.defaultExpectation.paramPtrs

		mm_got := SlotRepositoryMockBulkUpsertParams{ctx, slots}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmBulkUpsert.t.Errorf("SlotRepositoryMock.BulkUpsert got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmBulkUpsert.BulkUpsertMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.slots != nil && !minimock.Equal(*mm_want_ptrs.slots, mm_got.slots) {
				mmBulkUpsert.t.Errorf("SlotRepositoryMock.BulkUpsert got unexpected parameter slots, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmBulkUpsert.BulkUpsertMock.defaultExpectation.expectationOrigins.originSlots, *mm_want_ptrs.slots, mm_got.slots, minimock.Diff(*mm_want_ptrs.slots, mm_got.slots))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmBulkUpsert.t.Errorf("SlotRepositoryMock.BulkUpsert got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmBulkUpsert.BulkUpsertMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmBulkUpsert.BulkUpsertMock.defaultExpectation.results
		if mm_results == nil {
			mmBulkUpsert.t.Fatal("No results are set for the SlotRepositoryMock.BulkUpsert")
		}
		return (*mm_results).err
	}
	if mmBulkUpsert.funcBulkUpsert != nil {
		return mmBulkUpsert.funcBulkUpsert(ctx, slots)
	}
	mmBulkUpsert.t.Fatalf("Unexpected call to SlotRepositoryMock.BulkUpsert. %v %v", ctx, slots)
	return
}

// BulkUpsertAfterCounter returns a count of finished SlotRepositoryMock.BulkUpsert invocations
func (mmBulkUpsert *SlotRepositoryMock) BulkUpsertAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmBulkUpsert.afterBulkUpsertCounter)
}

// BulkUpsertBeforeCounter returns a count of SlotRepositoryMock.BulkUpsert invocations
func (mmBulkUpsert *SlotRepositoryMock) BulkUpsertBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmBulkUpsert.beforeBulkUpsertCounter)
}

// Calls returns a list of arguments used in each call to SlotRepositoryMock.BulkUpsert.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmBulkUpsert *mSlotRepositoryMockBulkUpsert) Calls() []*SlotRepositoryMockBulkUpsertParams {
	mmBulkUpsert.mutex.RLock()

	argCopy := make([]*SlotRepositoryMockBulkUpsertParams, len(mmBulkUpsert.callArgs))
	copy(argCopy, mmBulkUpsert.callArgs)

	mmBulkUpsert.mutex.RUnlock()

	return argCopy
}

// MinimockBulkUpsertDone returns true if the count of the BulkUpsert invocations corresponds
// the number of defined expectations
func (m *SlotRepositoryMock) MinimockBulkUpsertDone() bool {
	if m.BulkUpsertMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.BulkUpsertMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.BulkUpsertMock.invocationsDone()
}

// MinimockBulkUpsertInspect logs each unmet expectation
func (m *SlotRepositoryMock) MinimockBulkUpsertInspect() {
	for _, e := range m.BulkUpsertMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SlotRepositoryMock.BulkUpsert at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterBulkUpsertCounter := mm_atomic.LoadUint64(&m.afterBulkUpsertCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.BulkUpsertMock.defaultExpectation != nil && afterBulkUpsertCounter < 1 {
		if m.BulkUpsertMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to SlotRepositoryMock.BulkUpsert at\n%s", m.BulkUpsertMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to SlotRepositoryMock.BulkUpsert at\n%s with params: %#v", m.BulkUpsertMock.defaultExpectation.expectationOrigins.origin, *m.BulkUpsertMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcBulkUpsert != nil && afterBulkUpsertCounter < 1 {
		m.t.Errorf("Expected call to SlotRepositoryMock.BulkUpsert at\n%s", m.funcBulkUpsertOrigin)
	}

	if !m.BulkUpsertMock.invocationsDone() && afterBulkUpsertCounter > 0 {
		m.t.Errorf("Expected %d calls to SlotRepositoryMock.BulkUpsert at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.BulkUpsertMock.expectedInvocations), m.BulkUpsertMock.expectedInvocationsOrigin, afterBulkUpsertCounter)
	}
}

type mSlotRepositoryMockDateHasSlots struct {
	optional           bool
	mock               *SlotRepositoryMock
	defaultExpectation *SlotRepositoryMockDateHasSlotsExpectation
	expectations       []*SlotRepositoryMockDateHasSlotsExpectation

	callArgs []*SlotRepositoryMockDateHasSlotsParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// SlotRepositoryMockDateHasSlotsExpectation specifies expectation struct of the SlotRepository.DateHasSlots
type SlotRepositoryMockDateHasSlotsExpectation struct {
	mock               *SlotRepositoryMock
	params             *SlotRepositoryMockDateHasSlotsParams
	paramPtrs          *SlotRepositoryMockDateHasSlotsParamPtrs
	expectationOrigins SlotRepositoryMockDateHasSlotsExpectationOrigins
	results            *SlotRepositoryMockDateHasSlotsResults
	returnOrigin       string
	Counter            uint64
}

// SlotRepositoryMockDateHasSlotsParams contains parameters of the SlotRepository.DateHasSlots
type SlotRepositoryMockDateHasSlotsParams struct {
	ctx    context.Context
	roomID string
	date   time.Time
}

// SlotRepositoryMockDateHasSlotsParamPtrs contains pointers to parameters of the SlotRepository.DateHasSlots
type SlotRepositoryMockDateHasSlotsParamPtrs struct {
	ctx    *context.Context
	roomID *string
	date   *time.Time
}

// SlotRepositoryMockDateHasSlotsResults contains results of the SlotRepository.DateHasSlots
type SlotRepositoryMockDateHasSlotsResults struct {
	b1  bool
	err error
}

// SlotRepositoryMockDateHasSlotsOrigins contains origins of expectations of the SlotRepository.DateHasSlots
type SlotRepositoryMockDateHasSlotsExpectationOrigins struct {
	origin       string
	originCtx    string
	originRoomID string
	originDate   string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDateHasSlots *mSlotRepositoryMockDateHasSlots) Optional() *mSlotRepositoryMockDateHasSlots {
	mmDateHasSlots.optional = true
	return mmDateHasSlots
}

// Expect sets up expected params for SlotRepository.DateHasSlots
func (mmDateHasSlots *mSlotRepositoryMockDateHasSlots) Expect(ctx context.Context, roomID string, date time.Time) *mSlotRepositoryMockDateHasSlots {
	if mmDateHasSlots.mock.funcDateHasSlots != nil {
		mmDateHasSlots.mock.t.Fatalf("SlotRepositoryMock.DateHasSlots mock is already set by Set")
	}

	if mmDateHasSlots.defaultExpectation == nil {
		mmDateHasSlots.defaultExpectation = &SlotRepositoryMockDateHasSlotsExpectation{}
	}

	if mmDateHasSlots.defaultExpectation.paramPtrs != nil {
		mmDateHasSlots.mock.t.Fatalf("SlotRepositoryMock.DateHasSlots mock is already set by ExpectParams functions")
	}

	mmDateHasSlots.defaultExpectation.params = &SlotRepositoryMockDateHasSlotsParams{ctx, roomID, date}
	mmDateHasSlots.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDateHasSlots.expectations {
		if minimock.Equal(e.params, mmDateHasSlots.defaultExpectation.params) {
			mmDateHasSlots.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDateHasSlots.defaultExpectation.params)
		}
	}

	return mmDateHasSlots
}

// ExpectCtxParam1 sets up expected param ctx for SlotRepository.DateHasSlots
func (mmDateHasSlots *mSlotRepositoryMockDateHasSlots) ExpectCtxParam1(ctx context.Context) *mSlotRepositoryMockDateHasSlots {
	if mmDateHasSlots.mock.funcDateHasSlots != nil {
		mmDateHasSlots.mock.t.Fatalf("SlotRepositoryMock.DateHasSlots mock is already set by Set")
	}

	if mmDateHasSlots.defaultExpectation == nil {
		mmDateHasSlots.defaultExpectation = &SlotRepositoryMockDateHasSlotsExpectation{}
	}

	if mmDateHasSlots.defaultExpectation.params != nil {
		mmDateHasSlots.mock.t.Fatalf("SlotRepositoryMock.DateHasSlots mock is already set by Expect")
	}

	if mmDateHasSlots.defaultExpectation.paramPtrs == nil {
		mmDateHasSlots.defaultExpectation.paramPtrs = &SlotRepositoryMockDateHasSlotsParamPtrs{}
	}
	mmDateHasSlots.defaultExpectation.paramPtrs.ctx = &ctx
	mmDateHasSlots.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmDateHasSlots
}

// ExpectRoomIDParam2 sets up expected param roomID for SlotRepository.DateHasSlots
func (mmDateHasSlots *mSlotRepositoryMockDateHasSlots) ExpectRoomIDParam2(roomID string) *mSlotRepositoryMockDateHasSlots {
	if mmDateHasSlots.mock.funcDateHasSlots != nil {
		mmDateHasSlots.mock.t.Fatalf("SlotRepositoryMock.DateHasSlots mock is already set by Set")
	}

	if mmDateHasSlots.defaultExpectation == nil {
		mmDateHasSlots.defaultExpectation = &SlotRepositoryMockDateHasSlotsExpectation{}
	}

	if mmDateHasSlots.defaultExpectation.params != nil {
		mmDateHasSlots.mock.t.Fatalf("SlotRepositoryMock.DateHasSlots mock is already set by Expect")
	}

	if mmDateHasSlots.defaultExpectation.paramPtrs == nil {
		mmDateHasSlots.defaultExpectation.paramPtrs = &SlotRepositoryMockDateHasSlotsParamPtrs{}
	}
	mmDateHasSlots.defaultExpectation.paramPtrs.roomID = &roomID
	mmDateHasSlots.defaultExpectation.expectationOrigins.originRoomID = minimock.CallerInfo(1)

	return mmDateHasSlots
}

// ExpectDateParam3 sets up expected param date for SlotRepository.DateHasSlots
func (mmDateHasSlots *mSlotRepositoryMockDateHasSlots) ExpectDateParam3(date time.Time) *mSlotRepositoryMockDateHasSlots {
	if mmDateHasSlots.mock.funcDateHasSlots != nil {
		mmDateHasSlots.mock.t.Fatalf("SlotRepositoryMock.DateHasSlots mock is already set by Set")
	}

	if mmDateHasSlots.defaultExpectation == nil {
		mmDateHasSlots.defaultExpectation = &SlotRepositoryMockDateHasSlotsExpectation{}
	}

	if mmDateHasSlots.defaultExpectation.params != nil {
		mmDateHasSlots.mock.t.Fatalf("SlotRepositoryMock.DateHasSlots mock is already set by Expect")
	}

	if mmDateHasSlots.defaultExpectation.paramPtrs == nil {
		mmDateHasSlots.defaultExpectation.paramPtrs = &SlotRepositoryMockDateHasSlotsParamPtrs{}
	}
	mmDateHasSlots.defaultExpectation.paramPtrs.date = &date
	mmDateHasSlots.defaultExpectation.expectationOrigins.originDate = minimock.CallerInfo(1)

	return mmDateHasSlots
}

// Inspect accepts an inspector function that has same arguments as the SlotRepository.DateHasSlots
func (mmDateHasSlots *mSlotRepositoryMockDateHasSlots) Inspect(f func(ctx context.Context, roomID string, date time.Time)) *mSlotRepositoryMockDateHasSlots {
	if mmDateHasSlots.mock.inspectFuncDateHasSlots != nil {
		mmDateHasSlots.mock.t.Fatalf("Inspect function is already set for SlotRepositoryMock.DateHasSlots")
	}

	mmDateHasSlots.mock.inspectFuncDateHasSlots = f

	return mmDateHasSlots
}

// Return sets up results that will be returned by SlotRepository.DateHasSlots
func (mmDateHasSlots *mSlotRepositoryMockDateHasSlots) Return(b1 bool, err error) *SlotRepositoryMock {
	if mmDateHasSlots.mock.funcDateHasSlots != nil {
		mmDateHasSlots.mock.t.Fatalf("SlotRepositoryMock.DateHasSlots mock is already set by Set")
	}

	if mmDateHasSlots.defaultExpectation == nil {
		mmDateHasSlots.defaultExpectation = &SlotRepositoryMockDateHasSlotsExpectation{mock: mmDateHasSlots.mock}
	}
	mmDateHasSlots.defaultExpectation.results = &SlotRepositoryMockDateHasSlotsResults{b1, err}
	mmDateHasSlots.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDateHasSlots.mock
}

// Set uses given function f to mock the SlotRepository.DateHasSlots method
func (mmDateHasSlots *mSlotRepositoryMockDateHasSlots) Set(f func(ctx context.Context, roomID string, date time.Time) (b1 bool, err error)) *SlotRepositoryMock {
	if mmDateHasSlots.defaultExpectation != nil {
		mmDateHasSlots.mock.t.Fatalf("Default expectation is already set for the SlotRepository.DateHasSlots method")
	}

	if len(mmDateHasSlots.expectations) > 0 {
		mmDateHasSlots.mock.t.Fatalf("Some expectations are already set for the SlotRepository.DateHasSlots method")
	}

	mmDateHasSlots.mock.funcDateHasSlots = f
	mmDateHasSlots.mock.funcDateHasSlotsOrigin = minimock.CallerInfo(1)
	return mmDateHasSlots.mock
}

// When sets expectation for the SlotRepository.DateHasSlots which will trigger the result defined by the following
// Then helper
func (mmDateHasSlots *mSlotRepositoryMockDateHasSlots) When(ctx context.Context, roomID string, date time.Time) *SlotRepositoryMockDateHasSlotsExpectation {
	if mmDateHasSlots.mock.funcDateHasSlots != nil {
		mmDateHasSlots.mock.t.Fatalf("SlotRepositoryMock.DateHasSlots mock is already set by Set")
	}

	expectation := &SlotRepositoryMockDateHasSlotsExpectation{
		mock:               mmDateHasSlots.mock,
		params:             &SlotRepositoryMockDateHasSlotsParams{ctx, roomID, date},
		expectationOrigins: SlotRepositoryMockDateHasSlotsExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDateHasSlots.expectations = append(mmDateHasSlots.expectations, expectation)
	return expectation
}

// Then sets up SlotRepository.DateHasSlots return parameters for the expectation previously defined by the When method
func (e *SlotRepositoryMockDateHasSlotsExpectation) Then(b1 bool, err error) *SlotRepositoryMock {
	e.results = &SlotRepositoryMockDateHasSlotsResults{b1, err}
	return e.mock
}

// Times sets number of times SlotRepository.DateHasSlots should be invoked
func (mmDateHasSlots *mSlotRepositoryMockDateHasSlots) Times(n uint64) *mSlotRepositoryMockDateHasSlots {
	if n == 0 {
		mmDateHasSlots.mock.t.Fatalf("Times of SlotRepositoryMock.DateHasSlots mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDateHasSlots.expectedInvocations, n)
	mmDateHasSlots.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDateHasSlots
}

func (mmDateHasSlots *mSlotRepositoryMockDateHasSlots) invocationsDone() bool {
	if len(mmDateHasSlots.expectations) == 0 && mmDateHasSlots.defaultExpectation == nil && mmDateHasSlots.mock.funcDateHasSlots == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDateHasSlots.mock.afterDateHasSlotsCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDateHasSlots.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// DateHasSlots implements mm_repository.SlotRepository
func (mmDateHasSlots *SlotRepositoryMock) DateHasSlots(ctx context.Context, roomID string, date time.Time) (b1 bool, err error) {
	mm_atomic.AddUint64(&mmDateHasSlots.beforeDateHasSlotsCounter, 1)
	defer mm_atomic.AddUint64(&mmDateHasSlots.afterDateHasSlotsCounter, 1)

	mmDateHasSlots.t.Helper()

	if mmDateHasSlots.inspectFuncDateHasSlots != nil {
		mmDateHasSlots.inspectFuncDateHasSlots(ctx, roomID, date)
	}

	mm_params := SlotRepositoryMockDateHasSlotsParams{ctx, roomID, date}

	// Record call args
	mmDateHasSlots.DateHasSlotsMock.mutex.Lock()
	mmDateHasSlots.DateHasSlotsMock.callArgs = append(mmDateHasSlots.DateHasSlotsMock.callArgs, &mm_params)
	mmDateHasSlots.DateHasSlotsMock.mutex.Unlock()

	for _, e := range mmDateHasSlots.DateHasSlotsMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.b1, e.results.err
		}
	}

	if mmDateHasSlots.DateHasSlotsMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDateHasSlots.DateHasSlotsMock.defaultExpectation.Counter, 1)
		mm_want := mmDateHasSlots.DateHasSlotsMock.defaultExpectation.params
		mm_want_ptrs := mmDateHasSlots.DateHasSlotsMock.defaultExpectation.paramPtrs

		mm_got := SlotRepositoryMockDateHasSlotsParams{ctx, roomID, date}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmDateHasSlots.t.Errorf("SlotRepositoryMock.DateHasSlots got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDateHasSlots.DateHasSlotsMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.roomID != nil && !minimock.Equal(*mm_want_ptrs.roomID, mm_got.roomID) {
				mmDateHasSlots.t.Errorf("SlotRepositoryMock.DateHasSlots got unexpected parameter roomID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDateHasSlots.DateHasSlotsMock.defaultExpectation.expectationOrigins.originRoomID, *mm_want_ptrs.roomID, mm_got.roomID, minimock.Diff(*mm_want_ptrs.roomID, mm_got.roomID))
			}

			if mm_want_ptrs.date != nil && !minimock.Equal(*mm_want_ptrs.date, mm_got.date) {
				mmDateHasSlots.t.Errorf("SlotRepositoryMock.DateHasSlots got unexpected parameter date, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDateHasSlots.DateHasSlotsMock.defaultExpectation.expectationOrigins.originDate, *mm_want_ptrs.date, mm_got.date, minimock.Diff(*mm_want_ptrs.date, mm_got.date))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDateHasSlots.t.Errorf("SlotRepositoryMock.DateHasSlots got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDateHasSlots.DateHasSlotsMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDateHasSlots.DateHasSlotsMock.defaultExpectation.results
		if mm_results == nil {
			mmDateHasSlots.t.Fatal("No results are set for the SlotRepositoryMock.DateHasSlots")
		}
		return (*mm_results).b1, (*mm_results).err
	}
	if mmDateHasSlots.funcDateHasSlots != nil {
		return mmDateHasSlots.funcDateHasSlots(ctx, roomID, date)
	}
	mmDateHasSlots.t.Fatalf("Unexpected call to SlotRepositoryMock.DateHasSlots. %v %v %v", ctx, roomID, date)
	return
}

// DateHasSlotsAfterCounter returns a count of finished SlotRepositoryMock.DateHasSlots invocations
func (mmDateHasSlots *SlotRepositoryMock) DateHasSlotsAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDateHasSlots.afterDateHasSlotsCounter)
}

// DateHasSlotsBeforeCounter returns a count of SlotRepositoryMock.DateHasSlots invocations
func (mmDateHasSlots *SlotRepositoryMock) DateHasSlotsBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDateHasSlots.beforeDateHasSlotsCounter)
}

// Calls returns a list of arguments used in each call to SlotRepositoryMock.DateHasSlots.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDateHasSlots *mSlotRepositoryMockDateHasSlots) Calls() []*SlotRepositoryMockDateHasSlotsParams {
	mmDateHasSlots.mutex.RLock()

	argCopy := make([]*SlotRepositoryMockDateHasSlotsParams, len(mmDateHasSlots.callArgs))
	copy(argCopy, mmDateHasSlots.callArgs)

	mmDateHasSlots.mutex.RUnlock()

	return argCopy
}

// MinimockDateHasSlotsDone returns true if the count of the DateHasSlots invocations corresponds
// the number of defined expectations
func (m *SlotRepositoryMock) MinimockDateHasSlotsDone() bool {
	if m.DateHasSlotsMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DateHasSlotsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DateHasSlotsMock.invocationsDone()
}

// MinimockDateHasSlotsInspect logs each unmet expectation
func (m *SlotRepositoryMock) MinimockDateHasSlotsInspect() {
	for _, e := range m.DateHasSlotsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SlotRepositoryMock.DateHasSlots at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDateHasSlotsCounter := mm_atomic.LoadUint64(&m.afterDateHasSlotsCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DateHasSlotsMock.defaultExpectation != nil && afterDateHasSlotsCounter < 1 {
		if m.DateHasSlotsMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to SlotRepositoryMock.DateHasSlots at\n%s", m.DateHasSlotsMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to SlotRepositoryMock.DateHasSlots at\n%s with params: %#v", m.DateHasSlotsMock.defaultExpectation.expectationOrigins.origin, *m.DateHasSlotsMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDateHasSlots != nil && afterDateHasSlotsCounter < 1 {
		m.t.Errorf("Expected call to SlotRepositoryMock.DateHasSlots at\n%s", m.funcDateHasSlotsOrigin)
	}

	if !m.DateHasSlotsMock.invocationsDone() && afterDateHasSlotsCounter > 0 {
		m.t.Errorf("Expected %d calls to SlotRepositoryMock.DateHasSlots at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DateHasSlotsMock.expectedInvocations), m.DateHasSlotsMock.expectedInvocationsOrigin, afterDateHasSlotsCounter)
	}
}

type mSlotRepositoryMockGetByID struct {
	optional           bool
	mock               *SlotRepositoryMock
	defaultExpectation *SlotRepositoryMockGetByIDExpectation
	expectations       []*SlotRepositoryMockGetByIDExpectation

	callArgs []*SlotRepositoryMockGetByIDParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// SlotRepositoryMockGetByIDExpectation specifies expectation struct of the SlotRepository.GetByID
type SlotRepositoryMockGetByIDExpectation struct {
	mock               *SlotRepositoryMock
	params             *SlotRepositoryMockGetByIDParams
	paramPtrs          *SlotRepositoryMockGetByIDParamPtrs
	expectationOrigins SlotRepositoryMockGetByIDExpectationOrigins
	results            *SlotRepositoryMockGetByIDResults
	returnOrigin       string
	Counter            uint64
}

// SlotRepositoryMockGetByIDParams contains parameters of the SlotRepository.GetByID
type SlotRepositoryMockGetByIDParams struct {
	ctx    context.Context
	slotID string
}

// SlotRepositoryMockGetByIDParamPtrs contains pointers to parameters of the SlotRepository.GetByID
type SlotRepositoryMockGetByIDParamPtrs struct {
	ctx    *context.Context
	slotID *string
}

// SlotRepositoryMockGetByIDResults contains results of the SlotRepository.GetByID
type SlotRepositoryMockGetByIDResults struct {
	s1  domain.Slot
	err error
}

// SlotRepositoryMockGetByIDOrigins contains origins of expectations of the SlotRepository.GetByID
type SlotRepositoryMockGetByIDExpectationOrigins struct {
	origin       string
	originCtx    string
	originSlotID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetByID *mSlotRepositoryMockGetByID) Optional() *mSlotRepositoryMockGetByID {
	mmGetByID.optional = true
	return mmGetByID
}

// Expect sets up expected params for SlotRepository.GetByID
func (mmGetByID *mSlotRepositoryMockGetByID) Expect(ctx context.Context, slotID string) *mSlotRepositoryMockGetByID {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("SlotRepositoryMock.GetByID mock is already set by Set")
	}

	if mmGetByID.defaultExpectation == nil {
		mmGetByID.defaultExpectation = &SlotRepositoryMockGetByIDExpectation{}
	}

	if mmGetByID.defaultExpectation.paramPtrs != nil {
		mmGetByID.mock.t.Fatalf("SlotRepositoryMock.GetByID mock is already set by ExpectParams functions")
	}

	mmGetByID.defaultExpectation.params = &SlotRepositoryMockGetByIDParams{ctx, slotID}
	mmGetByID.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetByID.expectations {
		if minimock.Equal(e.params, mmGetByID.defaultExpectation.params) {
			mmGetByID.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetByID.defaultExpectation.params)
		}
	}

	return mmGetByID
}

// ExpectCtxParam1 sets up expected param ctx for SlotRepository.GetByID
func (mmGetByID *mSlotRepositoryMockGetByID) ExpectCtxParam1(ctx context.Context) *mSlotRepositoryMockGetByID {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("SlotRepositoryMock.GetByID mock is already set by Set")
	}

	if mmGetByID.defaultExpectation == nil {
		mmGetByID.defaultExpectation = &SlotRepositoryMockGetByIDExpectation{}
	}

	if mmGetByID.defaultExpectation.params != nil {
		mmGetByID.mock.t.Fatalf("SlotRepositoryMock.GetByID mock is already set by Expect")
	}

	if mmGetByID.defaultExpectation.paramPtrs == nil {
		mmGetByID.defaultExpectation.paramPtrs = &SlotRepositoryMockGetByIDParamPtrs{}
	}
	mmGetByID.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetByID.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetByID
}

// ExpectSlotIDParam2 sets up expected param slotID for SlotRepository.GetByID
func (mmGetByID *mSlotRepositoryMockGetByID) ExpectSlotIDParam2(slotID string) *mSlotRepositoryMockGetByID {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("SlotRepositoryMock.GetByID mock is already set by Set")
	}

	if mmGetByID.defaultExpectation == nil {
		mmGetByID.defaultExpectation = &SlotRepositoryMockGetByIDExpectation{}
	}

	if mmGetByID.defaultExpectation.params != nil {
		mmGetByID.mock.t.Fatalf("SlotRepositoryMock.GetByID mock is already set by Expect")
	}

	if mmGetByID.defaultExpectation.paramPtrs == nil {
		mmGetByID.defaultExpectation.paramPtrs = &SlotRepositoryMockGetByIDParamPtrs{}
	}
	mmGetByID.defaultExpectation.paramPtrs.slotID = &slotID
	mmGetByID.defaultExpectation.expectationOrigins.originSlotID = minimock.CallerInfo(1)

	return mmGetByID
}

// Inspect accepts an inspector function that has same arguments as the SlotRepository.GetByID
func (mmGetByID *mSlotRepositoryMockGetByID) Inspect(f func(ctx context.Context, slotID string)) *mSlotRepositoryMockGetByID {
	if mmGetByID.mock.inspectFuncGetByID != nil {
		mmGetByID.mock.t.Fatalf("Inspect function is already set for SlotRepositoryMock.GetByID")
	}

	mmGetByID.mock.inspectFuncGetByID = f

	return mmGetByID
}

// Return sets up results that will be returned by SlotRepository.GetByID
func (mmGetByID *mSlotRepositoryMockGetByID) Return(s1 domain.Slot, err error) *SlotRepositoryMock {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("SlotRepositoryMock.GetByID mock is already set by Set")
	}

	if mmGetByID.defaultExpectation == nil {
		mmGetByID.defaultExpectation = &SlotRepositoryMockGetByIDExpectation{mock: mmGetByID.mock}
	}
	mmGetByID.defaultExpectation.results = &SlotRepositoryMockGetByIDResults{s1, err}
	mmGetByID.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetByID.mock
}

// Set uses given function f to mock the SlotRepository.GetByID method
func (mmGetByID *mSlotRepositoryMockGetByID) Set(f func(ctx context.Context, slotID string) (s1 domain.Slot, err error)) *SlotRepositoryMock {
	if mmGetByID.defaultExpectation != nil {
		mmGetByID.mock.t.Fatalf("Default expectation is already set for the SlotRepository.GetByID method")
	}

	if len(mmGetByID.expectations) > 0 {
		mmGetByID.mock.t.Fatalf("Some expectations are already set for the SlotRepository.GetByID method")
	}

	mmGetByID.mock.funcGetByID = f
	mmGetByID.mock.funcGetByIDOrigin = minimock.CallerInfo(1)
	return mmGetByID.mock
}

// When sets expectation for the SlotRepository.GetByID which will trigger the result defined by the following
// Then helper
func (mmGetByID *mSlotRepositoryMockGetByID) When(ctx context.Context, slotID string) *SlotRepositoryMockGetByIDExpectation {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("SlotRepositoryMock.GetByID mock is already set by Set")
	}

	expectation := &SlotRepositoryMockGetByIDExpectation{
		mock:               mmGetByID.mock,
		params:             &SlotRepositoryMockGetByIDParams{ctx, slotID},
		expectationOrigins: SlotRepositoryMockGetByIDExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetByID.expectations = append(mmGetByID.expectations, expectation)
	return expectation
}

// Then sets up SlotRepository.GetByID return parameters for the expectation previously defined by the When method
func (e *SlotRepositoryMockGetByIDExpectation) Then(s1 domain.Slot, err error) *SlotRepositoryMock {
	e.results = &SlotRepositoryMockGetByIDResults{s1, err}
	return e.mock
}

// Times sets number of times SlotRepository.GetByID should be invoked
func (mmGetByID *mSlotRepositoryMockGetByID) Times(n uint64) *mSlotRepositoryMockGetByID {
	if n == 0 {
		mmGetByID.mock.t.Fatalf("Times of SlotRepositoryMock.GetByID mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetByID.expectedInvocations, n)
	mmGetByID.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetByID
}

func (mmGetByID *mSlotRepositoryMockGetByID) invocationsDone() bool {
	if len(mmGetByID.expectations) == 0 && mmGetByID.defaultExpectation == nil && mmGetByID.mock.funcGetByID == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetByID.mock.afterGetByIDCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetByID.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetByID implements mm_repository.SlotRepository
func (mmGetByID *SlotRepositoryMock) GetByID(ctx context.Context, slotID string) (s1 domain.Slot, err error) {
	mm_atomic.AddUint64(&mmGetByID.beforeGetByIDCounter, 1)
	defer mm_atomic.AddUint64(&mmGetByID.afterGetByIDCounter, 1)

	mmGetByID.t.Helper()

	if mmGetByID.inspectFuncGetByID != nil {
		mmGetByID.inspectFuncGetByID(ctx, slotID)
	}

	mm_params := SlotRepositoryMockGetByIDParams{ctx, slotID}

	// Record call args
	mmGetByID.GetByIDMock.mutex.Lock()
	mmGetByID.GetByIDMock.callArgs = append(mmGetByID.GetByIDMock.callArgs, &mm_params)
	mmGetByID.GetByIDMock.mutex.Unlock()

	for _, e := range mmGetByID.GetByIDMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1, e.results.err
		}
	}

	if mmGetByID.GetByIDMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetByID.GetByIDMock.defaultExpectation.Counter, 1)
		mm_want := mmGetByID.GetByIDMock.defaultExpectation.params
		mm_want_ptrs := mmGetByID.GetByIDMock.defaultExpectation.paramPtrs

		mm_got := SlotRepositoryMockGetByIDParams{ctx, slotID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetByID.t.Errorf("SlotRepositoryMock.GetByID got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByID.GetByIDMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.slotID != nil && !minimock.Equal(*mm_want_ptrs.slotID, mm_got.slotID) {
				mmGetByID.t.Errorf("SlotRepositoryMock.GetByID got unexpected parameter slotID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByID.GetByIDMock.defaultExpectation.expectationOrigins.originSlotID, *mm_want_ptrs.slotID, mm_got.slotID, minimock.Diff(*mm_want_ptrs.slotID, mm_got.slotID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetByID.t.Errorf("SlotRepositoryMock.GetByID got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetByID.GetByIDMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetByID.GetByIDMock.defaultExpectation.results
		if mm_results == nil {
			mmGetByID.t.Fatal("No results are set for the SlotRepositoryMock.GetByID")
		}
		return (*mm_results).s1, (*mm_results).err
	}
	if mmGetByID.funcGetByID != nil {
		return mmGetByID.funcGetByID(ctx, slotID)
	}
	mmGetByID.t.Fatalf("Unexpected call to SlotRepositoryMock.GetByID. %v %v", ctx, slotID)
	return
}

// GetByIDAfterCounter returns a count of finished SlotRepositoryMock.GetByID invocations
func (mmGetByID *SlotRepositoryMock) GetByIDAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByID.afterGetByIDCounter)
}

// GetByIDBeforeCounter returns a count of SlotRepositoryMock.GetByID invocations
func (mmGetByID *SlotRepositoryMock) GetByIDBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByID.beforeGetByIDCounter)
}

// Calls returns a list of arguments used in each call to SlotRepositoryMock.GetByID.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetByID *mSlotRepositoryMockGetByID) Calls() []*SlotRepositoryMockGetByIDParams {
	mmGetByID.mutex.RLock()

	argCopy := make([]*SlotRepositoryMockGetByIDParams, len(mmGetByID.callArgs))
	copy(argCopy, mmGetByID.callArgs)

	mmGetByID.mutex.RUnlock()

	return argCopy
}

// MinimockGetByIDDone returns true if the count of the GetByID invocations corresponds
// the number of defined expectations
func (m *SlotRepositoryMock) MinimockGetByIDDone() bool {
	if m.GetByIDMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetByIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetByIDMock.invocationsDone()
}

// MinimockGetByIDInspect logs each unmet expectation
func (m *SlotRepositoryMock) MinimockGetByIDInspect() {
	for _, e := range m.GetByIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SlotRepositoryMock.GetByID at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetByIDCounter := mm_atomic.LoadUint64(&m.afterGetByIDCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetByIDMock.defaultExpectation != nil && afterGetByIDCounter < 1 {
		if m.GetByIDMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to SlotRepositoryMock.GetByID at\n%s", m.GetByIDMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to SlotRepositoryMock.GetByID at\n%s with params: %#v", m.GetByIDMock.defaultExpectation.expectationOrigins.origin, *m.GetByIDMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetByID != nil && afterGetByIDCounter < 1 {
		m.t.Errorf("Expected call to SlotRepositoryMock.GetByID at\n%s", m.funcGetByIDOrigin)
	}

	if !m.GetByIDMock.invocationsDone() && afterGetByIDCounter > 0 {
		m.t.Errorf("Expected %d calls to SlotRepositoryMock.GetByID at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetByIDMock.expectedInvocations), m.GetByIDMock.expectedInvocationsOrigin, afterGetByIDCounter)
	}
}

type mSlotRepositoryMockListAvailableByRoomAndDate struct {
	optional           bool
	mock               *SlotRepositoryMock
	defaultExpectation *SlotRepositoryMockListAvailableByRoomAndDateExpectation
	expectations       []*SlotRepositoryMockListAvailableByRoomAndDateExpectation

	callArgs []*SlotRepositoryMockListAvailableByRoomAndDateParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// SlotRepositoryMockListAvailableByRoomAndDateExpectation specifies expectation struct of the SlotRepository.ListAvailableByRoomAndDate
type SlotRepositoryMockListAvailableByRoomAndDateExpectation struct {
	mock               *SlotRepositoryMock
	params             *SlotRepositoryMockListAvailableByRoomAndDateParams
	paramPtrs          *SlotRepositoryMockListAvailableByRoomAndDateParamPtrs
	expectationOrigins SlotRepositoryMockListAvailableByRoomAndDateExpectationOrigins
	results            *SlotRepositoryMockListAvailableByRoomAndDateResults
	returnOrigin       string
	Counter            uint64
}

// SlotRepositoryMockListAvailableByRoomAndDateParams contains parameters of the SlotRepository.ListAvailableByRoomAndDate
type SlotRepositoryMockListAvailableByRoomAndDateParams struct {
	ctx    context.Context
	roomID string
	date   time.Time
}

// SlotRepositoryMockListAvailableByRoomAndDateParamPtrs contains pointers to parameters of the SlotRepository.ListAvailableByRoomAndDate
type SlotRepositoryMockListAvailableByRoomAndDateParamPtrs struct {
	ctx    *context.Context
	roomID *string
	date   *time.Time
}

// SlotRepositoryMockListAvailableByRoomAndDateResults contains results of the SlotRepository.ListAvailableByRoomAndDate
type SlotRepositoryMockListAvailableByRoomAndDateResults struct {
	sa1 []domain.Slot
	err error
}

// SlotRepositoryMockListAvailableByRoomAndDateOrigins contains origins of expectations of the SlotRepository.ListAvailableByRoomAndDate
type SlotRepositoryMockListAvailableByRoomAndDateExpectationOrigins struct {
	origin       string
	originCtx    string
	originRoomID string
	originDate   string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmListAvailableByRoomAndDate *mSlotRepositoryMockListAvailableByRoomAndDate) Optional() *mSlotRepositoryMockListAvailableByRoomAndDate {
	mmListAvailableByRoomAndDate.optional = true
	return mmListAvailableByRoomAndDate
}

// Expect sets up expected params for SlotRepository.ListAvailableByRoomAndDate
func (mmListAvailableByRoomAndDate *mSlotRepositoryMockListAvailableByRoomAndDate) Expect(ctx context.Context, roomID string, date time.Time) *mSlotRepositoryMockListAvailableByRoomAndDate {
	if mmListAvailableByRoomAndDate.mock.funcListAvailableByRoomAndDate != nil {
		mmListAvailableByRoomAndDate.mock.t.Fatalf("SlotRepositoryMock.ListAvailableByRoomAndDate mock is already set by Set")
	}

	if mmListAvailableByRoomAndDate.defaultExpectation == nil {
		mmListAvailableByRoomAndDate.defaultExpectation = &SlotRepositoryMockListAvailableByRoomAndDateExpectation{}
	}

	if mmListAvailableByRoomAndDate.defaultExpectation.paramPtrs != nil {
		mmListAvailableByRoomAndDate.mock.t.Fatalf("SlotRepositoryMock.ListAvailableByRoomAndDate mock is already set by ExpectParams functions")
	}

	mmListAvailableByRoomAndDate.defaultExpectation.params = &SlotRepositoryMockListAvailableByRoomAndDateParams{ctx, roomID, date}
	mmListAvailableByRoomAndDate.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmListAvailableByRoomAndDate.expectations {
		if minimock.Equal(e.params, mmListAvailableByRoomAndDate.defaultExpectation.params) {
			mmListAvailableByRoomAndDate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmListAvailableByRoomAndDate.defaultExpectation.params)
		}
	}

	return mmListAvailableByRoomAndDate
}

// ExpectCtxParam1 sets up expected param ctx for SlotRepository.ListAvailableByRoomAndDate
func (mmListAvailableByRoomAndDate *mSlotRepositoryMockListAvailableByRoomAndDate) ExpectCtxParam1(ctx context.Context) *mSlotRepositoryMockListAvailableByRoomAndDate {
	if mmListAvailableByRoomAndDate.mock.funcListAvailableByRoomAndDate != nil {
		mmListAvailableByRoomAndDate.mock.t.Fatalf("SlotRepositoryMock.ListAvailableByRoomAndDate mock is already set by Set")
	}

	if mmListAvailableByRoomAndDate.defaultExpectation == nil {
		mmListAvailableByRoomAndDate.defaultExpectation = &SlotRepositoryMockListAvailableByRoomAndDateExpectation{}
	}

	if mmListAvailableByRoomAndDate.defaultExpectation.params != nil {
		mmListAvailableByRoomAndDate.mock.t.Fatalf("SlotRepositoryMock.ListAvailableByRoomAndDate mock is already set by Expect")
	}

	if mmListAvailableByRoomAndDate.defaultExpectation.paramPtrs == nil {
		mmListAvailableByRoomAndDate.defaultExpectation.paramPtrs = &SlotRepositoryMockListAvailableByRoomAndDateParamPtrs{}
	}
	mmListAvailableByRoomAndDate.defaultExpectation.paramPtrs.ctx = &ctx
	mmListAvailableByRoomAndDate.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmListAvailableByRoomAndDate
}

// ExpectRoomIDParam2 sets up expected param roomID for SlotRepository.ListAvailableByRoomAndDate
func (mmListAvailableByRoomAndDate *mSlotRepositoryMockListAvailableByRoomAndDate) ExpectRoomIDParam2(roomID string) *mSlotRepositoryMockListAvailableByRoomAndDate {
	if mmListAvailableByRoomAndDate.mock.funcListAvailableByRoomAndDate != nil {
		mmListAvailableByRoomAndDate.mock.t.Fatalf("SlotRepositoryMock.ListAvailableByRoomAndDate mock is already set by Set")
	}

	if mmListAvailableByRoomAndDate.defaultExpectation == nil {
		mmListAvailableByRoomAndDate.defaultExpectation = &SlotRepositoryMockListAvailableByRoomAndDateExpectation{}
	}

	if mmListAvailableByRoomAndDate.defaultExpectation.params != nil {
		mmListAvailableByRoomAndDate.mock.t.Fatalf("SlotRepositoryMock.ListAvailableByRoomAndDate mock is already set by Expect")
	}

	if mmListAvailableByRoomAndDate.defaultExpectation.paramPtrs == nil {
		mmListAvailableByRoomAndDate.defaultExpectation.paramPtrs = &SlotRepositoryMockListAvailableByRoomAndDateParamPtrs{}
	}
	mmListAvailableByRoomAndDate.defaultExpectation.paramPtrs.roomID = &roomID
	mmListAvailableByRoomAndDate.defaultExpectation.expectationOrigins.originRoomID = minimock.CallerInfo(1)

	return mmListAvailableByRoomAndDate
}

// ExpectDateParam3 sets up expected param date for SlotRepository.ListAvailableByRoomAndDate
func (mmListAvailableByRoomAndDate *mSlotRepositoryMockListAvailableByRoomAndDate) ExpectDateParam3(date time.Time) *mSlotRepositoryMockListAvailableByRoomAndDate {
	if mmListAvailableByRoomAndDate.mock.funcListAvailableByRoomAndDate != nil {
		mmListAvailableByRoomAndDate.mock.t.Fatalf("SlotRepositoryMock.ListAvailableByRoomAndDate mock is already set by Set")
	}

	if mmListAvailableByRoomAndDate.defaultExpectation == nil {
		mmListAvailableByRoomAndDate.defaultExpectation = &SlotRepositoryMockListAvailableByRoomAndDateExpectation{}
	}

	if mmListAvailableByRoomAndDate.defaultExpectation.params != nil {
		mmListAvailableByRoomAndDate.mock.t.Fatalf("SlotRepositoryMock.ListAvailableByRoomAndDate mock is already set by Expect")
	}

	if mmListAvailableByRoomAndDate.defaultExpectation.paramPtrs == nil {
		mmListAvailableByRoomAndDate.defaultExpectation.paramPtrs = &SlotRepositoryMockListAvailableByRoomAndDateParamPtrs{}
	}
	mmListAvailableByRoomAndDate.defaultExpectation.paramPtrs.date = &date
	mmListAvailableByRoomAndDate.defaultExpectation.expectationOrigins.originDate = minimock.CallerInfo(1)

	return mmListAvailableByRoomAndDate
}

// Inspect accepts an inspector function that has same arguments as the SlotRepository.ListAvailableByRoomAndDate
func (mmListAvailableByRoomAndDate *mSlotRepositoryMockListAvailableByRoomAndDate) Inspect(f func(ctx context.Context, roomID string, date time.Time)) *mSlotRepositoryMockListAvailableByRoomAndDate {
	if mmListAvailableByRoomAndDate.mock.inspectFuncListAvailableByRoomAndDate != nil {
		mmListAvailableByRoomAndDate.mock.t.Fatalf("Inspect function is already set for SlotRepositoryMock.ListAvailableByRoomAndDate")
	}

	mmListAvailableByRoomAndDate.mock.inspectFuncListAvailableByRoomAndDate = f

	return mmListAvailableByRoomAndDate
}

// Return sets up results that will be returned by SlotRepository.ListAvailableByRoomAndDate
func (mmListAvailableByRoomAndDate *mSlotRepositoryMockListAvailableByRoomAndDate) Return(sa1 []domain.Slot, err error) *SlotRepositoryMock {
	if mmListAvailableByRoomAndDate.mock.funcListAvailableByRoomAndDate != nil {
		mmListAvailableByRoomAndDate.mock.t.Fatalf("SlotRepositoryMock.ListAvailableByRoomAndDate mock is already set by Set")
	}

	if mmListAvailableByRoomAndDate.defaultExpectation == nil {
		mmListAvailableByRoomAndDate.defaultExpectation = &SlotRepositoryMockListAvailableByRoomAndDateExpectation{mock: mmListAvailableByRoomAndDate.mock}
	}
	mmListAvailableByRoomAndDate.defaultExpectation.results = &SlotRepositoryMockListAvailableByRoomAndDateResults{sa1, err}
	mmListAvailableByRoomAndDate.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmListAvailableByRoomAndDate.mock
}

// Set uses given function f to mock the SlotRepository.ListAvailableByRoomAndDate method
func (mmListAvailableByRoomAndDate *mSlotRepositoryMockListAvailableByRoomAndDate) Set(f func(ctx context.Context, roomID string, date time.Time) (sa1 []domain.Slot, err error)) *SlotRepositoryMock {
	if mmListAvailableByRoomAndDate.defaultExpectation != nil {
		mmListAvailableByRoomAndDate.mock.t.Fatalf("Default expectation is already set for the SlotRepository.ListAvailableByRoomAndDate method")
	}

	if len(mmListAvailableByRoomAndDate.expectations) > 0 {
		mmListAvailableByRoomAndDate.mock.t.Fatalf("Some expectations are already set for the SlotRepository.ListAvailableByRoomAndDate method")
	}

	mmListAvailableByRoomAndDate.mock.funcListAvailableByRoomAndDate = f
	mmListAvailableByRoomAndDate.mock.funcListAvailableByRoomAndDateOrigin = minimock.CallerInfo(1)
	return mmListAvailableByRoomAndDate.mock
}

// When sets expectation for the SlotRepository.ListAvailableByRoomAndDate which will trigger the result defined by the following
// Then helper
func (mmListAvailableByRoomAndDate *mSlotRepositoryMockListAvailableByRoomAndDate) When(ctx context.Context, roomID string, date time.Time) *SlotRepositoryMockListAvailableByRoomAndDateExpectation {
	if mmListAvailableByRoomAndDate.mock.funcListAvailableByRoomAndDate != nil {
		mmListAvailableByRoomAndDate.mock.t.Fatalf("SlotRepositoryMock.ListAvailableByRoomAndDate mock is already set by Set")
	}

	expectation := &SlotRepositoryMockListAvailableByRoomAndDateExpectation{
		mock:               mmListAvailableByRoomAndDate.mock,
		params:             &SlotRepositoryMockListAvailableByRoomAndDateParams{ctx, roomID, date},
		expectationOrigins: SlotRepositoryMockListAvailableByRoomAndDateExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmListAvailableByRoomAndDate.expectations = append(mmListAvailableByRoomAndDate.expectations, expectation)
	return expectation
}

// Then sets up SlotRepository.ListAvailableByRoomAndDate return parameters for the expectation previously defined by the When method
func (e *SlotRepositoryMockListAvailableByRoomAndDateExpectation) Then(sa1 []domain.Slot, err error) *SlotRepositoryMock {
	e.results = &SlotRepositoryMockListAvailableByRoomAndDateResults{sa1, err}
	return e.mock
}

// Times sets number of times SlotRepository.ListAvailableByRoomAndDate should be invoked
func (mmListAvailableByRoomAndDate *mSlotRepositoryMockListAvailableByRoomAndDate) Times(n uint64) *mSlotRepositoryMockListAvailableByRoomAndDate {
	if n == 0 {
		mmListAvailableByRoomAndDate.mock.t.Fatalf("Times of SlotRepositoryMock.ListAvailableByRoomAndDate mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmListAvailableByRoomAndDate.expectedInvocations, n)
	mmListAvailableByRoomAndDate.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmListAvailableByRoomAndDate
}

func (mmListAvailableByRoomAndDate *mSlotRepositoryMockListAvailableByRoomAndDate) invocationsDone() bool {
	if len(mmListAvailableByRoomAndDate.expectations) == 0 && mmListAvailableByRoomAndDate.defaultExpectation == nil && mmListAvailableByRoomAndDate.mock.funcListAvailableByRoomAndDate == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmListAvailableByRoomAndDate.mock.afterListAvailableByRoomAndDateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmListAvailableByRoomAndDate.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// ListAvailableByRoomAndDate implements mm_repository.SlotRepository
func (mmListAvailableByRoomAndDate *SlotRepositoryMock) ListAvailableByRoomAndDate(ctx context.Context, roomID string, date time.Time) (sa1 []domain.Slot, err error) {
	mm_atomic.AddUint64(&mmListAvailableByRoomAndDate.beforeListAvailableByRoomAndDateCounter, 1)
	defer mm_atomic.AddUint64(&mmListAvailableByRoomAndDate.afterListAvailableByRoomAndDateCounter, 1)

	mmListAvailableByRoomAndDate.t.Helper()

	if mmListAvailableByRoomAndDate.inspectFuncListAvailableByRoomAndDate != nil {
		mmListAvailableByRoomAndDate.inspectFuncListAvailableByRoomAndDate(ctx, roomID, date)
	}

	mm_params := SlotRepositoryMockListAvailableByRoomAndDateParams{ctx, roomID, date}

	// Record call args
	mmListAvailableByRoomAndDate.ListAvailableByRoomAndDateMock.mutex.Lock()
	mmListAvailableByRoomAndDate.ListAvailableByRoomAndDateMock.callArgs = append(mmListAvailableByRoomAndDate.ListAvailableByRoomAndDateMock.callArgs, &mm_params)
	mmListAvailableByRoomAndDate.ListAvailableByRoomAndDateMock.mutex.Unlock()

	for _, e := range mmListAvailableByRoomAndDate.ListAvailableByRoomAndDateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.sa1, e.results.err
		}
	}

	if mmListAvailableByRoomAndDate.ListAvailableByRoomAndDateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmListAvailableByRoomAndDate.ListAvailableByRoomAndDateMock.defaultExpectation.Counter, 1)
		mm_want := mmListAvailableByRoomAndDate.ListAvailableByRoomAndDateMock.defaultExpectation.params
		mm_want_ptrs := mmListAvailableByRoomAndDate.ListAvailableByRoomAndDateMock.defaultExpectation.paramPtrs

		mm_got := SlotRepositoryMockListAvailableByRoomAndDateParams{ctx, roomID, date}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmListAvailableByRoomAndDate.t.Errorf("SlotRepositoryMock.ListAvailableByRoomAndDate got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmListAvailableByRoomAndDate.ListAvailableByRoomAndDateMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.roomID != nil && !minimock.Equal(*mm_want_ptrs.roomID, mm_got.roomID) {
				mmListAvailableByRoomAndDate.t.Errorf("SlotRepositoryMock.ListAvailableByRoomAndDate got unexpected parameter roomID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmListAvailableByRoomAndDate.ListAvailableByRoomAndDateMock.defaultExpectation.expectationOrigins.originRoomID, *mm_want_ptrs.roomID, mm_got.roomID, minimock.Diff(*mm_want_ptrs.roomID, mm_got.roomID))
			}

			if mm_want_ptrs.date != nil && !minimock.Equal(*mm_want_ptrs.date, mm_got.date) {
				mmListAvailableByRoomAndDate.t.Errorf("SlotRepositoryMock.ListAvailableByRoomAndDate got unexpected parameter date, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmListAvailableByRoomAndDate.ListAvailableByRoomAndDateMock.defaultExpectation.expectationOrigins.originDate, *mm_want_ptrs.date, mm_got.date, minimock.Diff(*mm_want_ptrs.date, mm_got.date))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmListAvailableByRoomAndDate.t.Errorf("SlotRepositoryMock.ListAvailableByRoomAndDate got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmListAvailableByRoomAndDate.ListAvailableByRoomAndDateMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmListAvailableByRoomAndDate.ListAvailableByRoomAndDateMock.defaultExpectation.results
		if mm_results == nil {
			mmListAvailableByRoomAndDate.t.Fatal("No results are set for the SlotRepositoryMock.ListAvailableByRoomAndDate")
		}
		return (*mm_results).sa1, (*mm_results).err
	}
	if mmListAvailableByRoomAndDate.funcListAvailableByRoomAndDate != nil {
		return mmListAvailableByRoomAndDate.funcListAvailableByRoomAndDate(ctx, roomID, date)
	}
	mmListAvailableByRoomAndDate.t.Fatalf("Unexpected call to SlotRepositoryMock.ListAvailableByRoomAndDate. %v %v %v", ctx, roomID, date)
	return
}

// ListAvailableByRoomAndDateAfterCounter returns a count of finished SlotRepositoryMock.ListAvailableByRoomAndDate invocations
func (mmListAvailableByRoomAndDate *SlotRepositoryMock) ListAvailableByRoomAndDateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmListAvailableByRoomAndDate.afterListAvailableByRoomAndDateCounter)
}

// ListAvailableByRoomAndDateBeforeCounter returns a count of SlotRepositoryMock.ListAvailableByRoomAndDate invocations
func (mmListAvailableByRoomAndDate *SlotRepositoryMock) ListAvailableByRoomAndDateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmListAvailableByRoomAndDate.beforeListAvailableByRoomAndDateCounter)
}

// Calls returns a list of arguments used in each call to SlotRepositoryMock.ListAvailableByRoomAndDate.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmListAvailableByRoomAndDate *mSlotRepositoryMockListAvailableByRoomAndDate) Calls() []*SlotRepositoryMockListAvailableByRoomAndDateParams {
	mmListAvailableByRoomAndDate.mutex.RLock()

	argCopy := make([]*SlotRepositoryMockListAvailableByRoomAndDateParams, len(mmListAvailableByRoomAndDate.callArgs))
	copy(argCopy, mmListAvailableByRoomAndDate.callArgs)

	mmListAvailableByRoomAndDate.mutex.RUnlock()

	return argCopy
}

// MinimockListAvailableByRoomAndDateDone returns true if the count of the ListAvailableByRoomAndDate invocations corresponds
// the number of defined expectations
func (m *SlotRepositoryMock) MinimockListAvailableByRoomAndDateDone() bool {
	if m.ListAvailableByRoomAndDateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ListAvailableByRoomAndDateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ListAvailableByRoomAndDateMock.invocationsDone()
}

// MinimockListAvailableByRoomAndDateInspect logs each unmet expectation
func (m *SlotRepositoryMock) MinimockListAvailableByRoomAndDateInspect() {
	for _, e := range m.ListAvailableByRoomAndDateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SlotRepositoryMock.ListAvailableByRoomAndDate at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterListAvailableByRoomAndDateCounter := mm_atomic.LoadUint64(&m.afterListAvailableByRoomAndDateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ListAvailableByRoomAndDateMock.defaultExpectation != nil && afterListAvailableByRoomAndDateCounter < 1 {
		if m.ListAvailableByRoomAndDateMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to SlotRepositoryMock.ListAvailableByRoomAndDate at\n%s", m.ListAvailableByRoomAndDateMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to SlotRepositoryMock.ListAvailableByRoomAndDate at\n%s with params: %#v", m.ListAvailableByRoomAndDateMock.defaultExpectation.expectationOrigins.origin, *m.ListAvailableByRoomAndDateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcListAvailableByRoomAndDate != nil && afterListAvailableByRoomAndDateCounter < 1 {
		m.t.Errorf("Expected call to SlotRepositoryMock.ListAvailableByRoomAndDate at\n%s", m.funcListAvailableByRoomAndDateOrigin)
	}

	if !m.ListAvailableByRoomAndDateMock.invocationsDone() && afterListAvailableByRoomAndDateCounter > 0 {
		m.t.Errorf("Expected %d calls to SlotRepositoryMock.ListAvailableByRoomAndDate at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ListAvailableByRoomAndDateMock.expectedInvocations), m.ListAvailableByRoomAndDateMock.expectedInvocationsOrigin, afterListAvailableByRoomAndDateCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *SlotRepositoryMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockBulkUpsertInspect()

			m.MinimockDateHasSlotsInspect()

			m.MinimockGetByIDInspect()

			m.MinimockListAvailableByRoomAndDateInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *SlotRepositoryMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *SlotRepositoryMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockBulkUpsertDone() &&
		m.MinimockDateHasSlotsDone() &&
		m.MinimockGetByIDDone() &&
		m.MinimockListAvailableByRoomAndDateDone()
}
